package types

// DONTCOVER

import (
	"cosmossdk.io/errors"
)

// x/forum module sentinel errors
var (
	// Base errors (1100-1199)
	ErrInvalidSigner = errors.Register(ModuleName, 1100, "expected gov account as only signer for proposal message")
	ErrUnauthorized  = errors.Register(ModuleName, 1101, "unauthorized")
	ErrInvalidParam  = errors.Register(ModuleName, 1102, "invalid parameter")

	// Content errors (1200-1299)
	ErrContentTooLarge    = errors.Register(ModuleName, 1200, "content exceeds maximum size")
	ErrInvalidTag         = errors.Register(ModuleName, 1201, "invalid tag format")
	ErrTagLimitExceeded   = errors.Register(ModuleName, 1202, "tag limit exceeded for post")
	ErrTotalTagsExceeded  = errors.Register(ModuleName, 1203, "system-wide tag limit exceeded")
	ErrTagNotFound        = errors.Register(ModuleName, 1204, "tag not found")
	ErrTagAlreadyExists   = errors.Register(ModuleName, 1205, "tag already exists")
	ErrReservedTag        = errors.Register(ModuleName, 1206, "tag is reserved")
	ErrTagExpired         = errors.Register(ModuleName, 1207, "tag has expired")
	ErrInvalidContent     = errors.Register(ModuleName, 1208, "invalid content")
	ErrEmptyContent       = errors.Register(ModuleName, 1209, "content cannot be empty")
	ErrInvalidReasonCode  = errors.Register(ModuleName, 1210, "invalid reason code")
	ErrReasonTextRequired = errors.Register(ModuleName, 1211, "custom reason text required for OTHER reason code")
	ErrMaxTagLength       = errors.Register(ModuleName, 1212, "tag exceeds maximum length")

	// Post errors (1300-1399)
	ErrPostNotFound           = errors.Register(ModuleName, 1300, "post not found")
	ErrNotPostAuthor          = errors.Register(ModuleName, 1301, "not the post author")
	ErrPostAlreadyHidden      = errors.Register(ModuleName, 1302, "post is already hidden")
	ErrPostNotHidden          = errors.Register(ModuleName, 1303, "post is not hidden")
	ErrPostDeleted            = errors.Register(ModuleName, 1304, "post has been deleted")
	ErrPostArchived           = errors.Register(ModuleName, 1305, "post has been archived")
	ErrNotRootPost            = errors.Register(ModuleName, 1306, "operation only allowed on root posts")
	ErrIsRootPost             = errors.Register(ModuleName, 1307, "operation not allowed on root posts")
	ErrPostAlreadyPinned      = errors.Register(ModuleName, 1308, "post is already pinned")
	ErrPostNotPinned          = errors.Register(ModuleName, 1309, "post is not pinned")
	ErrMaxPinnedPosts         = errors.Register(ModuleName, 1310, "maximum pinned posts reached for category")
	ErrCannotDeleteHiddenPost = errors.Register(ModuleName, 1311, "cannot delete hidden post")
	ErrMaxReplyDepthExceeded  = errors.Register(ModuleName, 1312, "maximum reply depth exceeded")
	ErrParentPostNotFound     = errors.Register(ModuleName, 1313, "parent post not found")
	ErrInvalidPostStatus      = errors.Register(ModuleName, 1314, "invalid post status for this operation")

	// Thread errors (1400-1449)
	ErrThreadLocked          = errors.Register(ModuleName, 1400, "thread is locked")
	ErrThreadNotLocked       = errors.Register(ModuleName, 1401, "thread is not locked")
	ErrThreadAlreadyLocked   = errors.Register(ModuleName, 1402, "thread is already locked")
	ErrNotThreadAuthor       = errors.Register(ModuleName, 1403, "not the thread author")
	ErrLockReasonRequired    = errors.Register(ModuleName, 1404, "lock reason required for sentinels")
	ErrMoveReasonRequired    = errors.Register(ModuleName, 1405, "move reason required")
	ErrCannotMoveReservedTag = errors.Register(ModuleName, 1406, "cannot move thread with reserved tag")

	// Category errors (1450-1499)
	ErrCategoryNotFound      = errors.Register(ModuleName, 1450, "category not found")
	ErrCategoryAlreadyExists = errors.Register(ModuleName, 1451, "category already exists")
	ErrMembersOnlyWrite      = errors.Register(ModuleName, 1452, "category restricted to members only")
	ErrAdminOnlyWrite        = errors.Register(ModuleName, 1453, "category restricted to admins only")
	ErrInvalidCategoryId     = errors.Register(ModuleName, 1454, "invalid category ID")

	// Rate limit errors (1500-1549)
	ErrRateLimitExceeded      = errors.Register(ModuleName, 1500, "rate limit exceeded")
	ErrReactionLimitExceeded  = errors.Register(ModuleName, 1501, "reaction rate limit exceeded")
	ErrFlagLimitExceeded      = errors.Register(ModuleName, 1502, "flag rate limit exceeded")
	ErrFollowLimitExceeded    = errors.Register(ModuleName, 1503, "follow rate limit exceeded")
	ErrSalvationLimitExceeded = errors.Register(ModuleName, 1504, "salvation rate limit exceeded")
	ErrDownvoteLimitExceeded  = errors.Register(ModuleName, 1505, "downvote rate limit exceeded")

	// Moderation errors (1550-1649)
	ErrSentinelCooldown         = errors.Register(ModuleName, 1550, "sentinel is in cooldown period")
	ErrInsufficientBond         = errors.Register(ModuleName, 1551, "insufficient sentinel bond")
	ErrInsufficientBacking      = errors.Register(ModuleName, 1552, "insufficient sentinel backing")
	ErrInsufficientReputation   = errors.Register(ModuleName, 1553, "insufficient reputation tier")
	ErrSentinelDemoted          = errors.Register(ModuleName, 1554, "sentinel is demoted")
	ErrNotSentinel              = errors.Register(ModuleName, 1555, "not a registered sentinel")
	ErrAlreadySentinel          = errors.Register(ModuleName, 1556, "already registered as sentinel")
	ErrHideLimitExceeded        = errors.Register(ModuleName, 1557, "sentinel hide limit exceeded for epoch")
	ErrLockLimitExceeded        = errors.Register(ModuleName, 1558, "sentinel lock limit exceeded for epoch")
	ErrMoveLimitExceeded        = errors.Register(ModuleName, 1559, "sentinel move limit exceeded for epoch")
	ErrInsufficientLockBond     = errors.Register(ModuleName, 1560, "insufficient bond for thread locking")
	ErrInsufficientLockBacking  = errors.Register(ModuleName, 1561, "insufficient backing for thread locking")
	ErrSentinelNotFound         = errors.Register(ModuleName, 1562, "sentinel activity record not found")
	ErrCannotUnbondPendingHides = errors.Register(ModuleName, 1563, "cannot unbond with pending hide appeals")
	ErrDemotionCooldown         = errors.Register(ModuleName, 1564, "sentinel is in demotion cooldown")
	ErrBondAmountTooSmall       = errors.Register(ModuleName, 1565, "bond amount too small")
	ErrNotGovAuthority          = errors.Register(ModuleName, 1566, "not governance authority")
	ErrNotAuthorized            = errors.Register(ModuleName, 1567, "not authorized for this action")
	ErrPostStatus               = errors.Register(ModuleName, 1568, "invalid post status for this operation")

	// Appeal errors (1650-1699)
	ErrAppealCooldown         = errors.Register(ModuleName, 1650, "appeal cooldown not yet passed")
	ErrAppealAlreadyFiled     = errors.Register(ModuleName, 1651, "appeal already filed for this action")
	ErrAppealNotFound         = errors.Register(ModuleName, 1652, "appeal not found")
	ErrAppealPending          = errors.Register(ModuleName, 1653, "appeal is pending")
	ErrAppealExpired          = errors.Register(ModuleName, 1654, "appeal deadline has passed")
	ErrGovLockNotAppealable   = errors.Register(ModuleName, 1655, "governance locks must be appealed via gov action appeal")
	ErrLockAppealAlreadyFiled = errors.Register(ModuleName, 1656, "lock appeal already filed")
	ErrLockAppealExpired      = errors.Register(ModuleName, 1657, "lock appeal window has expired")
	ErrMoveAppealAlreadyFiled = errors.Register(ModuleName, 1658, "move appeal already filed")
	ErrMoveAppealExpired      = errors.Register(ModuleName, 1659, "move appeal window has expired")
	ErrPinDisputeAlreadyFiled = errors.Register(ModuleName, 1660, "pin dispute already filed")
	ErrNotSentinelPin         = errors.Register(ModuleName, 1661, "cannot dispute non-sentinel pins")

	// Archive errors (1700-1749)
	ErrThreadNotInactive                    = errors.Register(ModuleName, 1700, "thread is not inactive enough to archive")
	ErrArchiveCooldown                      = errors.Register(ModuleName, 1701, "archive cooldown not yet passed")
	ErrUnarchiveCooldown                    = errors.Register(ModuleName, 1702, "unarchive cooldown not yet passed")
	ErrArchiveCycleLimit                    = errors.Register(ModuleName, 1703, "archive cycle limit reached, requires governance approval")
	ErrArchivedThreadNotFound               = errors.Register(ModuleName, 1704, "archived thread not found")
	ErrCannotArchiveThreadWithPendingAppeal = errors.Register(ModuleName, 1706, "cannot archive thread with pending appeal")

	// Bounty errors (1750-1799)
	ErrBountyNotFound        = errors.Register(ModuleName, 1750, "bounty not found")
	ErrBountyNotActive       = errors.Register(ModuleName, 1751, "bounty is not active")
	ErrBountyExpired         = errors.Register(ModuleName, 1752, "bounty has expired")
	ErrBountyAlreadyExists   = errors.Register(ModuleName, 1753, "bounty already exists for this thread")
	ErrNotBountyCreator      = errors.Register(ModuleName, 1754, "not the bounty creator")
	ErrBountyAmountTooSmall  = errors.Register(ModuleName, 1755, "bounty amount below minimum")
	ErrBountyAlreadyAwarded  = errors.Register(ModuleName, 1756, "bounty has already been awarded")
	ErrMaxBountyWinners      = errors.Register(ModuleName, 1757, "maximum bounty winners reached")
	ErrInvalidBountyDuration = errors.Register(ModuleName, 1758, "bounty duration exceeds maximum")
	ErrBountyInModeration    = errors.Register(ModuleName, 1759, "bounty is pending moderation resolution")
	ErrNotReplyInThread      = errors.Register(ModuleName, 1760, "post is not a reply in the bounty thread")
	ErrBountyFullyAwarded    = errors.Register(ModuleName, 1761, "bounty has been fully awarded")

	// Tag budget errors (1800-1849) moved to x/rep.

	// Flag errors (1850-1899)
	ErrAlreadyFlagged     = errors.Register(ModuleName, 1850, "already flagged this post")
	ErrFlagNotFound       = errors.Register(ModuleName, 1851, "flag record not found")
	ErrNotInReviewQueue   = errors.Register(ModuleName, 1852, "post not in review queue")
	ErrFlagExpired        = errors.Register(ModuleName, 1853, "flags have expired")
	ErrMaxFlaggersReached = errors.Register(ModuleName, 1854, "maximum flaggers reached for this post")

	// Thread metadata errors (1900-1949)
	ErrNoAcceptedReply        = errors.Register(ModuleName, 1900, "no accepted reply for this thread")
	ErrAlreadyAccepted        = errors.Register(ModuleName, 1901, "thread already has an accepted reply")
	ErrNoProposedReply        = errors.Register(ModuleName, 1902, "no proposed reply for this thread")
	ErrProposalAlreadyPending = errors.Register(ModuleName, 1903, "accept proposal already pending")
	ErrMaxPinnedReplies       = errors.Register(ModuleName, 1904, "maximum pinned replies reached")
	ErrAlreadyPinned          = errors.Register(ModuleName, 1905, "post is already pinned")
	ErrNotPinned              = errors.Register(ModuleName, 1906, "post is not pinned")
	ErrCannotPinOwnReply      = errors.Register(ModuleName, 1907, "cannot pin own reply")
	ErrPinDisputed            = errors.Register(ModuleName, 1908, "pin is being disputed")
	ErrCannotDisputeGovPin    = errors.Register(ModuleName, 1909, "cannot dispute governance pins")
	ErrAlreadyDisputed        = errors.Register(ModuleName, 1910, "pin is already disputed")

	// Follow errors (1950-1999)
	ErrAlreadyFollowing  = errors.Register(ModuleName, 1950, "already following this thread")
	ErrNotFollowing      = errors.Register(ModuleName, 1951, "not following this thread")
	ErrCannotVoteOwnPost = errors.Register(ModuleName, 1952, "cannot vote on your own post")
	ErrAlreadyVoted      = errors.Register(ModuleName, 1953, "already voted on this post")

	// Report errors (2000-2049)
	ErrReportNotFound          = errors.Register(ModuleName, 2000, "report not found")
	ErrReportAlreadyExists     = errors.Register(ModuleName, 2001, "report already exists")
	ErrReportExpired           = errors.Register(ModuleName, 2002, "report has expired")
	ErrInsufficientEvidence    = errors.Register(ModuleName, 2003, "insufficient evidence posts")
	ErrMaxReportersReached     = errors.Register(ModuleName, 2004, "maximum reporters reached")
	ErrAlreadyCosigned         = errors.Register(ModuleName, 2005, "already co-signed this report")
	ErrDefenseAlreadySubmitted = errors.Register(ModuleName, 2006, "defense already submitted")
	ErrDefenseWaitPeriod       = errors.Register(ModuleName, 2007, "must wait after defense before resolution")
	ErrMinReportDuration       = errors.Register(ModuleName, 2008, "minimum report duration not yet passed")
	ErrReportNotPending        = errors.Register(ModuleName, 2009, "report is not pending")
	ErrCannotReportSelf        = errors.Register(ModuleName, 2010, "cannot report yourself")

	// Gov action appeal errors (2050-2099)
	ErrGovAppealNotFound     = errors.Register(ModuleName, 2050, "governance action appeal not found")
	ErrGovAppealNotPending   = errors.Register(ModuleName, 2051, "governance action appeal is not pending")
	ErrCannotAppealAction    = errors.Register(ModuleName, 2052, "this action type cannot be appealed")
	ErrPauseNotLongEnough    = errors.Register(ModuleName, 2053, "pause duration not long enough to appeal")
	ErrGovAppealAlreadyFiled = errors.Register(ModuleName, 2054, "governance action appeal already filed")

	// Emergency pause errors (2100-2149)
	ErrForumPaused       = errors.Register(ModuleName, 2100, "forum is paused")
	ErrModerationPaused  = errors.Register(ModuleName, 2101, "moderation is paused")
	ErrNewPostsPaused    = errors.Register(ModuleName, 2102, "new posts are paused")
	ErrAppealsPaused     = errors.Register(ModuleName, 2103, "appeals are paused")
	ErrBountiesDisabled  = errors.Register(ModuleName, 2104, "bounties are disabled")
	ErrReactionsDisabled = errors.Register(ModuleName, 2105, "reactions are disabled")
	ErrEditingDisabled   = errors.Register(ModuleName, 2106, "post editing is disabled")

	// Edit errors (2150-2199)
	ErrEditWindowExpired     = errors.Register(ModuleName, 2150, "edit window has expired")
	ErrCannotEditHiddenPost  = errors.Register(ModuleName, 2151, "cannot edit hidden post")
	ErrCannotEditDeletedPost = errors.Register(ModuleName, 2152, "cannot edit deleted post")

	// Payment errors (2200-2249)
	ErrInsufficientFunds = errors.Register(ModuleName, 2200, "insufficient funds")
	ErrInvalidAmount     = errors.Register(ModuleName, 2201, "invalid amount")
	ErrInvalidDenom      = errors.Register(ModuleName, 2202, "invalid denomination")

	// Member errors (2250-2299)
	ErrNotMember        = errors.Register(ModuleName, 2250, "not a member")
	ErrMembershipTooNew = errors.Register(ModuleName, 2251, "membership too recent for this operation")

	// Conviction propagation errors (2400-2499)
	ErrInvalidInitiativeRef = errors.Register(ModuleName, 2400, "invalid initiative reference")
)
