package types

import (
	"testing"

	"cosmossdk.io/errors"
)

// TestErrorCodesUnique verifies that every registered forum error has a
// distinct code. Duplicate codes would break error identification at the
// SDK level.
func TestErrorCodesUnique(t *testing.T) {
	errs := []*errors.Error{
		ErrInvalidSigner,
		ErrUnauthorized,
		ErrInvalidParam,
		ErrContentTooLarge,
		ErrInvalidTag,
		ErrTagLimitExceeded,
		ErrTotalTagsExceeded,
		ErrTagNotFound,
		ErrTagAlreadyExists,
		ErrReservedTag,
		ErrTagExpired,
		ErrInvalidContent,
		ErrEmptyContent,
		ErrInvalidReasonCode,
		ErrReasonTextRequired,
		ErrMaxTagLength,
		ErrPostNotFound,
		ErrNotPostAuthor,
		ErrPostAlreadyHidden,
		ErrPostNotHidden,
		ErrPostDeleted,
		ErrPostArchived,
		ErrNotRootPost,
		ErrIsRootPost,
		ErrPostAlreadyPinned,
		ErrPostNotPinned,
		ErrMaxPinnedPosts,
		ErrCannotDeleteHiddenPost,
		ErrMaxReplyDepthExceeded,
		ErrParentPostNotFound,
		ErrInvalidPostStatus,
		ErrThreadLocked,
		ErrThreadNotLocked,
		ErrThreadAlreadyLocked,
		ErrNotThreadAuthor,
		ErrLockReasonRequired,
		ErrMoveReasonRequired,
		ErrCannotMoveReservedTag,
		ErrCategoryNotFound,
		ErrCategoryAlreadyExists,
		ErrMembersOnlyWrite,
		ErrAdminOnlyWrite,
		ErrInvalidCategoryId,
		ErrRateLimitExceeded,
		ErrReactionLimitExceeded,
		ErrFlagLimitExceeded,
		ErrFollowLimitExceeded,
		ErrSalvationLimitExceeded,
		ErrDownvoteLimitExceeded,
		ErrSentinelCooldown,
		ErrInsufficientBond,
		ErrInsufficientBacking,
		ErrInsufficientReputation,
		ErrSentinelDemoted,
		ErrNotSentinel,
		ErrAlreadySentinel,
		ErrHideLimitExceeded,
		ErrLockLimitExceeded,
		ErrMoveLimitExceeded,
		ErrInsufficientLockBond,
		ErrInsufficientLockBacking,
		ErrSentinelNotFound,
		ErrCannotUnbondPendingHides,
		ErrDemotionCooldown,
		ErrBondAmountTooSmall,
		ErrNotGovAuthority,
		ErrNotAuthorized,
		ErrPostStatus,
		ErrAppealCooldown,
		ErrAppealAlreadyFiled,
		ErrAppealNotFound,
		ErrAppealPending,
		ErrAppealExpired,
		ErrGovLockNotAppealable,
		ErrLockAppealAlreadyFiled,
		ErrLockAppealExpired,
		ErrMoveAppealAlreadyFiled,
		ErrMoveAppealExpired,
		ErrPinDisputeAlreadyFiled,
		ErrNotSentinelPin,
		ErrThreadNotInactive,
		ErrArchiveCooldown,
		ErrUnarchiveCooldown,
		ErrArchiveCycleLimit,
		ErrArchivedThreadNotFound,
		ErrCannotArchiveThreadWithPendingAppeal,
		ErrBountyNotFound,
		ErrBountyNotActive,
		ErrBountyExpired,
		ErrBountyAlreadyExists,
		ErrNotBountyCreator,
		ErrBountyAmountTooSmall,
		ErrBountyAlreadyAwarded,
		ErrMaxBountyWinners,
		ErrInvalidBountyDuration,
		ErrBountyInModeration,
		ErrNotReplyInThread,
		ErrBountyFullyAwarded,
		ErrAlreadyFlagged,
		ErrFlagNotFound,
		ErrNotInReviewQueue,
		ErrFlagExpired,
		ErrMaxFlaggersReached,
		ErrNoAcceptedReply,
		ErrAlreadyAccepted,
		ErrNoProposedReply,
		ErrProposalAlreadyPending,
		ErrMaxPinnedReplies,
		ErrAlreadyPinned,
		ErrNotPinned,
		ErrCannotPinOwnReply,
		ErrPinDisputed,
		ErrCannotDisputeGovPin,
		ErrAlreadyDisputed,
		ErrAlreadyFollowing,
		ErrNotFollowing,
		ErrCannotVoteOwnPost,
		ErrAlreadyVoted,
		ErrReportNotFound,
		ErrReportAlreadyExists,
		ErrReportExpired,
		ErrInsufficientEvidence,
		ErrMaxReportersReached,
		ErrAlreadyCosigned,
		ErrDefenseAlreadySubmitted,
		ErrDefenseWaitPeriod,
		ErrMinReportDuration,
		ErrReportNotPending,
		ErrCannotReportSelf,
		ErrGovAppealNotFound,
		ErrGovAppealNotPending,
		ErrCannotAppealAction,
		ErrPauseNotLongEnough,
		ErrGovAppealAlreadyFiled,
		ErrForumPaused,
		ErrModerationPaused,
		ErrNewPostsPaused,
		ErrAppealsPaused,
		ErrBountiesDisabled,
		ErrReactionsDisabled,
		ErrEditingDisabled,
		ErrEditWindowExpired,
		ErrCannotEditHiddenPost,
		ErrCannotEditDeletedPost,
		ErrInsufficientFunds,
		ErrInvalidAmount,
		ErrInvalidDenom,
		ErrNotMember,
		ErrMembershipTooNew,
		ErrInvalidInitiativeRef,
	}

	seen := make(map[uint32]*errors.Error, len(errs))
	for _, e := range errs {
		if e == nil {
			t.Fatal("nil error registered")
		}
		if e.Codespace() != ModuleName {
			t.Errorf("error %v has codespace %q, want %q", e, e.Codespace(), ModuleName)
		}
		if existing, ok := seen[e.ABCICode()]; ok {
			t.Errorf("duplicate code %d: %v vs %v", e.ABCICode(), existing, e)
		}
		seen[e.ABCICode()] = e
	}
}
