// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/forum/v1/user_rate_limit.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UserRateLimit defines the UserRateLimit message. Counters are split by
// action class — the post counter (fields 2-5) bounds CreatePost, the
// make-permanent counter (fields 6-8) bounds MakePostPermanent. They are
// kept on the same record to avoid an extra collection lookup per call.
type UserRateLimit struct {
	UserAddress        string `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	CurrentEpochCount  uint64 `protobuf:"varint,2,opt,name=current_epoch_count,json=currentEpochCount,proto3" json:"current_epoch_count,omitempty"`
	PreviousEpochCount uint64 `protobuf:"varint,3,opt,name=previous_epoch_count,json=previousEpochCount,proto3" json:"previous_epoch_count,omitempty"`
	CurrentEpochStart  int64  `protobuf:"varint,4,opt,name=current_epoch_start,json=currentEpochStart,proto3" json:"current_epoch_start,omitempty"`
	LastPostTime       int64  `protobuf:"varint,5,opt,name=last_post_time,json=lastPostTime,proto3" json:"last_post_time,omitempty"`
	// MakePostPermanent sliding-window counters, mirrored from the post counter.
	MakePermanentCurrentEpochCount  uint64 `protobuf:"varint,6,opt,name=make_permanent_current_epoch_count,json=makePermanentCurrentEpochCount,proto3" json:"make_permanent_current_epoch_count,omitempty"`
	MakePermanentPreviousEpochCount uint64 `protobuf:"varint,7,opt,name=make_permanent_previous_epoch_count,json=makePermanentPreviousEpochCount,proto3" json:"make_permanent_previous_epoch_count,omitempty"`
	MakePermanentCurrentEpochStart  int64  `protobuf:"varint,8,opt,name=make_permanent_current_epoch_start,json=makePermanentCurrentEpochStart,proto3" json:"make_permanent_current_epoch_start,omitempty"`
}

func (m *UserRateLimit) Reset()         { *m = UserRateLimit{} }
func (m *UserRateLimit) String() string { return proto.CompactTextString(m) }
func (*UserRateLimit) ProtoMessage()    {}
func (*UserRateLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc7cc4997aeedc88, []int{0}
}
func (m *UserRateLimit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserRateLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserRateLimit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserRateLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRateLimit.Merge(m, src)
}
func (m *UserRateLimit) XXX_Size() int {
	return m.Size()
}
func (m *UserRateLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRateLimit.DiscardUnknown(m)
}

var xxx_messageInfo_UserRateLimit proto.InternalMessageInfo

func (m *UserRateLimit) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *UserRateLimit) GetCurrentEpochCount() uint64 {
	if m != nil {
		return m.CurrentEpochCount
	}
	return 0
}

func (m *UserRateLimit) GetPreviousEpochCount() uint64 {
	if m != nil {
		return m.PreviousEpochCount
	}
	return 0
}

func (m *UserRateLimit) GetCurrentEpochStart() int64 {
	if m != nil {
		return m.CurrentEpochStart
	}
	return 0
}

func (m *UserRateLimit) GetLastPostTime() int64 {
	if m != nil {
		return m.LastPostTime
	}
	return 0
}

func (m *UserRateLimit) GetMakePermanentCurrentEpochCount() uint64 {
	if m != nil {
		return m.MakePermanentCurrentEpochCount
	}
	return 0
}

func (m *UserRateLimit) GetMakePermanentPreviousEpochCount() uint64 {
	if m != nil {
		return m.MakePermanentPreviousEpochCount
	}
	return 0
}

func (m *UserRateLimit) GetMakePermanentCurrentEpochStart() int64 {
	if m != nil {
		return m.MakePermanentCurrentEpochStart
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRateLimit)(nil), "sparkdream.forum.v1.UserRateLimit")
}

func init() {
	proto.RegisterFile("sparkdream/forum/v1/user_rate_limit.proto", fileDescriptor_fc7cc4997aeedc88)
}

var fileDescriptor_fc7cc4997aeedc88 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbd, 0x4e, 0x42, 0x31,
	0x14, 0xc7, 0xa9, 0x20, 0x6a, 0x45, 0x13, 0x8b, 0xc3, 0x9d, 0x2a, 0xa2, 0x03, 0x2e, 0x17, 0xd1,
	0x27, 0x50, 0xe2, 0x62, 0x18, 0x08, 0xea, 0xe2, 0xd2, 0x54, 0x38, 0xc6, 0x1b, 0x28, 0x6d, 0xda,
	0x73, 0x89, 0xbe, 0x85, 0x8f, 0xe5, 0xc8, 0xe8, 0x68, 0xe0, 0x45, 0x4c, 0x0b, 0x44, 0xf0, 0x62,
	0x5c, 0xcf, 0xff, 0xa3, 0xe7, 0xd7, 0x1c, 0x7a, 0xe6, 0x8c, 0xb4, 0xfd, 0x9e, 0x05, 0xa9, 0xea,
	0xcf, 0xda, 0xa6, 0xaa, 0x3e, 0x6a, 0xd4, 0x53, 0x07, 0x56, 0x58, 0x89, 0x20, 0x06, 0x89, 0x4a,
	0x30, 0x36, 0x56, 0xa3, 0x66, 0xe5, 0x1f, 0x6b, 0x1c, 0xac, 0xf1, 0xa8, 0x51, 0x1d, 0xe7, 0xe9,
	0xde, 0x83, 0x03, 0xdb, 0x91, 0x08, 0x2d, 0x6f, 0x66, 0xc7, 0xb4, 0x14, 0xf2, 0xb2, 0xd7, 0xb3,
	0xe0, 0x5c, 0x44, 0x2a, 0xa4, 0xb6, 0xd3, 0xd9, 0xf5, 0xb3, 0xab, 0xd9, 0x88, 0xc5, 0xb4, 0xdc,
	0x4d, 0xad, 0x85, 0x21, 0x0a, 0x30, 0xba, 0xfb, 0x22, 0xba, 0x3a, 0x1d, 0x62, 0xb4, 0x51, 0x21,
	0xb5, 0x42, 0xe7, 0x60, 0x2e, 0xdd, 0x78, 0xa5, 0xe9, 0x05, 0x76, 0x4e, 0x0f, 0x8d, 0x85, 0x51,
	0xa2, 0x53, 0xb7, 0x12, 0xc8, 0x87, 0x00, 0x5b, 0x68, 0x4b, 0x89, 0xcc, 0x0b, 0x0e, 0xa5, 0xc5,
	0xa8, 0x50, 0x21, 0xb5, 0xfc, 0xea, 0x0b, 0x77, 0x5e, 0x60, 0xa7, 0x74, 0x7f, 0x20, 0x1d, 0x0a,
	0xa3, 0x1d, 0x0a, 0x4c, 0x14, 0x44, 0x9b, 0xc1, 0x5a, 0xf2, 0xd3, 0xb6, 0x76, 0x78, 0x9f, 0x28,
	0x60, 0xb7, 0xb4, 0xaa, 0x64, 0x1f, 0x84, 0x01, 0xab, 0xe4, 0xd0, 0x97, 0xaf, 0xc3, 0x28, 0x86,
	0xad, 0xb8, 0x77, 0xb6, 0x17, 0xc6, 0x66, 0x86, 0xa9, 0x45, 0x4f, 0x7e, 0x75, 0xad, 0x45, 0xdc,
	0x0a, 0x65, 0x47, 0x2b, 0x65, 0xed, 0x2c, 0xef, 0x7f, 0x9b, 0xcd, 0xf0, 0xb7, 0x03, 0xd3, 0xdf,
	0x9b, 0x85, 0xbf, 0xb8, 0xbe, 0xf8, 0x98, 0x70, 0x32, 0x9e, 0x70, 0xf2, 0x35, 0xe1, 0xe4, 0x7d,
	0xca, 0x73, 0xe3, 0x29, 0xcf, 0x7d, 0x4e, 0x79, 0xee, 0x31, 0x5a, 0x3a, 0x96, 0xd7, 0xf9, 0xb9,
	0xe0, 0x9b, 0x01, 0xf7, 0x54, 0x0c, 0x27, 0x72, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xda, 0x8c,
	0x98, 0xe2, 0x4f, 0x02, 0x00, 0x00,
}

func (m *UserRateLimit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserRateLimit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserRateLimit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MakePermanentCurrentEpochStart != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.MakePermanentCurrentEpochStart))
		i--
		dAtA[i] = 0x40
	}
	if m.MakePermanentPreviousEpochCount != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.MakePermanentPreviousEpochCount))
		i--
		dAtA[i] = 0x38
	}
	if m.MakePermanentCurrentEpochCount != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.MakePermanentCurrentEpochCount))
		i--
		dAtA[i] = 0x30
	}
	if m.LastPostTime != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.LastPostTime))
		i--
		dAtA[i] = 0x28
	}
	if m.CurrentEpochStart != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.CurrentEpochStart))
		i--
		dAtA[i] = 0x20
	}
	if m.PreviousEpochCount != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.PreviousEpochCount))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentEpochCount != 0 {
		i = encodeVarintUserRateLimit(dAtA, i, uint64(m.CurrentEpochCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.UserAddress) > 0 {
		i -= len(m.UserAddress)
		copy(dAtA[i:], m.UserAddress)
		i = encodeVarintUserRateLimit(dAtA, i, uint64(len(m.UserAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUserRateLimit(dAtA []byte, offset int, v uint64) int {
	offset -= sovUserRateLimit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserRateLimit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAddress)
	if l > 0 {
		n += 1 + l + sovUserRateLimit(uint64(l))
	}
	if m.CurrentEpochCount != 0 {
		n += 1 + sovUserRateLimit(uint64(m.CurrentEpochCount))
	}
	if m.PreviousEpochCount != 0 {
		n += 1 + sovUserRateLimit(uint64(m.PreviousEpochCount))
	}
	if m.CurrentEpochStart != 0 {
		n += 1 + sovUserRateLimit(uint64(m.CurrentEpochStart))
	}
	if m.LastPostTime != 0 {
		n += 1 + sovUserRateLimit(uint64(m.LastPostTime))
	}
	if m.MakePermanentCurrentEpochCount != 0 {
		n += 1 + sovUserRateLimit(uint64(m.MakePermanentCurrentEpochCount))
	}
	if m.MakePermanentPreviousEpochCount != 0 {
		n += 1 + sovUserRateLimit(uint64(m.MakePermanentPreviousEpochCount))
	}
	if m.MakePermanentCurrentEpochStart != 0 {
		n += 1 + sovUserRateLimit(uint64(m.MakePermanentCurrentEpochStart))
	}
	return n
}

func sovUserRateLimit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUserRateLimit(x uint64) (n int) {
	return sovUserRateLimit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserRateLimit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUserRateLimit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserRateLimit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserRateLimit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUserRateLimit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUserRateLimit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochCount", wireType)
			}
			m.CurrentEpochCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousEpochCount", wireType)
			}
			m.PreviousEpochCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousEpochCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochStart", wireType)
			}
			m.CurrentEpochStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPostTime", wireType)
			}
			m.LastPostTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPostTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakePermanentCurrentEpochCount", wireType)
			}
			m.MakePermanentCurrentEpochCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakePermanentCurrentEpochCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakePermanentPreviousEpochCount", wireType)
			}
			m.MakePermanentPreviousEpochCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakePermanentPreviousEpochCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakePermanentCurrentEpochStart", wireType)
			}
			m.MakePermanentCurrentEpochStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakePermanentCurrentEpochStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUserRateLimit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUserRateLimit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUserRateLimit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUserRateLimit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserRateLimit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUserRateLimit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUserRateLimit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUserRateLimit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUserRateLimit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUserRateLimit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUserRateLimit = fmt.Errorf("proto: unexpected end of group")
)
