version: 1
validation: sovereign
accounts: 
- name: alice
  coins: [20000000000000uspark, 20000000000000udream]
- name: bob
  coins: [10000000000000uspark, 10000000000000udream]
- name: carol
  coins: [5000000000000uspark, 5000000000000udream]
faucet:
  name: bob
  coins: [1000uspark, 1000udream]
genesis:
  app_state:
    bank:
      denom_metadata:
      - base: uspark
        denom_units:
        - denom: uspark
          exponent: 0
        - denom: spark
          exponent: 6
        description: Native token of Spark Dream A T E L I E R.
        display: spark
        name: spark
        symbol: spark
      - base: udream
        denom_units:
        - denom: udream
          exponent: 0
        - denom: dream
          exponent: 6
        description: Native token of Spark Dream A T E L I E R.
        display: dream
        name: dream
        symbol: dream
    crisis:
      constant_fee:
        denom: uspark
    distribution:
      params:
        community_tax: "0.15"
    gov:
      params:
        max_deposit_period: "30s"
        min_deposit:
          - amount: "50000000"
            denom: "uspark"
        voting_period: "60s"
        expedited_min_deposit:
          - amount: "100000000"
            denom: "uspark"
        expedited_voting_period: "40s"
    mint:
      params:
        mint_denom: uspark
    split:
      params:
        commons_council_address: "sprkdrm1afyuna8gqe55t7jztxcg0aleg0k5txep72pfan"
    staking:
      params:
        bond_denom: uspark
validators:
- name: alice
  bonded: 15000000000000uspark
- name: bob
  bonded: 5000000000000uspark
