// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/service/v1/controller_transfer_case.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ControllerTransferCase records an open jury case to transfer an
// operator's controller (see x-service-spec.md §5.4). Created by
// MsgOpenControllerTransferCase, deleted by MsgFinalizeControllerTransfer.
//
// At most one open case per (operator_address, service_type), enforced
// via OpenControllerTransferByOperator secondary index.
type ControllerTransferCase struct {
	// jury_case_id is the x/rep case id (the primary key for this store).
	JuryCaseId uint64 `protobuf:"varint,1,opt,name=jury_case_id,json=juryCaseId,proto3" json:"jury_case_id,omitempty"`
	// operator_address is the operator whose controller is being transferred.
	OperatorAddress string `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	// service_type identifies which operator record.
	ServiceType string `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	// opener is the address that filed MsgOpenControllerTransferCase
	// (operator themselves OR an ESTABLISHED+ member).
	Opener string `protobuf:"bytes,4,opt,name=opener,proto3" json:"opener,omitempty"`
	// proposed_new_controller is the x/commons Group address the case
	// proposes to transfer to. Re-checked at apply time (§5.4).
	ProposedNewController string `protobuf:"bytes,5,opt,name=proposed_new_controller,json=proposedNewController,proto3" json:"proposed_new_controller,omitempty"`
	// deposit is the SPARK the opener escrowed, in bond-denom micro-units;
	// refunded on ACCEPT, forfeited on REJECT. Wrapped into sdk.Coin with
	// the chain's bond denom at the point of use.
	Deposit cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=deposit,proto3,customtype=cosmossdk.io/math.Int" json:"deposit"`
	// opened_at is the height the case was opened.
	OpenedAt int64 `protobuf:"varint,7,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
}

func (m *ControllerTransferCase) Reset()         { *m = ControllerTransferCase{} }
func (m *ControllerTransferCase) String() string { return proto.CompactTextString(m) }
func (*ControllerTransferCase) ProtoMessage()    {}
func (*ControllerTransferCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb5559818dbd9e1f, []int{0}
}
func (m *ControllerTransferCase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ControllerTransferCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ControllerTransferCase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ControllerTransferCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerTransferCase.Merge(m, src)
}
func (m *ControllerTransferCase) XXX_Size() int {
	return m.Size()
}
func (m *ControllerTransferCase) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerTransferCase.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerTransferCase proto.InternalMessageInfo

func (m *ControllerTransferCase) GetJuryCaseId() uint64 {
	if m != nil {
		return m.JuryCaseId
	}
	return 0
}

func (m *ControllerTransferCase) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *ControllerTransferCase) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ControllerTransferCase) GetOpener() string {
	if m != nil {
		return m.Opener
	}
	return ""
}

func (m *ControllerTransferCase) GetProposedNewController() string {
	if m != nil {
		return m.ProposedNewController
	}
	return ""
}

func (m *ControllerTransferCase) GetOpenedAt() int64 {
	if m != nil {
		return m.OpenedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*ControllerTransferCase)(nil), "sparkdream.service.v1.ControllerTransferCase")
}

func init() {
	proto.RegisterFile("sparkdream/service/v1/controller_transfer_case.proto", fileDescriptor_fb5559818dbd9e1f)
}

var fileDescriptor_fb5559818dbd9e1f = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x31, 0x6f, 0x13, 0x31,
	0x14, 0xc7, 0x63, 0x52, 0x52, 0x6a, 0x2a, 0x01, 0x56, 0x03, 0x26, 0x48, 0x97, 0x83, 0x29, 0xa2,
	0xea, 0x1d, 0x15, 0x99, 0xd8, 0xda, 0x88, 0x21, 0x0b, 0x42, 0x47, 0x27, 0x16, 0xcb, 0x9c, 0x1f,
	0xe1, 0x68, 0xcf, 0xcf, 0xb2, 0x4d, 0x4a, 0xbe, 0x02, 0x13, 0x1f, 0x81, 0x8f, 0xc0, 0xd0, 0x0f,
	0xc0, 0xd8, 0xb1, 0xea, 0x84, 0x18, 0x2a, 0x94, 0x0c, 0xf0, 0x31, 0xd0, 0xdd, 0x39, 0x0d, 0x43,
	0xa5, 0x2e, 0xa7, 0xf3, 0xff, 0xf9, 0xff, 0x7b, 0xcf, 0xef, 0x3d, 0x3a, 0x74, 0x46, 0xda, 0x43,
	0x65, 0x41, 0x96, 0xa9, 0x03, 0x3b, 0x2d, 0x72, 0x48, 0xa7, 0xbb, 0x69, 0x8e, 0xda, 0x5b, 0x3c,
	0x3a, 0x02, 0x2b, 0xbc, 0x95, 0xda, 0xbd, 0x07, 0x2b, 0x72, 0xe9, 0x20, 0x31, 0x16, 0x3d, 0xb2,
	0xee, 0xca, 0x95, 0x04, 0x57, 0x32, 0xdd, 0xed, 0xdd, 0x93, 0x65, 0xa1, 0x31, 0xad, 0xbf, 0xcd,
	0xcd, 0xde, 0xc3, 0x1c, 0x5d, 0x89, 0x4e, 0xd4, 0xa7, 0xb4, 0x39, 0x84, 0xd0, 0xd6, 0x04, 0x27,
	0xd8, 0xe8, 0xd5, 0x5f, 0xa3, 0x3e, 0xf9, 0xd1, 0xa6, 0xf7, 0x47, 0x97, 0xd9, 0x0f, 0x42, 0xf2,
	0x91, 0x74, 0xc0, 0x62, 0xba, 0xf9, 0xf1, 0x93, 0x9d, 0xd5, 0x85, 0x88, 0x42, 0x71, 0x12, 0x93,
	0xc1, 0x5a, 0x46, 0x2b, 0xad, 0x8a, 0x8f, 0x15, 0x1b, 0xd1, 0xbb, 0x68, 0xc0, 0x4a, 0x8f, 0x56,
	0x48, 0xa5, 0x2c, 0x38, 0xc7, 0x6f, 0xc4, 0x64, 0xb0, 0xb1, 0xcf, 0xcf, 0x4f, 0x76, 0xb6, 0x42,
	0xfa, 0xbd, 0x26, 0xf2, 0xc6, 0xdb, 0x42, 0x4f, 0xb2, 0x3b, 0x4b, 0x47, 0x90, 0xd9, 0x63, 0xba,
	0x19, 0xde, 0x24, 0xfc, 0xcc, 0x00, 0x6f, 0x57, 0x80, 0xec, 0x76, 0xd0, 0x0e, 0x66, 0x06, 0xd8,
	0x33, 0xda, 0x41, 0x03, 0x1a, 0x2c, 0x5f, 0xbb, 0x86, 0x1e, 0xee, 0xb1, 0xd7, 0xf4, 0x81, 0xb1,
	0x68, 0xd0, 0x81, 0x12, 0x1a, 0x8e, 0xc5, 0xaa, 0xc1, 0xfc, 0xe6, 0x35, 0x88, 0xee, 0xd2, 0xf8,
	0x0a, 0x8e, 0x57, 0x9d, 0x61, 0x2f, 0xe9, 0xba, 0x02, 0x83, 0xae, 0xf0, 0xbc, 0x53, 0x13, 0xb6,
	0x4f, 0x2f, 0xfa, 0xad, 0x5f, 0x17, 0xfd, 0x6e, 0x43, 0x71, 0xea, 0x30, 0x29, 0x30, 0x2d, 0xa5,
	0xff, 0x90, 0x8c, 0xb5, 0x3f, 0x3f, 0xd9, 0xa1, 0x01, 0x3f, 0xd6, 0x3e, 0x5b, 0x7a, 0xd9, 0x23,
	0xba, 0x51, 0x97, 0xa8, 0x84, 0xf4, 0x7c, 0x3d, 0x26, 0x83, 0x76, 0x76, 0xab, 0x11, 0xf6, 0xfc,
	0x8b, 0xe1, 0xdf, 0x6f, 0x7d, 0xf2, 0xe5, 0xcf, 0xf7, 0xa7, 0xdb, 0xff, 0xad, 0xc9, 0xe7, 0xcb,
	0x45, 0xb9, 0x7a, 0x4e, 0xfb, 0xc3, 0xd3, 0x79, 0x44, 0xce, 0xe6, 0x11, 0xf9, 0x3d, 0x8f, 0xc8,
	0xd7, 0x45, 0xd4, 0x3a, 0x5b, 0x44, 0xad, 0x9f, 0x8b, 0xa8, 0xf5, 0xb6, 0x77, 0x25, 0xa6, 0xea,
	0xb2, 0x7b, 0xd7, 0xa9, 0xe7, 0xff, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x57, 0x7d,
	0x95, 0x92, 0x02, 0x00, 0x00,
}

func (this *ControllerTransferCase) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ControllerTransferCase)
	if !ok {
		that2, ok := that.(ControllerTransferCase)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.JuryCaseId != that1.JuryCaseId {
		return false
	}
	if this.OperatorAddress != that1.OperatorAddress {
		return false
	}
	if this.ServiceType != that1.ServiceType {
		return false
	}
	if this.Opener != that1.Opener {
		return false
	}
	if this.ProposedNewController != that1.ProposedNewController {
		return false
	}
	if !this.Deposit.Equal(that1.Deposit) {
		return false
	}
	if this.OpenedAt != that1.OpenedAt {
		return false
	}
	return true
}
func (m *ControllerTransferCase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ControllerTransferCase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ControllerTransferCase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OpenedAt != 0 {
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(m.OpenedAt))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.Deposit.Size()
		i -= size
		if _, err := m.Deposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ProposedNewController) > 0 {
		i -= len(m.ProposedNewController)
		copy(dAtA[i:], m.ProposedNewController)
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(len(m.ProposedNewController)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Opener) > 0 {
		i -= len(m.Opener)
		copy(dAtA[i:], m.Opener)
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(len(m.Opener)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ServiceType) > 0 {
		i -= len(m.ServiceType)
		copy(dAtA[i:], m.ServiceType)
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(len(m.ServiceType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.JuryCaseId != 0 {
		i = encodeVarintControllerTransferCase(dAtA, i, uint64(m.JuryCaseId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintControllerTransferCase(dAtA []byte, offset int, v uint64) int {
	offset -= sovControllerTransferCase(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ControllerTransferCase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.JuryCaseId != 0 {
		n += 1 + sovControllerTransferCase(uint64(m.JuryCaseId))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovControllerTransferCase(uint64(l))
	}
	l = len(m.ServiceType)
	if l > 0 {
		n += 1 + l + sovControllerTransferCase(uint64(l))
	}
	l = len(m.Opener)
	if l > 0 {
		n += 1 + l + sovControllerTransferCase(uint64(l))
	}
	l = len(m.ProposedNewController)
	if l > 0 {
		n += 1 + l + sovControllerTransferCase(uint64(l))
	}
	l = m.Deposit.Size()
	n += 1 + l + sovControllerTransferCase(uint64(l))
	if m.OpenedAt != 0 {
		n += 1 + sovControllerTransferCase(uint64(m.OpenedAt))
	}
	return n
}

func sovControllerTransferCase(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozControllerTransferCase(x uint64) (n int) {
	return sovControllerTransferCase(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ControllerTransferCase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowControllerTransferCase
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ControllerTransferCase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ControllerTransferCase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JuryCaseId", wireType)
			}
			m.JuryCaseId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JuryCaseId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opener", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opener = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedNewController", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposedNewController = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedAt", wireType)
			}
			m.OpenedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipControllerTransferCase(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthControllerTransferCase
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipControllerTransferCase(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowControllerTransferCase
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowControllerTransferCase
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthControllerTransferCase
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupControllerTransferCase
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthControllerTransferCase
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthControllerTransferCase        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowControllerTransferCase          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupControllerTransferCase = fmt.Errorf("proto: unexpected end of group")
)
