// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/service/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the module-wide parameters for x/service. See
// x-service-spec.md §4.2 for full semantics and validation rules. All
// fields are x/gov-mutable via MsgUpdateParams unless hardened later
// via the x/mint immutable-parameter pattern (§4.2 high-impact
// hardening candidates).
//
// Per-service-type overrides for `default_*` fields live on
// ServiceTypeConfig (§3.2). The values here are the defaults that
// apply when a service type's override is zero.
//
// Bond-denom-valued amounts are stored as bare math.Int values; the
// keeper wraps them into sdk.Coin at the point of use via the identity
// keeper's BondDenom(ctx).
type Params struct {
	// default_unbonding_period_blocks is the default unbonding window
	// (~14 days at default block time).
	DefaultUnbondingPeriodBlocks int64 `protobuf:"varint,1,opt,name=default_unbonding_period_blocks,json=defaultUnbondingPeriodBlocks,proto3" json:"default_unbonding_period_blocks,omitempty"`
	// default_unilateral_slash_cap_bps is the default per-slash cap
	// (500 = 5%).
	DefaultUnilateralSlashCapBps uint32 `protobuf:"varint,2,opt,name=default_unilateral_slash_cap_bps,json=defaultUnilateralSlashCapBps,proto3" json:"default_unilateral_slash_cap_bps,omitempty"`
	// default_tier1_window_blocks is the default rolling-window length
	// for aggregate tier-1 cap accounting (~90 days).
	DefaultTier1WindowBlocks int64 `protobuf:"varint,3,opt,name=default_tier1_window_blocks,json=defaultTier1WindowBlocks,proto3" json:"default_tier1_window_blocks,omitempty"`
	// default_tier1_aggregate_cap_bps is the default cumulative-slash
	// cap within the window (1500 = 15%).
	DefaultTier1AggregateCapBps uint32 `protobuf:"varint,4,opt,name=default_tier1_aggregate_cap_bps,json=defaultTier1AggregateCapBps,proto3" json:"default_tier1_aggregate_cap_bps,omitempty"`
	// default_tier1_cooldown_blocks is the default minimum interval
	// between tier-1 slashes against the same operator (~7 days).
	DefaultTier1CooldownBlocks int64 `protobuf:"varint,5,opt,name=default_tier1_cooldown_blocks,json=defaultTier1CooldownBlocks,proto3" json:"default_tier1_cooldown_blocks,omitempty"`
	// default_underfunded_grace_blocks is the default time an
	// UNDERFUNDED operator has to top up before being force-unbonded
	// (~7 days).
	DefaultUnderfundedGraceBlocks int64 `protobuf:"varint,6,opt,name=default_underfunded_grace_blocks,json=defaultUnderfundedGraceBlocks,proto3" json:"default_underfunded_grace_blocks,omitempty"`
	// report_contest_window_blocks is the window an operator has to
	// contest a tier-1 slash (~24 hours). Also the tier-1 escrow
	// release delay.
	ReportContestWindowBlocks int64 `protobuf:"varint,7,opt,name=report_contest_window_blocks,json=reportContestWindowBlocks,proto3" json:"report_contest_window_blocks,omitempty"`
	// max_pending_blocks is the auto-dismiss horizon for PENDING
	// reports (~30 days).
	MaxPendingBlocks int64 `protobuf:"varint,8,opt,name=max_pending_blocks,json=maxPendingBlocks,proto3" json:"max_pending_blocks,omitempty"`
	// max_escalated_blocks is the auto-timeout horizon for ESCALATED
	// reports awaiting jury verdict (~60 days). MUST be greater than
	// max_pending_blocks.
	MaxEscalatedBlocks int64 `protobuf:"varint,9,opt,name=max_escalated_blocks,json=maxEscalatedBlocks,proto3" json:"max_escalated_blocks,omitempty"`
	// report_refile_cooldown_blocks is the per-controller cooldown for
	// re-filing a previously-dismissed allegation (~30 days). MUST be
	// ≥ max_pending_blocks.
	ReportRefileCooldownBlocks int64 `protobuf:"varint,10,opt,name=report_refile_cooldown_blocks,json=reportRefileCooldownBlocks,proto3" json:"report_refile_cooldown_blocks,omitempty"`
	// report_deposit_amount is the SPARK escrow required to file
	// MsgReportOperator, in bond-denom micro-units (default 10 SPARK =
	// 10_000_000). Wrapped into sdk.Coin with the chain's bond denom
	// at the point of use.
	ReportDepositAmount cosmossdk_io_math.Int `protobuf:"bytes,11,opt,name=report_deposit_amount,json=reportDepositAmount,proto3,customtype=cosmossdk.io/math.Int" json:"report_deposit_amount"`
	// min_reporter_trust_level gates who can file reports, as an enum
	// name (e.g. "TRUST_LEVEL_ESTABLISHED"). Empty = no gate.
	MinReporterTrustLevel string `protobuf:"bytes,12,opt,name=min_reporter_trust_level,json=minReporterTrustLevel,proto3" json:"min_reporter_trust_level,omitempty"`
	// max_reports_per_reporter_per_operator_per_window is the
	// sliding-window cap on filings by a single reporter against a
	// single (operator, service_type) (default 3).
	MaxReportsPerReporterPerOperatorPerWindow uint32 `protobuf:"varint,13,opt,name=max_reports_per_reporter_per_operator_per_window,json=maxReportsPerReporterPerOperatorPerWindow,proto3" json:"max_reports_per_reporter_per_operator_per_window,omitempty"`
	// reporter_rate_limit_window_blocks is the window over which the
	// above cap applies (~30 days).
	ReporterRateLimitWindowBlocks int64 `protobuf:"varint,14,opt,name=reporter_rate_limit_window_blocks,json=reporterRateLimitWindowBlocks,proto3" json:"reporter_rate_limit_window_blocks,omitempty"`
	// endblocker_sweep_limit is the per-queue per-block cap on records
	// processed by EndBlocker sweeps (default 100). Prevents unbounded
	// per-block work.
	EndblockerSweepLimit uint32 `protobuf:"varint,15,opt,name=endblocker_sweep_limit,json=endblockerSweepLimit,proto3" json:"endblocker_sweep_limit,omitempty"`
	// max_metadata_bytes caps Operator.metadata size (default 4096;
	// hard cap 65536).
	MaxMetadataBytes uint32 `protobuf:"varint,16,opt,name=max_metadata_bytes,json=maxMetadataBytes,proto3" json:"max_metadata_bytes,omitempty"`
	// max_reason_bytes caps Report.reason and similar free-form text
	// (default 512; hard cap 4096).
	MaxReasonBytes uint32 `protobuf:"varint,17,opt,name=max_reason_bytes,json=maxReasonBytes,proto3" json:"max_reason_bytes,omitempty"`
	// max_active_operators_per_address caps the number of live
	// operator records a single address may hold across service types
	// (default 16). Prevents reputation gaming via mass
	// micro-registration (§6.6).
	MaxActiveOperatorsPerAddress uint32 `protobuf:"varint,18,opt,name=max_active_operators_per_address,json=maxActiveOperatorsPerAddress,proto3" json:"max_active_operators_per_address,omitempty"`
	// reputation_grant_per_bond_block is the reputation accrued per
	// SPARK-block of ACTIVE bond, applied at successful unbond claim
	// and capped by the §6.6 anti-gaming rule.
	ReputationGrantPerBondBlock cosmossdk_io_math.LegacyDec `protobuf:"bytes,19,opt,name=reputation_grant_per_bond_block,json=reputationGrantPerBondBlock,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reputation_grant_per_bond_block"`
	// default_pagination_limit is the default page size when a client
	// omits pagination.limit on a paginated query (default 100).
	DefaultPaginationLimit uint32 `protobuf:"varint,20,opt,name=default_pagination_limit,json=defaultPaginationLimit,proto3" json:"default_pagination_limit,omitempty"`
	// max_pagination_limit hard-caps pagination.limit to bound query
	// gas (default 1000; absolute cap 10000).
	MaxPaginationLimit uint32 `protobuf:"varint,21,opt,name=max_pagination_limit,json=maxPaginationLimit,proto3" json:"max_pagination_limit,omitempty"`
	// max_system_reports_per_caller_per_window caps how many distinct
	// system reports a single allowlisted caller module (e.g.
	// "federation") may open via OpenSystemReport within a rolling
	// window of rate_limit_window_blocks. Idempotent re-calls (same
	// dedupe_key) don't count against the cap. Default 50 — tunable
	// from observed federation challenge volume post-launch.
	MaxSystemReportsPerCallerPerWindow uint32 `protobuf:"varint,22,opt,name=max_system_reports_per_caller_per_window,json=maxSystemReportsPerCallerPerWindow,proto3" json:"max_system_reports_per_caller_per_window,omitempty"`
	// rate_limit_window_blocks is the rolling window over which the
	// above per-caller cap applies (~1 day at default block time).
	// x/service has no native epoch concept, so this is an explicit
	// block-count param rather than reusing season/shield epochs.
	RateLimitWindowBlocks int64 `protobuf:"varint,23,opt,name=rate_limit_window_blocks,json=rateLimitWindowBlocks,proto3" json:"rate_limit_window_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cec6eb067274353, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDefaultUnbondingPeriodBlocks() int64 {
	if m != nil {
		return m.DefaultUnbondingPeriodBlocks
	}
	return 0
}

func (m *Params) GetDefaultUnilateralSlashCapBps() uint32 {
	if m != nil {
		return m.DefaultUnilateralSlashCapBps
	}
	return 0
}

func (m *Params) GetDefaultTier1WindowBlocks() int64 {
	if m != nil {
		return m.DefaultTier1WindowBlocks
	}
	return 0
}

func (m *Params) GetDefaultTier1AggregateCapBps() uint32 {
	if m != nil {
		return m.DefaultTier1AggregateCapBps
	}
	return 0
}

func (m *Params) GetDefaultTier1CooldownBlocks() int64 {
	if m != nil {
		return m.DefaultTier1CooldownBlocks
	}
	return 0
}

func (m *Params) GetDefaultUnderfundedGraceBlocks() int64 {
	if m != nil {
		return m.DefaultUnderfundedGraceBlocks
	}
	return 0
}

func (m *Params) GetReportContestWindowBlocks() int64 {
	if m != nil {
		return m.ReportContestWindowBlocks
	}
	return 0
}

func (m *Params) GetMaxPendingBlocks() int64 {
	if m != nil {
		return m.MaxPendingBlocks
	}
	return 0
}

func (m *Params) GetMaxEscalatedBlocks() int64 {
	if m != nil {
		return m.MaxEscalatedBlocks
	}
	return 0
}

func (m *Params) GetReportRefileCooldownBlocks() int64 {
	if m != nil {
		return m.ReportRefileCooldownBlocks
	}
	return 0
}

func (m *Params) GetMinReporterTrustLevel() string {
	if m != nil {
		return m.MinReporterTrustLevel
	}
	return ""
}

func (m *Params) GetMaxReportsPerReporterPerOperatorPerWindow() uint32 {
	if m != nil {
		return m.MaxReportsPerReporterPerOperatorPerWindow
	}
	return 0
}

func (m *Params) GetReporterRateLimitWindowBlocks() int64 {
	if m != nil {
		return m.ReporterRateLimitWindowBlocks
	}
	return 0
}

func (m *Params) GetEndblockerSweepLimit() uint32 {
	if m != nil {
		return m.EndblockerSweepLimit
	}
	return 0
}

func (m *Params) GetMaxMetadataBytes() uint32 {
	if m != nil {
		return m.MaxMetadataBytes
	}
	return 0
}

func (m *Params) GetMaxReasonBytes() uint32 {
	if m != nil {
		return m.MaxReasonBytes
	}
	return 0
}

func (m *Params) GetMaxActiveOperatorsPerAddress() uint32 {
	if m != nil {
		return m.MaxActiveOperatorsPerAddress
	}
	return 0
}

func (m *Params) GetDefaultPaginationLimit() uint32 {
	if m != nil {
		return m.DefaultPaginationLimit
	}
	return 0
}

func (m *Params) GetMaxPaginationLimit() uint32 {
	if m != nil {
		return m.MaxPaginationLimit
	}
	return 0
}

func (m *Params) GetMaxSystemReportsPerCallerPerWindow() uint32 {
	if m != nil {
		return m.MaxSystemReportsPerCallerPerWindow
	}
	return 0
}

func (m *Params) GetRateLimitWindowBlocks() int64 {
	if m != nil {
		return m.RateLimitWindowBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "sparkdream.service.v1.Params")
}

func init() {
	proto.RegisterFile("sparkdream/service/v1/params.proto", fileDescriptor_1cec6eb067274353)
}

var fileDescriptor_1cec6eb067274353 = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0xdf, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0x63, 0x0a, 0x81, 0x0e, 0x6d, 0x49, 0xb7, 0x71, 0xd8, 0xc6, 0x8d, 0x6d, 0x02, 0x17,
	0xe6, 0x9f, 0xdd, 0x88, 0x4a, 0x45, 0x48, 0x08, 0xd9, 0x49, 0x1b, 0x2a, 0x05, 0x61, 0x39, 0x41,
	0x48, 0xdc, 0x8c, 0x8e, 0x77, 0x4f, 0xdc, 0x51, 0x76, 0x67, 0x56, 0x33, 0x63, 0xc7, 0x79, 0x05,
	0xae, 0x78, 0x04, 0x1e, 0x81, 0x0b, 0x24, 0x5e, 0xa1, 0x97, 0x15, 0x57, 0x88, 0x8b, 0x0a, 0x25,
	0x17, 0xf0, 0x18, 0x68, 0xe6, 0xcc, 0xfa, 0x4f, 0x92, 0xde, 0x58, 0xde, 0x39, 0xbf, 0xf3, 0xed,
	0xd9, 0x6f, 0xbe, 0xdd, 0x61, 0xdb, 0xa6, 0x00, 0x7d, 0x92, 0x6a, 0x84, 0xbc, 0x63, 0x50, 0x4f,
	0x44, 0x82, 0x9d, 0xc9, 0x4e, 0xa7, 0x00, 0x0d, 0xb9, 0x69, 0x17, 0x5a, 0x59, 0x15, 0x55, 0xe7,
	0x4c, 0x3b, 0x30, 0xed, 0xc9, 0xce, 0xe6, 0x5d, 0xc8, 0x85, 0x54, 0x1d, 0xff, 0x4b, 0xe4, 0xe6,
	0xfd, 0x44, 0x99, 0x5c, 0x19, 0xee, 0xaf, 0x3a, 0x74, 0x11, 0x4a, 0xeb, 0x23, 0x35, 0x52, 0xb4,
	0xee, 0xfe, 0xd1, 0xea, 0xf6, 0x1f, 0xb7, 0xd8, 0x6a, 0xdf, 0xdf, 0x2b, 0x7a, 0xc2, 0x1a, 0x29,
	0x1e, 0xc3, 0x38, 0xb3, 0x7c, 0x2c, 0x87, 0x4a, 0xa6, 0x42, 0x8e, 0x78, 0x81, 0x5a, 0xa8, 0x94,
	0x0f, 0x33, 0x95, 0x9c, 0x98, 0xb8, 0xd2, 0xac, 0xb4, 0x6e, 0x0c, 0x1e, 0x04, 0xec, 0x87, 0x92,
	0xea, 0x7b, 0xa8, 0xe7, 0x99, 0xe8, 0x29, 0x6b, 0xce, 0x65, 0x44, 0x06, 0x16, 0x35, 0x64, 0xdc,
	0x64, 0x60, 0x9e, 0xf3, 0x04, 0x0a, 0x3e, 0x2c, 0x4c, 0xfc, 0x46, 0xb3, 0xd2, 0xba, 0xbd, 0xa0,
	0x53, 0x62, 0x87, 0x8e, 0xda, 0x85, 0xa2, 0x57, 0x98, 0xe8, 0x6b, 0x56, 0x2b, 0x75, 0xac, 0x40,
	0xbd, 0xc3, 0x4f, 0x85, 0x4c, 0xd5, 0x69, 0x39, 0xca, 0x0d, 0x3f, 0x4a, 0x1c, 0x90, 0x23, 0x47,
	0xfc, 0xe8, 0x81, 0x30, 0xc6, 0xde, 0xfc, 0x69, 0xa8, 0x1d, 0x46, 0x23, 0x8d, 0x23, 0xb0, 0x38,
	0x9b, 0xe2, 0x4d, 0x3f, 0x45, 0x6d, 0x51, 0xa2, 0x5b, 0x42, 0x61, 0x88, 0x2e, 0xdb, 0x5a, 0x56,
	0x49, 0x94, 0xca, 0x52, 0x75, 0x2a, 0xcb, 0x31, 0xde, 0xf2, 0x63, 0x6c, 0x2e, 0x6a, 0xec, 0x06,
	0x24, 0x0c, 0xb2, 0xbf, 0xe8, 0x47, 0x8a, 0xfa, 0xd8, 0xfd, 0xa6, 0x7c, 0xa4, 0x21, 0xc1, 0x52,
	0x65, 0xd5, 0xab, 0x6c, 0xcd, 0xfc, 0x98, 0x61, 0xfb, 0x8e, 0x0a, 0x42, 0xdf, 0xb0, 0x07, 0x1a,
	0x0b, 0xa5, 0x2d, 0x4f, 0x94, 0xb4, 0x68, 0xec, 0x25, 0x47, 0xde, 0xf6, 0x22, 0xf7, 0x89, 0xd9,
	0x25, 0x64, 0xc9, 0x92, 0xcf, 0x58, 0x94, 0xc3, 0x94, 0x17, 0x48, 0x5b, 0x1b, 0xda, 0xde, 0xf1,
	0x6d, 0x6b, 0x39, 0x4c, 0xfb, 0x54, 0x08, 0xf4, 0x43, 0xb6, 0xee, 0x68, 0x34, 0x09, 0xb8, 0xdd,
	0x99, 0x65, 0xe0, 0xa6, 0xe7, 0x9d, 0xd2, 0x93, 0xb2, 0x14, 0x3a, 0xba, 0x6c, 0x2b, 0x0c, 0xa8,
	0xf1, 0x58, 0x64, 0x78, 0xc5, 0x2c, 0x46, 0x66, 0x11, 0x34, 0xf0, 0xcc, 0x25, 0xb3, 0x38, 0xab,
	0x06, 0x89, 0x14, 0x0b, 0x65, 0x84, 0xe5, 0x90, 0xab, 0xb1, 0xb4, 0xf1, 0xbb, 0xcd, 0x4a, 0xeb,
	0x66, 0xef, 0xd3, 0x17, 0xaf, 0x1a, 0x2b, 0x7f, 0xbf, 0x6a, 0x54, 0x29, 0xd9, 0x26, 0x3d, 0x69,
	0x0b, 0xd5, 0xc9, 0xc1, 0x3e, 0x6f, 0x3f, 0x93, 0xf6, 0xcf, 0xdf, 0x3f, 0x67, 0x21, 0xf2, 0xcf,
	0xa4, 0x1d, 0xdc, 0x23, 0xa5, 0x3d, 0x12, 0xea, 0x7a, 0x9d, 0xe8, 0x31, 0x8b, 0x73, 0x21, 0x39,
	0x95, 0x50, 0x73, 0xab, 0xc7, 0xc6, 0xf2, 0x0c, 0x27, 0x98, 0xc5, 0xb7, 0xdc, 0x3d, 0x06, 0xd5,
	0x5c, 0xc8, 0x41, 0x28, 0x1f, 0xb9, 0xea, 0x81, 0x2b, 0x46, 0x09, 0x7b, 0xe8, 0xec, 0xa0, 0x46,
	0xe3, 0xde, 0x8b, 0xb9, 0x88, 0xbb, 0x50, 0x05, 0x6a, 0xb0, 0x8a, 0x2e, 0x68, 0x63, 0xe2, 0xdb,
	0x3e, 0x60, 0x1f, 0xe7, 0x30, 0x25, 0x41, 0xd3, 0x47, 0x5d, 0x4a, 0xf7, 0x51, 0x7f, 0x1f, 0x5a,
	0xfa, 0xa8, 0x69, 0x9f, 0xa2, 0x6f, 0xd9, 0x07, 0x33, 0x51, 0xed, 0xa2, 0x9a, 0x89, 0x5c, 0x5c,
	0xde, 0xe7, 0x3b, 0x14, 0x96, 0x12, 0x1c, 0x80, 0xc5, 0x03, 0x87, 0x2d, 0xed, 0xf5, 0x23, 0xb6,
	0x81, 0x32, 0xf5, 0x1d, 0xa8, 0xb9, 0x39, 0x45, 0x2c, 0x48, 0x2c, 0x7e, 0xcf, 0x0f, 0xb5, 0x3e,
	0xaf, 0x1e, 0xba, 0xa2, 0x57, 0x28, 0x13, 0x92, 0xa3, 0x85, 0x14, 0x2c, 0xf0, 0xe1, 0x99, 0x45,
	0x13, 0xaf, 0xf9, 0x0e, 0x97, 0x90, 0xef, 0x42, 0xa1, 0xe7, 0xd6, 0xa3, 0x16, 0x5b, 0x23, 0x4b,
	0xc0, 0x28, 0x19, 0xd8, 0xbb, 0x9e, 0xbd, 0xe3, 0x1f, 0xd9, 0x2d, 0x13, 0xf9, 0x94, 0x35, 0x1d,
	0x09, 0x89, 0x15, 0x13, 0x9c, 0x59, 0x45, 0x2e, 0x42, 0x9a, 0x6a, 0x34, 0x26, 0x8e, 0xe8, 0x9b,
	0x90, 0xc3, 0xb4, 0xeb, 0xb1, 0xd2, 0x1d, 0x67, 0x5a, 0x97, 0x98, 0x48, 0xb0, 0x86, 0xc6, 0x62,
	0x6c, 0xc1, 0x0a, 0x25, 0xdd, 0x2b, 0x24, 0xad, 0xd7, 0x70, 0xdf, 0x21, 0xb2, 0x27, 0xbe, 0xe7,
	0x83, 0xf2, 0x61, 0x08, 0x4a, 0xed, 0x6a, 0x50, 0x0e, 0x70, 0x04, 0xc9, 0xd9, 0x1e, 0x26, 0x83,
	0xda, 0x5c, 0x6b, 0xdf, 0x49, 0xf5, 0x51, 0xf7, 0x94, 0xa4, 0x34, 0x47, 0x5f, 0xb2, 0xf2, 0xdb,
	0xc2, 0x0b, 0x18, 0x09, 0x49, 0xb7, 0x24, 0x0b, 0xd7, 0xfd, 0xa8, 0x1b, 0xa1, 0xde, 0x9f, 0x95,
	0xc9, 0xc4, 0xf0, 0xe2, 0x5c, 0xe9, 0xaa, 0xfa, 0x2e, 0x67, 0xf0, 0xe5, 0x8e, 0x23, 0xd6, 0x72,
	0x1d, 0xe6, 0xcc, 0x58, 0xcc, 0x97, 0x22, 0x96, 0x40, 0x96, 0xe1, 0x52, 0xa6, 0x36, 0xbc, 0xca,
	0x76, 0x0e, 0xd3, 0x43, 0x8f, 0xcf, 0x93, 0xb5, 0xeb, 0xd9, 0x79, 0x98, 0x1e, 0xb3, 0xf8, 0xb5,
	0x19, 0x7a, 0xdf, 0x67, 0xa8, 0xaa, 0xaf, 0xcb, 0xce, 0x57, 0x1f, 0xfd, 0xf7, 0x6b, 0xa3, 0xf2,
	0xf3, 0xbf, 0xbf, 0x7d, 0x52, 0x5b, 0x38, 0x9b, 0xa6, 0xb3, 0xd3, 0x89, 0x8e, 0x8b, 0xde, 0xa3,
	0x17, 0xe7, 0xf5, 0xca, 0xcb, 0xf3, 0x7a, 0xe5, 0x9f, 0xf3, 0x7a, 0xe5, 0x97, 0x8b, 0xfa, 0xca,
	0xcb, 0x8b, 0xfa, 0xca, 0x5f, 0x17, 0xf5, 0x95, 0x9f, 0x36, 0xaf, 0x6d, 0xb3, 0x67, 0x05, 0x9a,
	0xe1, 0xaa, 0x3f, 0x76, 0xbe, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xa1, 0xfd, 0xa0, 0xf7,
	0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DefaultUnbondingPeriodBlocks != that1.DefaultUnbondingPeriodBlocks {
		return false
	}
	if this.DefaultUnilateralSlashCapBps != that1.DefaultUnilateralSlashCapBps {
		return false
	}
	if this.DefaultTier1WindowBlocks != that1.DefaultTier1WindowBlocks {
		return false
	}
	if this.DefaultTier1AggregateCapBps != that1.DefaultTier1AggregateCapBps {
		return false
	}
	if this.DefaultTier1CooldownBlocks != that1.DefaultTier1CooldownBlocks {
		return false
	}
	if this.DefaultUnderfundedGraceBlocks != that1.DefaultUnderfundedGraceBlocks {
		return false
	}
	if this.ReportContestWindowBlocks != that1.ReportContestWindowBlocks {
		return false
	}
	if this.MaxPendingBlocks != that1.MaxPendingBlocks {
		return false
	}
	if this.MaxEscalatedBlocks != that1.MaxEscalatedBlocks {
		return false
	}
	if this.ReportRefileCooldownBlocks != that1.ReportRefileCooldownBlocks {
		return false
	}
	if !this.ReportDepositAmount.Equal(that1.ReportDepositAmount) {
		return false
	}
	if this.MinReporterTrustLevel != that1.MinReporterTrustLevel {
		return false
	}
	if this.MaxReportsPerReporterPerOperatorPerWindow != that1.MaxReportsPerReporterPerOperatorPerWindow {
		return false
	}
	if this.ReporterRateLimitWindowBlocks != that1.ReporterRateLimitWindowBlocks {
		return false
	}
	if this.EndblockerSweepLimit != that1.EndblockerSweepLimit {
		return false
	}
	if this.MaxMetadataBytes != that1.MaxMetadataBytes {
		return false
	}
	if this.MaxReasonBytes != that1.MaxReasonBytes {
		return false
	}
	if this.MaxActiveOperatorsPerAddress != that1.MaxActiveOperatorsPerAddress {
		return false
	}
	if !this.ReputationGrantPerBondBlock.Equal(that1.ReputationGrantPerBondBlock) {
		return false
	}
	if this.DefaultPaginationLimit != that1.DefaultPaginationLimit {
		return false
	}
	if this.MaxPaginationLimit != that1.MaxPaginationLimit {
		return false
	}
	if this.MaxSystemReportsPerCallerPerWindow != that1.MaxSystemReportsPerCallerPerWindow {
		return false
	}
	if this.RateLimitWindowBlocks != that1.RateLimitWindowBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RateLimitWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RateLimitWindowBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.MaxSystemReportsPerCallerPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSystemReportsPerCallerPerWindow))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.MaxPaginationLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPaginationLimit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.DefaultPaginationLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultPaginationLimit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	{
		size := m.ReputationGrantPerBondBlock.Size()
		i -= size
		if _, err := m.ReputationGrantPerBondBlock.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	if m.MaxActiveOperatorsPerAddress != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxActiveOperatorsPerAddress))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.MaxReasonBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxReasonBytes))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.MaxMetadataBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMetadataBytes))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.EndblockerSweepLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EndblockerSweepLimit))
		i--
		dAtA[i] = 0x78
	}
	if m.ReporterRateLimitWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReporterRateLimitWindowBlocks))
		i--
		dAtA[i] = 0x70
	}
	if m.MaxReportsPerReporterPerOperatorPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxReportsPerReporterPerOperatorPerWindow))
		i--
		dAtA[i] = 0x68
	}
	if len(m.MinReporterTrustLevel) > 0 {
		i -= len(m.MinReporterTrustLevel)
		copy(dAtA[i:], m.MinReporterTrustLevel)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinReporterTrustLevel)))
		i--
		dAtA[i] = 0x62
	}
	{
		size := m.ReportDepositAmount.Size()
		i -= size
		if _, err := m.ReportDepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.ReportRefileCooldownBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReportRefileCooldownBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxEscalatedBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxEscalatedBlocks))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxPendingBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.ReportContestWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReportContestWindowBlocks))
		i--
		dAtA[i] = 0x38
	}
	if m.DefaultUnderfundedGraceBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultUnderfundedGraceBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.DefaultTier1CooldownBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultTier1CooldownBlocks))
		i--
		dAtA[i] = 0x28
	}
	if m.DefaultTier1AggregateCapBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultTier1AggregateCapBps))
		i--
		dAtA[i] = 0x20
	}
	if m.DefaultTier1WindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultTier1WindowBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.DefaultUnilateralSlashCapBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultUnilateralSlashCapBps))
		i--
		dAtA[i] = 0x10
	}
	if m.DefaultUnbondingPeriodBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultUnbondingPeriodBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DefaultUnbondingPeriodBlocks != 0 {
		n += 1 + sovParams(uint64(m.DefaultUnbondingPeriodBlocks))
	}
	if m.DefaultUnilateralSlashCapBps != 0 {
		n += 1 + sovParams(uint64(m.DefaultUnilateralSlashCapBps))
	}
	if m.DefaultTier1WindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.DefaultTier1WindowBlocks))
	}
	if m.DefaultTier1AggregateCapBps != 0 {
		n += 1 + sovParams(uint64(m.DefaultTier1AggregateCapBps))
	}
	if m.DefaultTier1CooldownBlocks != 0 {
		n += 1 + sovParams(uint64(m.DefaultTier1CooldownBlocks))
	}
	if m.DefaultUnderfundedGraceBlocks != 0 {
		n += 1 + sovParams(uint64(m.DefaultUnderfundedGraceBlocks))
	}
	if m.ReportContestWindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.ReportContestWindowBlocks))
	}
	if m.MaxPendingBlocks != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingBlocks))
	}
	if m.MaxEscalatedBlocks != 0 {
		n += 1 + sovParams(uint64(m.MaxEscalatedBlocks))
	}
	if m.ReportRefileCooldownBlocks != 0 {
		n += 1 + sovParams(uint64(m.ReportRefileCooldownBlocks))
	}
	l = m.ReportDepositAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.MinReporterTrustLevel)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxReportsPerReporterPerOperatorPerWindow != 0 {
		n += 1 + sovParams(uint64(m.MaxReportsPerReporterPerOperatorPerWindow))
	}
	if m.ReporterRateLimitWindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.ReporterRateLimitWindowBlocks))
	}
	if m.EndblockerSweepLimit != 0 {
		n += 1 + sovParams(uint64(m.EndblockerSweepLimit))
	}
	if m.MaxMetadataBytes != 0 {
		n += 2 + sovParams(uint64(m.MaxMetadataBytes))
	}
	if m.MaxReasonBytes != 0 {
		n += 2 + sovParams(uint64(m.MaxReasonBytes))
	}
	if m.MaxActiveOperatorsPerAddress != 0 {
		n += 2 + sovParams(uint64(m.MaxActiveOperatorsPerAddress))
	}
	l = m.ReputationGrantPerBondBlock.Size()
	n += 2 + l + sovParams(uint64(l))
	if m.DefaultPaginationLimit != 0 {
		n += 2 + sovParams(uint64(m.DefaultPaginationLimit))
	}
	if m.MaxPaginationLimit != 0 {
		n += 2 + sovParams(uint64(m.MaxPaginationLimit))
	}
	if m.MaxSystemReportsPerCallerPerWindow != 0 {
		n += 2 + sovParams(uint64(m.MaxSystemReportsPerCallerPerWindow))
	}
	if m.RateLimitWindowBlocks != 0 {
		n += 2 + sovParams(uint64(m.RateLimitWindowBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultUnbondingPeriodBlocks", wireType)
			}
			m.DefaultUnbondingPeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultUnbondingPeriodBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultUnilateralSlashCapBps", wireType)
			}
			m.DefaultUnilateralSlashCapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultUnilateralSlashCapBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultTier1WindowBlocks", wireType)
			}
			m.DefaultTier1WindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultTier1WindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultTier1AggregateCapBps", wireType)
			}
			m.DefaultTier1AggregateCapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultTier1AggregateCapBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultTier1CooldownBlocks", wireType)
			}
			m.DefaultTier1CooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultTier1CooldownBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultUnderfundedGraceBlocks", wireType)
			}
			m.DefaultUnderfundedGraceBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultUnderfundedGraceBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportContestWindowBlocks", wireType)
			}
			m.ReportContestWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportContestWindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingBlocks", wireType)
			}
			m.MaxPendingBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEscalatedBlocks", wireType)
			}
			m.MaxEscalatedBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEscalatedBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportRefileCooldownBlocks", wireType)
			}
			m.ReportRefileCooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportRefileCooldownBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportDepositAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReportDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReporterTrustLevel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinReporterTrustLevel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReportsPerReporterPerOperatorPerWindow", wireType)
			}
			m.MaxReportsPerReporterPerOperatorPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReportsPerReporterPerOperatorPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterRateLimitWindowBlocks", wireType)
			}
			m.ReporterRateLimitWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReporterRateLimitWindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndblockerSweepLimit", wireType)
			}
			m.EndblockerSweepLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndblockerSweepLimit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMetadataBytes", wireType)
			}
			m.MaxMetadataBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMetadataBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReasonBytes", wireType)
			}
			m.MaxReasonBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReasonBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActiveOperatorsPerAddress", wireType)
			}
			m.MaxActiveOperatorsPerAddress = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActiveOperatorsPerAddress |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReputationGrantPerBondBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReputationGrantPerBondBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultPaginationLimit", wireType)
			}
			m.DefaultPaginationLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultPaginationLimit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPaginationLimit", wireType)
			}
			m.MaxPaginationLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPaginationLimit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSystemReportsPerCallerPerWindow", wireType)
			}
			m.MaxSystemReportsPerCallerPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSystemReportsPerCallerPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimitWindowBlocks", wireType)
			}
			m.RateLimitWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateLimitWindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
