package types

// DONTCOVER

import (
	"cosmossdk.io/errors"
)

// x/season module sentinel errors
var (
	ErrInvalidSigner = errors.Register(ModuleName, 1100, "expected gov account as only signer for proposal message")

	// Profile errors (1101-1119)
	ErrProfileNotFound            = errors.Register(ModuleName, 1101, "member profile not found")
	ErrDisplayNameTooShort        = errors.Register(ModuleName, 1102, "display name too short")
	ErrDisplayNameTooLong         = errors.Register(ModuleName, 1103, "display name too long")
	ErrDisplayNameCooldown        = errors.Register(ModuleName, 1104, "display name change cooldown not passed")
	ErrUsernameTooShort           = errors.Register(ModuleName, 1105, "username too short")
	ErrUsernameTooLong            = errors.Register(ModuleName, 1106, "username too long")
	ErrUsernameCooldown           = errors.Register(ModuleName, 1107, "username change cooldown not passed")
	ErrUsernameAlreadyTaken       = errors.Register(ModuleName, 1108, "username already taken")
	ErrUsernameInvalidChars       = errors.Register(ModuleName, 1109, "username contains invalid characters")
	ErrTitleNotUnlocked           = errors.Register(ModuleName, 1110, "title not unlocked by member")
	ErrTitleNotFound              = errors.Register(ModuleName, 1111, "title not found")
	ErrDisplayNameModerated       = errors.Register(ModuleName, 1112, "display name is moderated")
	ErrDisplayNameReportCooldown  = errors.Register(ModuleName, 1113, "display name report cooldown not passed")
	ErrCannotReportOwnDisplayName = errors.Register(ModuleName, 1114, "cannot report own display name")
	ErrDisplayNameNotModerated    = errors.Register(ModuleName, 1115, "display name is not moderated")
	ErrAppealPeriodExpired        = errors.Register(ModuleName, 1116, "appeal period has expired")
	ErrAppealAlreadySubmitted     = errors.Register(ModuleName, 1117, "appeal already submitted")
	ErrNotDisplayNameOwner        = errors.Register(ModuleName, 1118, "not the display name owner")
	ErrAppealAlreadyResolved      = errors.Register(ModuleName, 1119, "appeal has already been resolved")
	ErrNoAppealToResolve          = errors.Register(ModuleName, 1240, "no appeal exists to resolve")
	ErrAppealPeriodNotExpired     = errors.Register(ModuleName, 1241, "appeal period has not yet expired")

	// Guild errors (1120-1149)
	ErrGuildNotFound            = errors.Register(ModuleName, 1120, "guild not found")
	ErrGuildNameTooShort        = errors.Register(ModuleName, 1121, "guild name too short")
	ErrGuildNameTooLong         = errors.Register(ModuleName, 1122, "guild name too long")
	ErrGuildNameTaken           = errors.Register(ModuleName, 1123, "guild name already taken")
	ErrAlreadyInGuild           = errors.Register(ModuleName, 1124, "member is already in a guild")
	ErrNotInGuild               = errors.Register(ModuleName, 1125, "member is not in a guild")
	ErrNotGuildFounder          = errors.Register(ModuleName, 1126, "only guild founder can perform this action")
	ErrNotGuildFounderOrOfficer = errors.Register(ModuleName, 1127, "only guild founder or officer can perform this action")
	ErrGuildFull                = errors.Register(ModuleName, 1128, "guild has reached maximum members")
	ErrGuildHopCooldown         = errors.Register(ModuleName, 1129, "guild hop cooldown not passed")
	ErrMaxGuildsPerSeason       = errors.Register(ModuleName, 1130, "already joined maximum guilds this season")
	ErrGuildInviteOnly          = errors.Register(ModuleName, 1131, "guild is invite only")
	ErrNoGuildInvite            = errors.Register(ModuleName, 1132, "no pending guild invite")
	ErrGuildInviteExpired       = errors.Register(ModuleName, 1133, "guild invite has expired")
	ErrAlreadyInvited           = errors.Register(ModuleName, 1134, "member already has pending invite")
	ErrMaxPendingInvites        = errors.Register(ModuleName, 1135, "guild has maximum pending invites")
	ErrCannotKickFounder        = errors.Register(ModuleName, 1136, "cannot kick guild founder")
	ErrGuildFrozen              = errors.Register(ModuleName, 1137, "guild is frozen")
	ErrGuildNotFrozen           = errors.Register(ModuleName, 1138, "guild is not frozen")
	ErrGuildDissolved           = errors.Register(ModuleName, 1139, "guild has been dissolved")
	ErrAlreadyOfficer           = errors.Register(ModuleName, 1140, "member is already an officer")
	ErrNotOfficer               = errors.Register(ModuleName, 1141, "member is not an officer")
	ErrMaxOfficers              = errors.Register(ModuleName, 1142, "guild has maximum officers")
	ErrCannotLeaveAsFounder     = errors.Register(ModuleName, 1143, "founder must transfer ownership or dissolve guild")
	ErrGuildDescriptionTooLong  = errors.Register(ModuleName, 1144, "guild description too long")
	ErrGuildTooYoung            = errors.Register(ModuleName, 1145, "guild must be older to perform this action")
	ErrNotGuildMember           = errors.Register(ModuleName, 1146, "not a member of this guild")
	ErrFounderCannotBeOfficer   = errors.Register(ModuleName, 1147, "founder cannot be an officer")

	// Quest errors (1150-1169)
	ErrQuestNotFound           = errors.Register(ModuleName, 1150, "quest not found")
	ErrQuestNotActive          = errors.Register(ModuleName, 1151, "quest is not active")
	ErrQuestAlreadyStarted     = errors.Register(ModuleName, 1152, "quest already started")
	ErrQuestNotStarted         = errors.Register(ModuleName, 1153, "quest not started")
	ErrQuestNotComplete        = errors.Register(ModuleName, 1154, "quest objectives not complete")
	ErrQuestAlreadyClaimed     = errors.Register(ModuleName, 1155, "quest reward already claimed")
	ErrQuestOnCooldown         = errors.Register(ModuleName, 1156, "quest on cooldown")
	ErrQuestPrerequisiteNotMet = errors.Register(ModuleName, 1157, "quest prerequisite not met")
	ErrQuestLevelTooLow        = errors.Register(ModuleName, 1158, "level too low for quest")
	ErrMaxActiveQuests         = errors.Register(ModuleName, 1159, "maximum active quests reached")
	ErrQuestSeasonMismatch     = errors.Register(ModuleName, 1160, "quest is not available this season")
	ErrQuestXpRewardTooHigh    = errors.Register(ModuleName, 1161, "quest XP reward exceeds maximum")
	ErrQuestTooManyObjectives  = errors.Register(ModuleName, 1162, "quest has too many objectives")
	ErrInvalidQuestObjective   = errors.Register(ModuleName, 1163, "invalid quest objective")
	ErrQuestIdAlreadyExists    = errors.Register(ModuleName, 1164, "quest ID already exists")

	// Season transition errors (1170-1189)
	ErrNoActiveTransition       = errors.Register(ModuleName, 1170, "no active season transition")
	ErrTransitionInProgress     = errors.Register(ModuleName, 1171, "season transition already in progress")
	ErrTransitionTooFarToAbort  = errors.Register(ModuleName, 1172, "transition too far to abort safely")
	ErrNotInRecoveryMode        = errors.Register(ModuleName, 1173, "transition not in recovery mode")
	ErrCannotSkipCriticalPhase  = errors.Register(ModuleName, 1174, "cannot skip critical transition phase")
	ErrSeasonNotActive          = errors.Register(ModuleName, 1175, "season is not active")
	ErrMaxExtensionsReached     = errors.Register(ModuleName, 1176, "maximum season extensions reached")
	ErrExtensionTooLong         = errors.Register(ModuleName, 1177, "extension exceeds maximum allowed")
	ErrMaintenanceMode          = errors.Register(ModuleName, 1178, "system is in maintenance mode")
	ErrSeasonAlreadyExists      = errors.Register(ModuleName, 1179, "season already exists")
	ErrNextSeasonInfoAlreadySet = errors.Register(ModuleName, 1180, "next season info already set")

	// Authority errors (1190-1199)
	ErrNotOperationsCommittee = errors.Register(ModuleName, 1190, "only operations committee can perform this action")
	ErrNotCommonsCouncil      = errors.Register(ModuleName, 1191, "only commons council can perform this action")
	ErrNotMember              = errors.Register(ModuleName, 1192, "only registered members can perform this action")
	ErrNotGovAuthority        = errors.Register(ModuleName, 1193, "only governance authority can perform this action")
	ErrNotAuthorized          = errors.Register(ModuleName, 1194, "sender not authorized for this action")

	// XP errors (1200-1209)
	ErrXPCapReached        = errors.Register(ModuleName, 1200, "XP cap reached for this epoch")
	ErrInvalidXPSource     = errors.Register(ModuleName, 1201, "invalid XP source")
	ErrAccountTooNew       = errors.Register(ModuleName, 1202, "account too new for this action")
	ErrXPCooldownNotPassed = errors.Register(ModuleName, 1203, "XP cooldown not passed")

	// Achievement errors (1210-1219)
	ErrAchievementNotFound      = errors.Register(ModuleName, 1210, "achievement not found")
	ErrAchievementAlreadyEarned = errors.Register(ModuleName, 1211, "achievement already earned")
	ErrInvalidAchievementId     = errors.Register(ModuleName, 1212, "invalid achievement ID")
	ErrAchievementExists        = errors.Register(ModuleName, 1213, "achievement already exists")

	// Title management errors (1230-1239)
	ErrInvalidTitleId = errors.Register(ModuleName, 1230, "invalid title ID")
	ErrTitleExists    = errors.Register(ModuleName, 1231, "title already exists")

	// Cross-module integration errors (1220-1229)
	ErrNameAlreadyReserved  = errors.Register(ModuleName, 1220, "name is already reserved")
	ErrInsufficientDREAM    = errors.Register(ModuleName, 1221, "insufficient DREAM balance")
	ErrDREAMOperationFailed = errors.Register(ModuleName, 1222, "DREAM operation failed")
	ErrNameOperationFailed  = errors.Register(ModuleName, 1223, "name operation failed")

	// Nomination errors (1250-1269)
	ErrNominationNotFound         = errors.Register(ModuleName, 1250, "nomination not found")
	ErrNominationWindowNotOpen    = errors.Register(ModuleName, 1251, "nomination window is not open")
	ErrMaxNominationsReached      = errors.Register(ModuleName, 1252, "maximum nominations per member reached")
	ErrAlreadyNominated           = errors.Register(ModuleName, 1253, "content already nominated this season")
	ErrInvalidContentRef          = errors.Register(ModuleName, 1254, "invalid content reference format")
	ErrContentNotFound            = errors.Register(ModuleName, 1255, "referenced content not found")
	ErrRationaleTooLong           = errors.Register(ModuleName, 1256, "rationale exceeds maximum length")
	ErrInsufficientTrustLevel     = errors.Register(ModuleName, 1257, "insufficient trust level for this action")
	ErrCannotNominateOwnContent   = errors.Register(ModuleName, 1258, "cannot nominate own content")
	ErrNominationStakeExists      = errors.Register(ModuleName, 1259, "already staked on this nomination")
	ErrNominationStakeNotFound    = errors.Register(ModuleName, 1260, "nomination stake not found")
	ErrStakeAmountTooLow          = errors.Register(ModuleName, 1261, "stake amount below minimum")
	ErrCannotUnstakeAfterWindow   = errors.Register(ModuleName, 1262, "cannot unstake after nomination window closes")
	ErrSeasonNotInNominationPhase = errors.Register(ModuleName, 1263, "season is not in nomination phase")
)
