package types

// DONTCOVER

import (
	"cosmossdk.io/errors"
)

// x/collect module sentinel errors
// Error codes aligned with spec §13.
var (
	ErrInvalidSigner                  = errors.Register(ModuleName, 1099, "expected gov account as only signer for proposal message")
	ErrCollectionNotFound             = errors.Register(ModuleName, 1100, "collection not found")
	ErrItemNotFound                   = errors.Register(ModuleName, 1101, "item not found")
	ErrUnauthorized                   = errors.Register(ModuleName, 1102, "unauthorized")
	ErrMaxCollections                 = errors.Register(ModuleName, 1103, "owner has reached tiered collection limit")
	ErrMaxItems                       = errors.Register(ModuleName, 1104, "collection has reached max items per collection")
	ErrInvalidName                    = errors.Register(ModuleName, 1105, "name empty or exceeds max length")
	ErrInvalidTitle                   = errors.Register(ModuleName, 1106, "title empty or exceeds max length")
	ErrInvalidDescription             = errors.Register(ModuleName, 1107, "description exceeds max length")
	ErrInvalidReference               = errors.Register(ModuleName, 1108, "reference type/data mismatch")
	ErrReferenceFieldTooLong          = errors.Register(ModuleName, 1109, "reference string field exceeds max length")
	ErrInvalidPosition                = errors.Register(ModuleName, 1110, "position out of range")
	ErrTagTooLong                     = errors.Register(ModuleName, 1111, "tag exceeds max length")
	ErrMaxTags                        = errors.Register(ModuleName, 1112, "tag count exceeds limit")
	ErrMaxAttributes                  = errors.Register(ModuleName, 1113, "attribute count exceeds max per item")
	ErrAttributeTooLong               = errors.Register(ModuleName, 1114, "attribute key/value exceeds length limit")
	ErrMaxCollaborators               = errors.Register(ModuleName, 1115, "collection at max collaborators per collection")
	ErrNotMember                      = errors.Register(ModuleName, 1116, "address is not an active x/rep member")
	ErrAlreadyCollaborator            = errors.Register(ModuleName, 1117, "already a collaborator")
	ErrCannotCollaborateSelf          = errors.Register(ModuleName, 1118, "cannot add owner as collaborator")
	ErrBatchTooLarge                  = errors.Register(ModuleName, 1119, "batch size exceeds max batch size")
	ErrInvalidExpiry                  = errors.Register(ModuleName, 1120, "expiry in past or exceeds max TTL")
	ErrCannotChangeEncryption         = errors.Register(ModuleName, 1121, "encrypted is immutable after creation")
	ErrCannotChangeVisibility         = errors.Register(ModuleName, 1122, "visibility is immutable after creation")
	ErrEncryptedRequiresPrivate       = errors.Register(ModuleName, 1123, "encrypted = true requires VISIBILITY_PRIVATE")
	ErrPrivateRequiresEncryption      = errors.Register(ModuleName, 1124, "VISIBILITY_PRIVATE requires encrypted = true")
	ErrBatchItemsMixedCollections     = errors.Register(ModuleName, 1125, "batch items span multiple collections")
	ErrAdminRemoveAdmin               = errors.Register(ModuleName, 1126, "ADMIN cannot remove another ADMIN")
	ErrAdminOnlyOwner                 = errors.Register(ModuleName, 1127, "only owner can grant/revoke ADMIN")
	ErrInsufficientFunds              = errors.Register(ModuleName, 1128, "insufficient SPARK for deposit + fees")
	ErrEncryptedDataTooLarge          = errors.Register(ModuleName, 1129, "blob exceeds max encrypted data size")
	ErrEncryptedFieldMismatch         = errors.Register(ModuleName, 1130, "structured fields on encrypted collection or blob on public")
	ErrNotCurator                     = errors.Register(ModuleName, 1131, "not a registered active curator")
	ErrAlreadyCurator                 = errors.Register(ModuleName, 1132, "already registered as curator")
	ErrInsufficientBond               = errors.Register(ModuleName, 1133, "bond below min curator bond")
	ErrTrustLevelTooLow               = errors.Register(ModuleName, 1134, "below required trust level")
	ErrCuratorTooNew                  = errors.Register(ModuleName, 1135, "curator registered less than min age blocks ago")
	ErrCannotRateOwnCollection        = errors.Register(ModuleName, 1136, "curator is owner/collaborator of collection")
	ErrAlreadyReviewed                = errors.Register(ModuleName, 1137, "one active review per curator per collection")
	ErrMaxReviews                     = errors.Register(ModuleName, 1138, "collection at max reviews per collection")
	ErrCannotRatePrivate              = errors.Register(ModuleName, 1139, "cannot rate private collections")
	ErrReviewNotFound                 = errors.Register(ModuleName, 1140, "review not found")
	ErrReviewAlreadyChallenged        = errors.Register(ModuleName, 1141, "review already challenged")
	ErrChallengeWindowExpired         = errors.Register(ModuleName, 1142, "past challenge window blocks")
	ErrCannotChallengeSelf            = errors.Register(ModuleName, 1143, "cannot challenge own review")
	ErrReasonTooLong                  = errors.Register(ModuleName, 1144, "challenge reason exceeds max length")
	ErrCuratorHasPendingChallenges    = errors.Register(ModuleName, 1145, "cannot unregister with pending challenges")
	ErrCuratorBondInsufficient        = errors.Register(ModuleName, 1146, "curator bond dropped below min (auto-deactivated)")
	ErrNonMemberPermanent             = errors.Register(ModuleName, 1147, "non-members cannot create permanent collections")
	ErrNonMemberTTLExceeded           = errors.Register(ModuleName, 1148, "non-member TTL exceeds max non-member TTL blocks")
	ErrSponsorshipRequestExists       = errors.Register(ModuleName, 1149, "collection already has a pending sponsorship request")
	ErrSponsorshipRequestNotFound     = errors.Register(ModuleName, 1150, "no pending sponsorship request for this collection")
	ErrMemberCannotRequestSponsorship = errors.Register(ModuleName, 1151, "members can convert to permanent directly")
	ErrCannotSponsorOwn               = errors.Register(ModuleName, 1152, "sponsor cannot be the collection owner")
	ErrSponsorTrustLevelTooLow        = errors.Register(ModuleName, 1153, "sponsor below min sponsor trust level")
	ErrAlreadySponsored               = errors.Register(ModuleName, 1154, "collection has already been sponsored")
	ErrCollectionExpired              = errors.Register(ModuleName, 1155, "collection has already expired")
	ErrCollectionAlreadyPermanent     = errors.Register(ModuleName, 1156, "collection is already permanent")
	ErrItemsLockedForSponsorship      = errors.Register(ModuleName, 1157, "cannot add/remove items while sponsorship request is pending")
	ErrDuplicateIDs                   = errors.Register(ModuleName, 1158, "batch contains duplicate item IDs")
	ErrCannotRevertPermanent          = errors.Register(ModuleName, 1159, "permanent collection cannot set expires_at > 0")
	ErrCollectionImmutable            = errors.Register(ModuleName, 1160, "collection is immutable after endorsement")
	ErrNotSentinel                    = errors.Register(ModuleName, 1161, "not an active forum sentinel")
	ErrNotPublicActive                = errors.Register(ModuleName, 1162, "target must be a public, active collection or item")
	ErrInsufficientBondAvailable      = errors.Register(ModuleName, 1164, "sentinel bond insufficient for commit")
	ErrAlreadyHidden                  = errors.Register(ModuleName, 1165, "content is already hidden")
	ErrHideRecordNotFound             = errors.Register(ModuleName, 1167, "hide record not found")
	ErrAlreadyFlagged                 = errors.Register(ModuleName, 1171, "already flagged this target")
	ErrMaxDailyReactions              = errors.Register(ModuleName, 1173, "daily reaction limit reached")
	ErrNotContentOwner                = errors.Register(ModuleName, 1175, "only content owner can appeal")
	ErrAppealAlreadyFiled             = errors.Register(ModuleName, 1168, "appeal already filed for this hide record")
	ErrAppealCooldown                 = errors.Register(ModuleName, 1169, "appeal cooldown not elapsed")
	ErrAppealDeadlinePassed           = errors.Register(ModuleName, 1170, "appeal deadline has passed")
	ErrAlreadyVoted                   = errors.Register(ModuleName, 1182, "already voted on this target")
	ErrCannotVoteOwnContent           = errors.Register(ModuleName, 1176, "cannot vote on own content")
	ErrCollectionNotPending           = errors.Register(ModuleName, 1177, "collection must be in PENDING status")
	ErrNotSeekingEndorsement          = errors.Register(ModuleName, 1178, "collection not seeking endorsement")
	ErrAlreadyEndorsed                = errors.Register(ModuleName, 1179, "collection already endorsed")
	ErrCannotEndorseSelf              = errors.Register(ModuleName, 1180, "cannot endorse own collection")
	ErrCannotModifyPrivateContent     = errors.Register(ModuleName, 1183, "cannot moderate private content")
	ErrHideRecordResolved             = errors.Register(ModuleName, 1184, "hide record already resolved")
	ErrInvalidFlagReason              = errors.Register(ModuleName, 1185, "invalid or unspecified flag reason")
	ErrMaxFlagsPerTarget              = errors.Register(ModuleName, 1186, "target has reached max flaggers")
	ErrFlagReasonTextRequired         = errors.Register(ModuleName, 1187, "reason_text required for REASON_OTHER")
	ErrFlagReasonTextTooLong          = errors.Register(ModuleName, 1188, "flag reason_text exceeds max length")
)
