// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/collect/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the collect module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params              Params               `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Collections         []Collection         `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections"`
	CollectionCount     uint64               `protobuf:"varint,3,opt,name=collection_count,json=collectionCount,proto3" json:"collection_count,omitempty"`
	Items               []Item               `protobuf:"bytes,4,rep,name=items,proto3" json:"items"`
	ItemCount           uint64               `protobuf:"varint,5,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Collaborators       []Collaborator       `protobuf:"bytes,6,rep,name=collaborators,proto3" json:"collaborators"`
	Curators            []Curator            `protobuf:"bytes,7,rep,name=curators,proto3" json:"curators"`
	CurationReviews     []CurationReview     `protobuf:"bytes,8,rep,name=curation_reviews,json=curationReviews,proto3" json:"curation_reviews"`
	CurationReviewCount uint64               `protobuf:"varint,9,opt,name=curation_review_count,json=curationReviewCount,proto3" json:"curation_review_count,omitempty"`
	CurationSummaries   []CurationSummary    `protobuf:"bytes,10,rep,name=curation_summaries,json=curationSummaries,proto3" json:"curation_summaries"`
	SponsorshipRequests []SponsorshipRequest `protobuf:"bytes,11,rep,name=sponsorship_requests,json=sponsorshipRequests,proto3" json:"sponsorship_requests"`
	Flags               []CollectionFlag     `protobuf:"bytes,12,rep,name=flags,proto3" json:"flags"`
	HideRecords         []HideRecord         `protobuf:"bytes,13,rep,name=hide_records,json=hideRecords,proto3" json:"hide_records"`
	HideRecordCount     uint64               `protobuf:"varint,14,opt,name=hide_record_count,json=hideRecordCount,proto3" json:"hide_record_count,omitempty"`
	Endorsements        []Endorsement        `protobuf:"bytes,15,rep,name=endorsements,proto3" json:"endorsements"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b16b90430cb10524, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCollections() []Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

func (m *GenesisState) GetCollectionCount() uint64 {
	if m != nil {
		return m.CollectionCount
	}
	return 0
}

func (m *GenesisState) GetItems() []Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GenesisState) GetItemCount() uint64 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

func (m *GenesisState) GetCollaborators() []Collaborator {
	if m != nil {
		return m.Collaborators
	}
	return nil
}

func (m *GenesisState) GetCurators() []Curator {
	if m != nil {
		return m.Curators
	}
	return nil
}

func (m *GenesisState) GetCurationReviews() []CurationReview {
	if m != nil {
		return m.CurationReviews
	}
	return nil
}

func (m *GenesisState) GetCurationReviewCount() uint64 {
	if m != nil {
		return m.CurationReviewCount
	}
	return 0
}

func (m *GenesisState) GetCurationSummaries() []CurationSummary {
	if m != nil {
		return m.CurationSummaries
	}
	return nil
}

func (m *GenesisState) GetSponsorshipRequests() []SponsorshipRequest {
	if m != nil {
		return m.SponsorshipRequests
	}
	return nil
}

func (m *GenesisState) GetFlags() []CollectionFlag {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *GenesisState) GetHideRecords() []HideRecord {
	if m != nil {
		return m.HideRecords
	}
	return nil
}

func (m *GenesisState) GetHideRecordCount() uint64 {
	if m != nil {
		return m.HideRecordCount
	}
	return 0
}

func (m *GenesisState) GetEndorsements() []Endorsement {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sparkdream.collect.v1.GenesisState")
}

func init() {
	proto.RegisterFile("sparkdream/collect/v1/genesis.proto", fileDescriptor_b16b90430cb10524)
}

var fileDescriptor_b16b90430cb10524 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x6f, 0x12, 0x41,
	0x18, 0xc6, 0x59, 0x0b, 0x08, 0x03, 0x95, 0x32, 0x6d, 0x93, 0x09, 0xa6, 0x2b, 0xa5, 0xd1, 0xd0,
	0x1e, 0x20, 0x45, 0x13, 0xaf, 0x95, 0xc6, 0x3f, 0x35, 0x26, 0x9a, 0x25, 0xf1, 0xa0, 0x07, 0x32,
	0x2c, 0x23, 0x4c, 0x64, 0x77, 0xd6, 0x79, 0x07, 0xb4, 0x9f, 0xc0, 0xab, 0x1f, 0xc3, 0xa3, 0x1f,
	0xa3, 0xc7, 0x1e, 0x3d, 0x19, 0x03, 0x07, 0xbf, 0x86, 0xd9, 0xd9, 0x61, 0x17, 0x14, 0xe8, 0x85,
	0x0c, 0x2f, 0xcf, 0xf3, 0x7b, 0x5e, 0xde, 0xbc, 0x79, 0xd1, 0x11, 0x04, 0x54, 0x7e, 0xec, 0x4b,
	0x46, 0xbd, 0xa6, 0x2b, 0x46, 0x23, 0xe6, 0xaa, 0xe6, 0xe4, 0xb4, 0x39, 0x60, 0x3e, 0x03, 0x0e,
	0x8d, 0x40, 0x0a, 0x25, 0xf0, 0x7e, 0x22, 0x6a, 0x18, 0x51, 0x63, 0x72, 0x5a, 0x29, 0x53, 0x8f,
	0xfb, 0xa2, 0xa9, 0x3f, 0x23, 0x65, 0x65, 0x6f, 0x20, 0x06, 0x42, 0x3f, 0x9b, 0xe1, 0xcb, 0x54,
	0x6b, 0xab, 0x43, 0x02, 0x2a, 0xa9, 0x67, 0x32, 0x2a, 0x87, 0xab, 0x35, 0xea, 0x32, 0x60, 0x46,
	0x52, 0xfb, 0x9a, 0x43, 0xc5, 0xe7, 0x51, 0x63, 0x1d, 0x45, 0x15, 0xc3, 0x67, 0x28, 0x1b, 0x31,
	0x88, 0x55, 0xb5, 0xea, 0x85, 0xd6, 0x41, 0x63, 0x65, 0xa3, 0x8d, 0x37, 0x5a, 0xd4, 0xce, 0x5f,
	0xfd, 0xba, 0x97, 0xfa, 0xfe, 0xe7, 0xc7, 0x89, 0xe5, 0x18, 0x1f, 0xbe, 0x40, 0x05, 0xa3, 0xe3,
	0xc2, 0x07, 0x72, 0xab, 0xba, 0x55, 0x2f, 0xb4, 0x0e, 0xd7, 0x60, 0xce, 0x63, 0x65, 0x3b, 0x1d,
	0xa2, 0x9c, 0x45, 0x2f, 0x3e, 0x46, 0x3b, 0xc9, 0xd7, 0xae, 0x2b, 0xc6, 0xbe, 0x22, 0x5b, 0x55,
	0xab, 0x9e, 0x76, 0x4a, 0x49, 0xfd, 0x3c, 0x2c, 0xe3, 0xc7, 0x28, 0xc3, 0x15, 0xf3, 0x80, 0xa4,
	0x75, 0xde, 0xdd, 0x35, 0x79, 0x17, 0x8a, 0x79, 0x26, 0x29, 0xd2, 0xe3, 0x03, 0x84, 0xc2, 0x87,
	0xa1, 0x67, 0x34, 0x3d, 0x1f, 0x56, 0x22, 0xee, 0x6b, 0xb4, 0x1d, 0xda, 0x69, 0x4f, 0x48, 0xaa,
	0x84, 0x04, 0x92, 0xd5, 0xfc, 0xa3, 0x0d, 0xff, 0x67, 0xae, 0x35, 0x39, 0xcb, 0x7e, 0x7c, 0x86,
	0x72, 0xee, 0xd8, 0xb0, 0x6e, 0x6b, 0x96, 0xbd, 0x8e, 0x35, 0x5e, 0xc4, 0xc4, 0x2e, 0xfc, 0x16,
	0xed, 0xe8, 0x77, 0x38, 0x13, 0xc9, 0x26, 0x9c, 0x7d, 0x06, 0x92, 0xd3, 0xa4, 0xfb, 0x9b, 0x48,
	0x5c, 0xf8, 0x8e, 0x56, 0x1b, 0x60, 0xc9, 0x5d, 0xaa, 0x02, 0x6e, 0xa1, 0xfd, 0x7f, 0xb8, 0x66,
	0x28, 0x79, 0x3d, 0x94, 0xdd, 0x65, 0x7d, 0x34, 0x9e, 0xf7, 0x08, 0xc7, 0x1e, 0x18, 0x7b, 0x1e,
	0x95, 0x9c, 0x01, 0x41, 0xba, 0x9b, 0x07, 0x37, 0x74, 0xd3, 0xd1, 0xfa, 0x4b, 0xd3, 0x4e, 0xd9,
	0x5d, 0x2a, 0x73, 0x06, 0xb8, 0x87, 0xf6, 0x20, 0x10, 0x3e, 0x08, 0x09, 0x43, 0x1e, 0x74, 0x25,
	0xfb, 0x34, 0x66, 0xa0, 0x80, 0x14, 0x34, 0xfe, 0x78, 0x0d, 0xbe, 0x93, 0x58, 0x9c, 0xc8, 0x61,
	0x12, 0x76, 0xe1, 0xbf, 0x5f, 0x00, 0x3f, 0x41, 0x99, 0x0f, 0x23, 0x3a, 0x00, 0x52, 0xdc, 0x3c,
	0xc1, 0x78, 0xdd, 0x9e, 0x8d, 0xe8, 0x60, 0xbe, 0x41, 0xda, 0x89, 0x5f, 0xa2, 0xe2, 0x90, 0xf7,
	0x59, 0x57, 0x32, 0x57, 0xc8, 0x3e, 0x90, 0xed, 0x8d, 0x1b, 0xff, 0x82, 0xf7, 0x99, 0xa3, 0x95,
	0xf3, 0x8d, 0x1f, 0xc6, 0x15, 0xc0, 0x27, 0xa8, 0xbc, 0xc0, 0x32, 0xf3, 0xbf, 0x13, 0xad, 0x7c,
	0xa2, 0x8b, 0x66, 0xff, 0x0a, 0x15, 0x99, 0xdf, 0x17, 0x12, 0x98, 0xc7, 0x7c, 0x05, 0xa4, 0xa4,
	0x73, 0x6b, 0x6b, 0x72, 0x9f, 0x26, 0x52, 0x13, 0xbc, 0xe4, 0x6e, 0x3f, 0xba, 0x9a, 0xda, 0xd6,
	0xf5, 0xd4, 0xb6, 0x7e, 0x4f, 0x6d, 0xeb, 0xdb, 0xcc, 0x4e, 0x5d, 0xcf, 0xec, 0xd4, 0xcf, 0x99,
	0x9d, 0x7a, 0x57, 0x59, 0x38, 0x23, 0x5f, 0xe2, 0x43, 0xa2, 0xaf, 0x48, 0x2f, 0xab, 0xcf, 0xc8,
	0xc3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x39, 0x0f, 0x21, 0xf4, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Endorsements) > 0 {
		for iNdEx := len(m.Endorsements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Endorsements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.HideRecordCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.HideRecordCount))
		i--
		dAtA[i] = 0x70
	}
	if len(m.HideRecords) > 0 {
		for iNdEx := len(m.HideRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HideRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Flags) > 0 {
		for iNdEx := len(m.Flags) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Flags[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.SponsorshipRequests) > 0 {
		for iNdEx := len(m.SponsorshipRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SponsorshipRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.CurationSummaries) > 0 {
		for iNdEx := len(m.CurationSummaries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurationSummaries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.CurationReviewCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CurationReviewCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.CurationReviews) > 0 {
		for iNdEx := len(m.CurationReviews) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurationReviews[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Curators) > 0 {
		for iNdEx := len(m.Curators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Curators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Collaborators) > 0 {
		for iNdEx := len(m.Collaborators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Collaborators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.ItemCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ItemCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CollectionCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CollectionCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Collections) > 0 {
		for iNdEx := len(m.Collections) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Collections[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Collections) > 0 {
		for _, e := range m.Collections {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CollectionCount != 0 {
		n += 1 + sovGenesis(uint64(m.CollectionCount))
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ItemCount != 0 {
		n += 1 + sovGenesis(uint64(m.ItemCount))
	}
	if len(m.Collaborators) > 0 {
		for _, e := range m.Collaborators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Curators) > 0 {
		for _, e := range m.Curators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CurationReviews) > 0 {
		for _, e := range m.CurationReviews {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CurationReviewCount != 0 {
		n += 1 + sovGenesis(uint64(m.CurationReviewCount))
	}
	if len(m.CurationSummaries) > 0 {
		for _, e := range m.CurationSummaries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SponsorshipRequests) > 0 {
		for _, e := range m.SponsorshipRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Flags) > 0 {
		for _, e := range m.Flags {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HideRecords) > 0 {
		for _, e := range m.HideRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.HideRecordCount != 0 {
		n += 1 + sovGenesis(uint64(m.HideRecordCount))
	}
	if len(m.Endorsements) > 0 {
		for _, e := range m.Endorsements {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collections = append(m.Collections, Collection{})
			if err := m.Collections[len(m.Collections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionCount", wireType)
			}
			m.CollectionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Item{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemCount", wireType)
			}
			m.ItemCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collaborators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collaborators = append(m.Collaborators, Collaborator{})
			if err := m.Collaborators[len(m.Collaborators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curators = append(m.Curators, Curator{})
			if err := m.Curators[len(m.Curators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationReviews", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurationReviews = append(m.CurationReviews, CurationReview{})
			if err := m.CurationReviews[len(m.CurationReviews)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationReviewCount", wireType)
			}
			m.CurationReviewCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurationReviewCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurationSummaries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurationSummaries = append(m.CurationSummaries, CurationSummary{})
			if err := m.CurationSummaries[len(m.CurationSummaries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SponsorshipRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SponsorshipRequests = append(m.SponsorshipRequests, SponsorshipRequest{})
			if err := m.SponsorshipRequests[len(m.SponsorshipRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flags = append(m.Flags, CollectionFlag{})
			if err := m.Flags[len(m.Flags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HideRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HideRecords = append(m.HideRecords, HideRecord{})
			if err := m.HideRecords[len(m.HideRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HideRecordCount", wireType)
			}
			m.HideRecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HideRecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endorsements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endorsements = append(m.Endorsements, Endorsement{})
			if err := m.Endorsements[len(m.Endorsements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
