// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/shield/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the shield module.
type Params struct {
	// Whether shielded execution is enabled globally
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Maximum uspark to skim from community pool per day (14400 blocks at 6s/block)
	MaxFundingPerDay cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=max_funding_per_day,json=maxFundingPerDay,proto3,customtype=cosmossdk.io/math.Int" json:"max_funding_per_day"`
	// Target minimum balance for the shield module account
	MinGasReserve cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=min_gas_reserve,json=minGasReserve,proto3,customtype=cosmossdk.io/math.Int" json:"min_gas_reserve"`
	// Maximum gas allowed per shielded execution
	MaxGasPerExec uint64 `protobuf:"varint,4,opt,name=max_gas_per_exec,json=maxGasPerExec,proto3" json:"max_gas_per_exec,omitempty"`
	// Per-identity rate limit: max shielded executions per epoch per nullifier-identity
	MaxExecsPerIdentityPerEpoch uint64 `protobuf:"varint,5,opt,name=max_execs_per_identity_per_epoch,json=maxExecsPerIdentityPerEpoch,proto3" json:"max_execs_per_identity_per_epoch,omitempty"`
	// Whether encrypted batch mode is enabled (requires TLE DKG ceremony completed)
	EncryptedBatchEnabled bool `protobuf:"varint,6,opt,name=encrypted_batch_enabled,json=encryptedBatchEnabled,proto3" json:"encrypted_batch_enabled,omitempty"`
	// Shield epoch interval in blocks
	ShieldEpochInterval uint64 `protobuf:"varint,7,opt,name=shield_epoch_interval,json=shieldEpochInterval,proto3" json:"shield_epoch_interval,omitempty"`
	// Minimum number of operations in a batch before it executes
	MinBatchSize uint32 `protobuf:"varint,8,opt,name=min_batch_size,json=minBatchSize,proto3" json:"min_batch_size,omitempty"`
	// Maximum epochs an operation can remain pending before force-executing
	MaxPendingEpochs uint32 `protobuf:"varint,9,opt,name=max_pending_epochs,json=maxPendingEpochs,proto3" json:"max_pending_epochs,omitempty"`
	// Maximum number of pending operations in the queue
	MaxPendingQueueSize uint32 `protobuf:"varint,10,opt,name=max_pending_queue_size,json=maxPendingQueueSize,proto3" json:"max_pending_queue_size,omitempty"`
	// Maximum size of encrypted_payload in bytes
	MaxEncryptedPayloadSize uint32 `protobuf:"varint,11,opt,name=max_encrypted_payload_size,json=maxEncryptedPayloadSize,proto3" json:"max_encrypted_payload_size,omitempty"`
	// Maximum operations to execute in a single EndBlocker batch
	MaxOpsPerBatch uint32 `protobuf:"varint,12,opt,name=max_ops_per_batch,json=maxOpsPerBatch,proto3" json:"max_ops_per_batch,omitempty"`
	// Rolling window in shield epochs for tracking validator TLE misses
	TleMissWindow uint64 `protobuf:"varint,13,opt,name=tle_miss_window,json=tleMissWindow,proto3" json:"tle_miss_window,omitempty"`
	// Max misses within window before validator is jailed
	TleMissTolerance uint64 `protobuf:"varint,14,opt,name=tle_miss_tolerance,json=tleMissTolerance,proto3" json:"tle_miss_tolerance,omitempty"`
	// Jail duration in seconds for TLE liveness violations
	TleJailDuration int64 `protobuf:"varint,15,opt,name=tle_jail_duration,json=tleJailDuration,proto3" json:"tle_jail_duration,omitempty"`
	// Minimum bonded validators required to auto-open a DKG ceremony
	MinTleValidators uint32 `protobuf:"varint,16,opt,name=min_tle_validators,json=minTleValidators,proto3" json:"min_tle_validators,omitempty"`
	// Total DKG window in blocks (split: first half = key registration, second half = contributions)
	DkgWindowBlocks uint64 `protobuf:"varint,17,opt,name=dkg_window_blocks,json=dkgWindowBlocks,proto3" json:"dkg_window_blocks,omitempty"`
	// Validator set drift percentage (0-100) that triggers automatic re-keying.
	// e.g. 33 means re-key if >33% of DKG participants are no longer in the bonded set.
	MaxValidatorSetDrift uint32 `protobuf:"varint,18,opt,name=max_validator_set_drift,json=maxValidatorSetDrift,proto3" json:"max_validator_set_drift,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b026cedcad5e804, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetMaxGasPerExec() uint64 {
	if m != nil {
		return m.MaxGasPerExec
	}
	return 0
}

func (m *Params) GetMaxExecsPerIdentityPerEpoch() uint64 {
	if m != nil {
		return m.MaxExecsPerIdentityPerEpoch
	}
	return 0
}

func (m *Params) GetEncryptedBatchEnabled() bool {
	if m != nil {
		return m.EncryptedBatchEnabled
	}
	return false
}

func (m *Params) GetShieldEpochInterval() uint64 {
	if m != nil {
		return m.ShieldEpochInterval
	}
	return 0
}

func (m *Params) GetMinBatchSize() uint32 {
	if m != nil {
		return m.MinBatchSize
	}
	return 0
}

func (m *Params) GetMaxPendingEpochs() uint32 {
	if m != nil {
		return m.MaxPendingEpochs
	}
	return 0
}

func (m *Params) GetMaxPendingQueueSize() uint32 {
	if m != nil {
		return m.MaxPendingQueueSize
	}
	return 0
}

func (m *Params) GetMaxEncryptedPayloadSize() uint32 {
	if m != nil {
		return m.MaxEncryptedPayloadSize
	}
	return 0
}

func (m *Params) GetMaxOpsPerBatch() uint32 {
	if m != nil {
		return m.MaxOpsPerBatch
	}
	return 0
}

func (m *Params) GetTleMissWindow() uint64 {
	if m != nil {
		return m.TleMissWindow
	}
	return 0
}

func (m *Params) GetTleMissTolerance() uint64 {
	if m != nil {
		return m.TleMissTolerance
	}
	return 0
}

func (m *Params) GetTleJailDuration() int64 {
	if m != nil {
		return m.TleJailDuration
	}
	return 0
}

func (m *Params) GetMinTleValidators() uint32 {
	if m != nil {
		return m.MinTleValidators
	}
	return 0
}

func (m *Params) GetDkgWindowBlocks() uint64 {
	if m != nil {
		return m.DkgWindowBlocks
	}
	return 0
}

func (m *Params) GetMaxValidatorSetDrift() uint32 {
	if m != nil {
		return m.MaxValidatorSetDrift
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "sparkdream.shield.v1.Params")
}

func init() { proto.RegisterFile("sparkdream/shield/v1/params.proto", fileDescriptor_7b026cedcad5e804) }

var fileDescriptor_7b026cedcad5e804 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x4e, 0x53, 0x4b,
	0x18, 0xef, 0xb9, 0x70, 0xf9, 0x33, 0x97, 0x52, 0x7a, 0x80, 0xcb, 0xd0, 0x9b, 0x94, 0x5e, 0x35,
	0x5a, 0x89, 0xb6, 0x41, 0x22, 0x0b, 0xdd, 0x35, 0x20, 0xc1, 0xc4, 0x58, 0x0b, 0xd1, 0xc4, 0x85,
	0x93, 0xe9, 0x39, 0x1f, 0xed, 0xd8, 0x73, 0x66, 0x8e, 0x33, 0xd3, 0x72, 0xca, 0x23, 0xb8, 0xf2,
	0x11, 0x7c, 0x04, 0x17, 0x3e, 0x04, 0x4b, 0xe2, 0xca, 0xb8, 0x20, 0x06, 0x16, 0xba, 0xf2, 0x19,
	0xcc, 0xcc, 0x9c, 0x16, 0x16, 0xec, 0xdc, 0x10, 0xce, 0xf7, 0xfb, 0x37, 0xdf, 0x6f, 0xd2, 0x41,
	0xff, 0xab, 0x84, 0xca, 0x5e, 0x28, 0x81, 0xc6, 0x75, 0xd5, 0x65, 0x10, 0x85, 0xf5, 0xc1, 0x46,
	0x3d, 0xa1, 0x92, 0xc6, 0xaa, 0x96, 0x48, 0xa1, 0x85, 0xbf, 0x74, 0x49, 0xa9, 0x39, 0x4a, 0x6d,
	0xb0, 0x51, 0x2a, 0xd2, 0x98, 0x71, 0x51, 0xb7, 0x7f, 0x1d, 0xb1, 0xb4, 0x1a, 0x08, 0x15, 0x0b,
	0x45, 0xec, 0x57, 0xdd, 0x7d, 0x64, 0xd0, 0x52, 0x47, 0x74, 0x84, 0x9b, 0x9b, 0xff, 0xdc, 0xf4,
	0xc6, 0xaf, 0x69, 0x34, 0xd5, 0xb4, 0x51, 0x3e, 0x46, 0xd3, 0xc0, 0x69, 0x3b, 0x82, 0x10, 0x7b,
	0x15, 0xaf, 0x3a, 0xd3, 0x1a, 0x7d, 0xfa, 0x80, 0x16, 0x63, 0x9a, 0x92, 0xc3, 0x3e, 0x0f, 0x19,
	0xef, 0x90, 0x04, 0x24, 0x09, 0xe9, 0x10, 0xff, 0x55, 0xf1, 0xaa, 0xb3, 0x8d, 0xad, 0x93, 0xb3,
	0xb5, 0xdc, 0xb7, 0xb3, 0xb5, 0x65, 0x97, 0xa6, 0xc2, 0x5e, 0x8d, 0x89, 0x7a, 0x4c, 0x75, 0xb7,
	0xb6, 0xc7, 0xf5, 0x97, 0xcf, 0xf7, 0xaf, 0x07, 0x5a, 0x0b, 0x31, 0x4d, 0x9f, 0x38, 0xc7, 0x26,
	0xc8, 0x6d, 0x3a, 0xf4, 0xdf, 0xa0, 0x42, 0xcc, 0x38, 0xe9, 0x50, 0x45, 0x24, 0x28, 0x90, 0x03,
	0xc0, 0x13, 0x7f, 0x14, 0x91, 0x8f, 0x19, 0xdf, 0xa5, 0xaa, 0xe5, 0xcc, 0xfc, 0x3b, 0xc8, 0x64,
	0x5a, 0x7f, 0xb3, 0x02, 0xa4, 0x10, 0xe0, 0xc9, 0x8a, 0x57, 0x9d, 0x6c, 0xe5, 0x63, 0x9a, 0xee,
	0x52, 0xd5, 0x04, 0xb9, 0x93, 0x42, 0xe0, 0xef, 0xa0, 0x8a, 0x21, 0x1a, 0x82, 0xa3, 0xb2, 0x10,
	0xb8, 0x66, 0x7a, 0xe8, 0x74, 0x89, 0x08, 0xba, 0xf8, 0x6f, 0x2b, 0xfc, 0x2f, 0xa6, 0xa9, 0x91,
	0x18, 0xe9, 0x5e, 0x46, 0x32, 0x2e, 0x86, 0xe2, 0x6f, 0xa1, 0x15, 0xe0, 0x81, 0x1c, 0x26, 0x1a,
	0x42, 0xd2, 0xa6, 0x3a, 0xe8, 0x92, 0x51, 0xc1, 0x53, 0xb6, 0xe0, 0xe5, 0x31, 0xdc, 0x30, 0xe8,
	0x4e, 0x56, 0xf7, 0x03, 0xb4, 0xec, 0x2e, 0xd9, 0x45, 0x11, 0xc6, 0x35, 0xc8, 0x01, 0x8d, 0xf0,
	0xb4, 0xcd, 0x5c, 0x74, 0xa0, 0xcd, 0xd8, 0xcb, 0x20, 0xff, 0x16, 0x9a, 0x37, 0xdd, 0xb9, 0x14,
	0xc5, 0x8e, 0x01, 0xcf, 0x54, 0xbc, 0x6a, 0xbe, 0x35, 0x17, 0x33, 0x6e, 0xcd, 0xf7, 0xd9, 0x31,
	0xf8, 0xf7, 0x90, 0x6f, 0x16, 0x4b, 0xc0, 0x5d, 0xa4, 0xb5, 0x57, 0x78, 0xd6, 0x32, 0x4d, 0x37,
	0x4d, 0x07, 0x58, 0x6b, 0xe5, 0x6f, 0xa2, 0x7f, 0xaf, 0xb2, 0xdf, 0xf5, 0xa1, 0x0f, 0xce, 0x1b,
	0x59, 0xc5, 0xe2, 0xa5, 0xe2, 0x85, 0xc1, 0x6c, 0xc4, 0x63, 0x54, 0xb2, 0xdd, 0x8d, 0x17, 0x4f,
	0xe8, 0x30, 0x12, 0x34, 0x74, 0xc2, 0x7f, 0xac, 0x70, 0xc5, 0xb4, 0x36, 0x22, 0x34, 0x1d, 0x6e,
	0xc5, 0x77, 0x51, 0xd1, 0x88, 0x45, 0xe2, 0x6a, 0xb7, 0xdb, 0xe0, 0x39, 0xab, 0x99, 0x8f, 0x69,
	0xfa, 0x3c, 0x31, 0x3d, 0xdb, 0x75, 0xfc, 0xdb, 0xa8, 0xa0, 0x23, 0x20, 0x31, 0x53, 0x8a, 0x1c,
	0x31, 0x1e, 0x8a, 0x23, 0x9c, 0x77, 0x77, 0xa9, 0x23, 0x78, 0xc6, 0x94, 0x7a, 0x65, 0x87, 0x66,
	0xe5, 0x31, 0x4f, 0x8b, 0x08, 0x24, 0xe5, 0x01, 0xe0, 0x79, 0x4b, 0x5d, 0xc8, 0xa8, 0x07, 0xa3,
	0xb9, 0xbf, 0x8e, 0x8a, 0x86, 0xfd, 0x96, 0xb2, 0x88, 0x84, 0x7d, 0x49, 0x35, 0x13, 0x1c, 0x17,
	0x2a, 0x5e, 0x75, 0xa2, 0x65, 0xe2, 0x9e, 0x52, 0x16, 0x6d, 0x67, 0x63, 0x5b, 0x26, 0xe3, 0xc4,
	0xf0, 0x07, 0x34, 0x62, 0x21, 0xd5, 0x42, 0x2a, 0xbc, 0x90, 0x95, 0xc9, 0xf8, 0x41, 0x04, 0x2f,
	0xc7, 0x73, 0xe3, 0x1c, 0xf6, 0x3a, 0xd9, 0x51, 0x49, 0x3b, 0x12, 0x41, 0x4f, 0xe1, 0xa2, 0x3d,
	0x46, 0x21, 0xec, 0x75, 0xdc, 0x69, 0x1b, 0x76, 0xec, 0x3f, 0x44, 0xa6, 0xa1, 0x4b, 0x57, 0xa2,
	0x40, 0x93, 0x50, 0xb2, 0x43, 0x8d, 0x7d, 0x6b, 0xbf, 0x14, 0xd3, 0x74, 0xec, 0xbd, 0x0f, 0x7a,
	0xdb, 0x60, 0x8f, 0x6e, 0xfe, 0xfc, 0xb8, 0xe6, 0xbd, 0xff, 0xf1, 0x69, 0xbd, 0x74, 0xe5, 0x45,
	0x49, 0x47, 0x6f, 0x8a, 0xfb, 0x95, 0x37, 0x36, 0x4f, 0xce, 0xcb, 0xde, 0xe9, 0x79, 0xd9, 0xfb,
	0x7e, 0x5e, 0xf6, 0x3e, 0x5c, 0x94, 0x73, 0xa7, 0x17, 0xe5, 0xdc, 0xd7, 0x8b, 0x72, 0xee, 0xf5,
	0xea, 0x75, 0x2a, 0x3d, 0x4c, 0x40, 0xb5, 0xa7, 0xec, 0x63, 0xb1, 0xf9, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xf9, 0xae, 0xc3, 0xb7, 0xab, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Enabled != that1.Enabled {
		return false
	}
	if !this.MaxFundingPerDay.Equal(that1.MaxFundingPerDay) {
		return false
	}
	if !this.MinGasReserve.Equal(that1.MinGasReserve) {
		return false
	}
	if this.MaxGasPerExec != that1.MaxGasPerExec {
		return false
	}
	if this.MaxExecsPerIdentityPerEpoch != that1.MaxExecsPerIdentityPerEpoch {
		return false
	}
	if this.EncryptedBatchEnabled != that1.EncryptedBatchEnabled {
		return false
	}
	if this.ShieldEpochInterval != that1.ShieldEpochInterval {
		return false
	}
	if this.MinBatchSize != that1.MinBatchSize {
		return false
	}
	if this.MaxPendingEpochs != that1.MaxPendingEpochs {
		return false
	}
	if this.MaxPendingQueueSize != that1.MaxPendingQueueSize {
		return false
	}
	if this.MaxEncryptedPayloadSize != that1.MaxEncryptedPayloadSize {
		return false
	}
	if this.MaxOpsPerBatch != that1.MaxOpsPerBatch {
		return false
	}
	if this.TleMissWindow != that1.TleMissWindow {
		return false
	}
	if this.TleMissTolerance != that1.TleMissTolerance {
		return false
	}
	if this.TleJailDuration != that1.TleJailDuration {
		return false
	}
	if this.MinTleValidators != that1.MinTleValidators {
		return false
	}
	if this.DkgWindowBlocks != that1.DkgWindowBlocks {
		return false
	}
	if this.MaxValidatorSetDrift != that1.MaxValidatorSetDrift {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxValidatorSetDrift != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxValidatorSetDrift))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.DkgWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DkgWindowBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.MinTleValidators != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinTleValidators))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.TleJailDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TleJailDuration))
		i--
		dAtA[i] = 0x78
	}
	if m.TleMissTolerance != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TleMissTolerance))
		i--
		dAtA[i] = 0x70
	}
	if m.TleMissWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TleMissWindow))
		i--
		dAtA[i] = 0x68
	}
	if m.MaxOpsPerBatch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOpsPerBatch))
		i--
		dAtA[i] = 0x60
	}
	if m.MaxEncryptedPayloadSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxEncryptedPayloadSize))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxPendingQueueSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingQueueSize))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxPendingEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingEpochs))
		i--
		dAtA[i] = 0x48
	}
	if m.MinBatchSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinBatchSize))
		i--
		dAtA[i] = 0x40
	}
	if m.ShieldEpochInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ShieldEpochInterval))
		i--
		dAtA[i] = 0x38
	}
	if m.EncryptedBatchEnabled {
		i--
		if m.EncryptedBatchEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.MaxExecsPerIdentityPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxExecsPerIdentityPerEpoch))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxGasPerExec != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxGasPerExec))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.MinGasReserve.Size()
		i -= size
		if _, err := m.MinGasReserve.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MaxFundingPerDay.Size()
		i -= size
		if _, err := m.MaxFundingPerDay.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = m.MaxFundingPerDay.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinGasReserve.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxGasPerExec != 0 {
		n += 1 + sovParams(uint64(m.MaxGasPerExec))
	}
	if m.MaxExecsPerIdentityPerEpoch != 0 {
		n += 1 + sovParams(uint64(m.MaxExecsPerIdentityPerEpoch))
	}
	if m.EncryptedBatchEnabled {
		n += 2
	}
	if m.ShieldEpochInterval != 0 {
		n += 1 + sovParams(uint64(m.ShieldEpochInterval))
	}
	if m.MinBatchSize != 0 {
		n += 1 + sovParams(uint64(m.MinBatchSize))
	}
	if m.MaxPendingEpochs != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingEpochs))
	}
	if m.MaxPendingQueueSize != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingQueueSize))
	}
	if m.MaxEncryptedPayloadSize != 0 {
		n += 1 + sovParams(uint64(m.MaxEncryptedPayloadSize))
	}
	if m.MaxOpsPerBatch != 0 {
		n += 1 + sovParams(uint64(m.MaxOpsPerBatch))
	}
	if m.TleMissWindow != 0 {
		n += 1 + sovParams(uint64(m.TleMissWindow))
	}
	if m.TleMissTolerance != 0 {
		n += 1 + sovParams(uint64(m.TleMissTolerance))
	}
	if m.TleJailDuration != 0 {
		n += 1 + sovParams(uint64(m.TleJailDuration))
	}
	if m.MinTleValidators != 0 {
		n += 2 + sovParams(uint64(m.MinTleValidators))
	}
	if m.DkgWindowBlocks != 0 {
		n += 2 + sovParams(uint64(m.DkgWindowBlocks))
	}
	if m.MaxValidatorSetDrift != 0 {
		n += 2 + sovParams(uint64(m.MaxValidatorSetDrift))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFundingPerDay", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxFundingPerDay.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasReserve", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGasReserve.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasPerExec", wireType)
			}
			m.MaxGasPerExec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasPerExec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxExecsPerIdentityPerEpoch", wireType)
			}
			m.MaxExecsPerIdentityPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxExecsPerIdentityPerEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedBatchEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EncryptedBatchEnabled = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShieldEpochInterval", wireType)
			}
			m.ShieldEpochInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShieldEpochInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBatchSize", wireType)
			}
			m.MinBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinBatchSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingEpochs", wireType)
			}
			m.MaxPendingEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingEpochs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingQueueSize", wireType)
			}
			m.MaxPendingQueueSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingQueueSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEncryptedPayloadSize", wireType)
			}
			m.MaxEncryptedPayloadSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEncryptedPayloadSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOpsPerBatch", wireType)
			}
			m.MaxOpsPerBatch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOpsPerBatch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TleMissWindow", wireType)
			}
			m.TleMissWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TleMissWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TleMissTolerance", wireType)
			}
			m.TleMissTolerance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TleMissTolerance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TleJailDuration", wireType)
			}
			m.TleJailDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TleJailDuration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTleValidators", wireType)
			}
			m.MinTleValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinTleValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkgWindowBlocks", wireType)
			}
			m.DkgWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DkgWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValidatorSetDrift", wireType)
			}
			m.MaxValidatorSetDrift = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValidatorSetDrift |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
