package types

// DONTCOVER

import (
	"cosmossdk.io/errors"
)

// x/artifact module sentinel errors
var (
	ErrInvalidSigner             = errors.Register(ModuleName, 1100, "expected gov account as only signer for proposal message")
	ErrClassNotFound             = errors.Register(ModuleName, 1101, "class not found")
	ErrTokenNotFound             = errors.Register(ModuleName, 1102, "token not found")
	ErrNotClassOwner             = errors.Register(ModuleName, 1103, "signer is not the class owner")
	ErrNotTokenOwner             = errors.Register(ModuleName, 1104, "signer is not the token owner")
	ErrNotMinter                 = errors.Register(ModuleName, 1105, "signer is not a minter of this class")
	ErrInsufficientTrust         = errors.Register(ModuleName, 1106, "creator is not a member at the required trust level nor a council body")
	ErrTooManyClasses            = errors.Register(ModuleName, 1107, "maximum classes per creator reached")
	ErrInvalidFlags              = errors.Register(ModuleName, 1108, "invalid class flags")
	ErrSupplyExceeded            = errors.Register(ModuleName, 1109, "max supply exceeded")
	ErrSupplyIncrease            = errors.Register(ModuleName, 1110, "max supply can only be lowered")
	ErrMintingClosed             = errors.Register(ModuleName, 1111, "minting is closed for this class")
	ErrMintWindow                = errors.Register(ModuleName, 1112, "public mint is not open")
	ErrPerAddressLimit           = errors.Register(ModuleName, 1113, "per-address public mint limit reached")
	ErrPriceExceeded             = errors.Register(ModuleName, 1114, "current price exceeds max price")
	ErrMetadataFrozen            = errors.Register(ModuleName, 1115, "metadata is frozen")
	ErrNotTransferable           = errors.Register(ModuleName, 1116, "class is not transferable")
	ErrTokenLocked               = errors.Register(ModuleName, 1117, "token is locked")
	ErrInvalidRecipient          = errors.Register(ModuleName, 1118, "invalid recipient")
	ErrPendingNotFound           = errors.Register(ModuleName, 1119, "pending item not found")
	ErrPendingExpired            = errors.Register(ModuleName, 1120, "pending item expired")
	ErrInboxFull                 = errors.Register(ModuleName, 1121, "recipient inbox is full")
	ErrListingNotFound           = errors.Register(ModuleName, 1122, "listing not found")
	ErrListingExpired            = errors.Register(ModuleName, 1123, "listing expired")
	ErrListingChanged            = errors.Register(ModuleName, 1124, "listing price or nonce changed")
	ErrMetadataChanged           = errors.Register(ModuleName, 1125, "metadata hash mismatch")
	ErrMarketDisabled            = errors.Register(ModuleName, 1126, "market is disabled")
	ErrRoyaltyTooHigh            = errors.Register(ModuleName, 1127, "royalty exceeds maximum")
	ErrRoyaltyIncrease           = errors.Register(ModuleName, 1128, "royalty can only be lowered")
	ErrInvalidDenom              = errors.Register(ModuleName, 1129, "invalid denom")
	ErrDreamNotAccepted          = errors.Register(ModuleName, 1130, "DREAM is not accepted")
	ErrInvalidMetadata           = errors.Register(ModuleName, 1131, "invalid metadata")
	ErrInlineData                = errors.Register(ModuleName, 1132, "data URIs are not allowed")
	ErrContentLicenseNotAccepted = errors.Register(ModuleName, 1133, "content license must be accepted")
	ErrContentHidden             = errors.Register(ModuleName, 1134, "content is hidden")
	ErrClassNotEmpty             = errors.Register(ModuleName, 1135, "class still has live or reserved tokens")
	ErrNotRevocable              = errors.Register(ModuleName, 1136, "class does not let the issuer burn tokens")
	ErrInvalidBatch              = errors.Register(ModuleName, 1137, "invalid batch")
	ErrPendingOwnerNotFound      = errors.Register(ModuleName, 1138, "no open class ownership proposal")
	ErrNotAuthorized             = errors.Register(ModuleName, 1139, "not authorized")
	ErrHideNotFound              = errors.Register(ModuleName, 1140, "hide record not found")
	ErrAlreadyHidden             = errors.Register(ModuleName, 1141, "target already has an open hide record")
	ErrSentinelRateLimit         = errors.Register(ModuleName, 1142, "sentinel daily hide limit reached")
	ErrNotAppellant              = errors.Register(ModuleName, 1143, "signer may not appeal this hide")
	ErrAppealWindowClosed        = errors.Register(ModuleName, 1144, "appeal is not possible in the current state")
	ErrInvalidParams             = errors.Register(ModuleName, 1145, "invalid params")
	ErrInsufficientFunds         = errors.Register(ModuleName, 1146, "insufficient funds")
	ErrSentinelCooldown          = errors.Register(ModuleName, 1147, "sentinel is in overturn cooldown")
	ErrInsufficientBond          = errors.Register(ModuleName, 1148, "insufficient available sentinel bond")
	ErrInvalidReason             = errors.Register(ModuleName, 1149, "invalid moderation reason")
	ErrHolderBurnNotAllowed      = errors.Register(ModuleName, 1150, "class does not let the holder burn tokens")
	ErrInvalidRoyaltySplit       = errors.Register(ModuleName, 1151, "invalid royalty split")
)
