package types

// Event types (docs/x-artifact-spec.md §10).
const (
	EventClassCreated         = "artifact_class_created"
	EventClassUpdated         = "artifact_class_updated"
	EventClassMetadataFrozen  = "artifact_class_metadata_frozen"
	EventMintPolicySet        = "artifact_mint_policy_set"
	EventMintersSet           = "artifact_minters_set"
	EventMaxSupplySet         = "artifact_max_supply_set"
	EventMintingClosed        = "artifact_minting_closed"
	EventClassOwnerProposed   = "artifact_class_owner_proposed"
	EventClassOwnerAccepted   = "artifact_class_owner_accepted"
	EventClassOwnerCancelled  = "artifact_class_owner_cancelled"
	EventClassOwnerExpired    = "artifact_class_owner_expired"
	EventClassDeleted         = "artifact_class_deleted"
	EventMinted               = "artifact_minted"
	EventMintPending          = "artifact_mint_pending"
	EventPublicMinted         = "artifact_public_minted"
	EventTransferred          = "artifact_transferred"
	EventTransferPending      = "artifact_transfer_pending"
	EventPendingResolved      = "artifact_pending_resolved"
	EventReceivePolicySet     = "artifact_receive_policy_set"
	EventBurned               = "artifact_burned"
	EventRevoked              = "artifact_revoked"
	EventTokenUpdated         = "artifact_token_updated"
	EventTokenMetadataFrozen  = "artifact_token_metadata_frozen"
	EventListed               = "artifact_listed"
	EventListingUpdated       = "artifact_listing_updated"
	EventDelisted             = "artifact_delisted"
	EventSold                 = "artifact_sold"
	EventHidden               = "artifact_hidden"
	EventUnhidden             = "artifact_unhidden"
	EventHideAppealed         = "artifact_hide_appealed"
	EventHideResolved         = "artifact_hide_resolved"
	EventMetadataScrubbed     = "artifact_metadata_scrubbed"
	EventClassDrainProgress   = "artifact_class_drain_progress"
	EventExpiryError          = "artifact_expiry_error"
	EventOperationalParamsSet = "artifact_operational_params_updated"
)
