package types

// Event types for the x/vote module.
const (
	EventVoterRegistered             = "voter_registered"
	EventVoterDeactivated            = "voter_deactivated"
	EventVoterKeyRotated             = "voter_key_rotated"
	EventProposalCreated             = "proposal_created"
	EventVoteCast                    = "vote_cast"
	EventSealedVoteCast              = "sealed_vote_cast"
	EventSealedVoteRevealed          = "sealed_vote_revealed"
	EventProposalCancelled           = "proposal_cancelled"
	EventProposalFinalized           = "proposal_finalized"
	EventProposalExecutionFailed     = "proposal_execution_failed"
	EventEpochDecryptionKeyAvail     = "epoch_decryption_key_available"
	EventTLEKeyUnavailable           = "tle_key_unavailable"
	EventTLEShareRegistered          = "tle_share_registered"
	EventDecryptionShareSubmit       = "decryption_share_submitted"
	EventSRSStored                   = "srs_stored"
	EventTLEValidatorMissed          = "tle_validator_missed"
	EventTLEEpochParticipation       = "tle_epoch_participation"
	EventTLEValidatorFlaggedInactive = "tle_validator_flagged_inactive"
	EventTLEValidatorRecovered       = "tle_validator_recovered"
	EventTLEValidatorJailed          = "tle_validator_jailed"

	AttributeProposalID      = "proposal_id"
	AttributeVoter           = "voter"
	AttributeValidator       = "validator"
	AttributeNullifier       = "nullifier"
	AttributeVoteOption      = "vote_option"
	AttributeOutcome         = "outcome"
	AttributeVisibility      = "visibility"
	AttributeReason          = "reason"
	AttributeEpoch           = "epoch"
	AttributeStatus          = "status"
	AttributeShareIndex      = "share_index"
	AttributeVoterCount      = "voter_count"
	AttributeMerkleRoot      = "merkle_root"
	AttributeTotalVotes      = "total_votes"
	AttributeProposer        = "proposer"
	AttributeDeposit         = "deposit"
	AttributeVotingStart     = "voting_start"
	AttributeVotingEnd       = "voting_end"
	AttributeRegisteredCount = "registered_count"
	AttributeSubmittedCount  = "submitted_count"
	AttributeMissedCount     = "missed_count"
)
