// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/reveal/v1/types.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ContributionStatus defines the lifecycle status of a contribution.
type ContributionStatus int32

const (
	ContributionStatus_CONTRIBUTION_STATUS_PROPOSED    ContributionStatus = 0
	ContributionStatus_CONTRIBUTION_STATUS_IN_PROGRESS ContributionStatus = 1
	ContributionStatus_CONTRIBUTION_STATUS_COMPLETED   ContributionStatus = 2
	ContributionStatus_CONTRIBUTION_STATUS_CANCELLED   ContributionStatus = 3
)

var ContributionStatus_name = map[int32]string{
	0: "CONTRIBUTION_STATUS_PROPOSED",
	1: "CONTRIBUTION_STATUS_IN_PROGRESS",
	2: "CONTRIBUTION_STATUS_COMPLETED",
	3: "CONTRIBUTION_STATUS_CANCELLED",
}

var ContributionStatus_value = map[string]int32{
	"CONTRIBUTION_STATUS_PROPOSED":    0,
	"CONTRIBUTION_STATUS_IN_PROGRESS": 1,
	"CONTRIBUTION_STATUS_COMPLETED":   2,
	"CONTRIBUTION_STATUS_CANCELLED":   3,
}

func (x ContributionStatus) String() string {
	return proto.EnumName(ContributionStatus_name, int32(x))
}

func (ContributionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{0}
}

// TrancheStatus defines the lifecycle status of a tranche.
type TrancheStatus int32

const (
	TrancheStatus_TRANCHE_STATUS_LOCKED    TrancheStatus = 0
	TrancheStatus_TRANCHE_STATUS_STAKING   TrancheStatus = 1
	TrancheStatus_TRANCHE_STATUS_BACKED    TrancheStatus = 2
	TrancheStatus_TRANCHE_STATUS_REVEALED  TrancheStatus = 3
	TrancheStatus_TRANCHE_STATUS_VERIFIED  TrancheStatus = 4
	TrancheStatus_TRANCHE_STATUS_DISPUTED  TrancheStatus = 5
	TrancheStatus_TRANCHE_STATUS_CANCELLED TrancheStatus = 6
	TrancheStatus_TRANCHE_STATUS_FAILED    TrancheStatus = 7
)

var TrancheStatus_name = map[int32]string{
	0: "TRANCHE_STATUS_LOCKED",
	1: "TRANCHE_STATUS_STAKING",
	2: "TRANCHE_STATUS_BACKED",
	3: "TRANCHE_STATUS_REVEALED",
	4: "TRANCHE_STATUS_VERIFIED",
	5: "TRANCHE_STATUS_DISPUTED",
	6: "TRANCHE_STATUS_CANCELLED",
	7: "TRANCHE_STATUS_FAILED",
}

var TrancheStatus_value = map[string]int32{
	"TRANCHE_STATUS_LOCKED":    0,
	"TRANCHE_STATUS_STAKING":   1,
	"TRANCHE_STATUS_BACKED":    2,
	"TRANCHE_STATUS_REVEALED":  3,
	"TRANCHE_STATUS_VERIFIED":  4,
	"TRANCHE_STATUS_DISPUTED":  5,
	"TRANCHE_STATUS_CANCELLED": 6,
	"TRANCHE_STATUS_FAILED":    7,
}

func (x TrancheStatus) String() string {
	return proto.EnumName(TrancheStatus_name, int32(x))
}

func (TrancheStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{1}
}

// DisputeVerdict defines the three-way outcome of a council dispute resolution.
type DisputeVerdict int32

const (
	DisputeVerdict_DISPUTE_VERDICT_UNSPECIFIED DisputeVerdict = 0
	DisputeVerdict_DISPUTE_VERDICT_ACCEPT      DisputeVerdict = 1
	DisputeVerdict_DISPUTE_VERDICT_IMPROVE     DisputeVerdict = 2
	DisputeVerdict_DISPUTE_VERDICT_REJECT      DisputeVerdict = 3
)

var DisputeVerdict_name = map[int32]string{
	0: "DISPUTE_VERDICT_UNSPECIFIED",
	1: "DISPUTE_VERDICT_ACCEPT",
	2: "DISPUTE_VERDICT_IMPROVE",
	3: "DISPUTE_VERDICT_REJECT",
}

var DisputeVerdict_value = map[string]int32{
	"DISPUTE_VERDICT_UNSPECIFIED": 0,
	"DISPUTE_VERDICT_ACCEPT":      1,
	"DISPUTE_VERDICT_IMPROVE":     2,
	"DISPUTE_VERDICT_REJECT":      3,
}

func (x DisputeVerdict) String() string {
	return proto.EnumName(DisputeVerdict_name, int32(x))
}

func (DisputeVerdict) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{2}
}

// Contribution represents a body of existing code being progressively revealed.
type Contribution struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Contributor    string                `protobuf:"bytes,2,opt,name=contributor,proto3" json:"contributor,omitempty"`
	ProjectName    string                `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description    string                `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tranches       []RevealTranche       `protobuf:"bytes,5,rep,name=tranches,proto3" json:"tranches"`
	CurrentTranche uint32                `protobuf:"varint,6,opt,name=current_tranche,json=currentTranche,proto3" json:"current_tranche,omitempty"`
	TotalValuation cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=total_valuation,json=totalValuation,proto3,customtype=cosmossdk.io/math.Int" json:"total_valuation"`
	// Bond posted by contributor at proposal time; slashed on failure to reveal
	BondAmount cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=bond_amount,json=bondAmount,proto3,customtype=cosmossdk.io/math.Int" json:"bond_amount"`
	// Remaining bond after any partial slashes (starts equal to bond_amount)
	BondRemaining         cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=bond_remaining,json=bondRemaining,proto3,customtype=cosmossdk.io/math.Int" json:"bond_remaining"`
	InitialLicense        string                `protobuf:"bytes,10,opt,name=initial_license,json=initialLicense,proto3" json:"initial_license,omitempty"`
	FinalLicense          string                `protobuf:"bytes,11,opt,name=final_license,json=finalLicense,proto3" json:"final_license,omitempty"`
	TransitionedToProject bool                  `protobuf:"varint,12,opt,name=transitioned_to_project,json=transitionedToProject,proto3" json:"transitioned_to_project,omitempty"`
	ProjectId             uint64                `protobuf:"varint,13,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status                ContributionStatus    `protobuf:"varint,14,opt,name=status,proto3,enum=sparkdream.reveal.v1.ContributionStatus" json:"status,omitempty"`
	CouncilId             uint64                `protobuf:"varint,15,opt,name=council_id,json=councilId,proto3" json:"council_id,omitempty"`
	ApprovedBy            string                `protobuf:"bytes,16,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt            int64                 `protobuf:"varint,17,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	CreatedAt             int64                 `protobuf:"varint,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// DREAM held back from tranche payouts until all tranches complete
	HoldbackAmount cosmossdk_io_math.Int `protobuf:"bytes,19,opt,name=holdback_amount,json=holdbackAmount,proto3,customtype=cosmossdk.io/math.Int" json:"holdback_amount"`
	// Epoch at which a rejected contributor may re-propose (0 if not rejected)
	ProposalEligibleAt int64 `protobuf:"varint,20,opt,name=proposal_eligible_at,json=proposalEligibleAt,proto3" json:"proposal_eligible_at,omitempty"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{0}
}
func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return m.Size()
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contribution) GetContributor() string {
	if m != nil {
		return m.Contributor
	}
	return ""
}

func (m *Contribution) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Contribution) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Contribution) GetTranches() []RevealTranche {
	if m != nil {
		return m.Tranches
	}
	return nil
}

func (m *Contribution) GetCurrentTranche() uint32 {
	if m != nil {
		return m.CurrentTranche
	}
	return 0
}

func (m *Contribution) GetInitialLicense() string {
	if m != nil {
		return m.InitialLicense
	}
	return ""
}

func (m *Contribution) GetFinalLicense() string {
	if m != nil {
		return m.FinalLicense
	}
	return ""
}

func (m *Contribution) GetTransitionedToProject() bool {
	if m != nil {
		return m.TransitionedToProject
	}
	return false
}

func (m *Contribution) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Contribution) GetStatus() ContributionStatus {
	if m != nil {
		return m.Status
	}
	return ContributionStatus_CONTRIBUTION_STATUS_PROPOSED
}

func (m *Contribution) GetCouncilId() uint64 {
	if m != nil {
		return m.CouncilId
	}
	return 0
}

func (m *Contribution) GetApprovedBy() string {
	if m != nil {
		return m.ApprovedBy
	}
	return ""
}

func (m *Contribution) GetApprovedAt() int64 {
	if m != nil {
		return m.ApprovedAt
	}
	return 0
}

func (m *Contribution) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Contribution) GetProposalEligibleAt() int64 {
	if m != nil {
		return m.ProposalEligibleAt
	}
	return 0
}

// RevealTranche represents a discrete chunk of code to be backed, revealed, and verified.
type RevealTranche struct {
	Id          uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Components  []string `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	// DREAM that must be staked to back this tranche; also the mint amount on payout
	// Invariant: sum(stake_threshold) across all tranches == contribution.total_valuation
	StakeThreshold       cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=stake_threshold,json=stakeThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"stake_threshold"`
	DreamStaked          cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=dream_staked,json=dreamStaked,proto3,customtype=cosmossdk.io/math.Int" json:"dream_staked"`
	PreviewUri           string                `protobuf:"bytes,7,opt,name=preview_uri,json=previewUri,proto3" json:"preview_uri,omitempty"`
	CodeUri              string                `protobuf:"bytes,8,opt,name=code_uri,json=codeUri,proto3" json:"code_uri,omitempty"`
	DocsUri              string                `protobuf:"bytes,9,opt,name=docs_uri,json=docsUri,proto3" json:"docs_uri,omitempty"`
	CommitHash           string                `protobuf:"bytes,10,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	StakeDeadline        int64                 `protobuf:"varint,11,opt,name=stake_deadline,json=stakeDeadline,proto3" json:"stake_deadline,omitempty"`
	RevealDeadline       int64                 `protobuf:"varint,12,opt,name=reveal_deadline,json=revealDeadline,proto3" json:"reveal_deadline,omitempty"`
	VerificationDeadline int64                 `protobuf:"varint,13,opt,name=verification_deadline,json=verificationDeadline,proto3" json:"verification_deadline,omitempty"`
	Status               TrancheStatus         `protobuf:"varint,14,opt,name=status,proto3,enum=sparkdream.reveal.v1.TrancheStatus" json:"status,omitempty"`
	BackedAt             int64                 `protobuf:"varint,15,opt,name=backed_at,json=backedAt,proto3" json:"backed_at,omitempty"`
	RevealedAt           int64                 `protobuf:"varint,16,opt,name=revealed_at,json=revealedAt,proto3" json:"revealed_at,omitempty"`
	VerifiedAt           int64                 `protobuf:"varint,17,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
}

func (m *RevealTranche) Reset()         { *m = RevealTranche{} }
func (m *RevealTranche) String() string { return proto.CompactTextString(m) }
func (*RevealTranche) ProtoMessage()    {}
func (*RevealTranche) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{1}
}
func (m *RevealTranche) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevealTranche) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevealTranche.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevealTranche) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevealTranche.Merge(m, src)
}
func (m *RevealTranche) XXX_Size() int {
	return m.Size()
}
func (m *RevealTranche) XXX_DiscardUnknown() {
	xxx_messageInfo_RevealTranche.DiscardUnknown(m)
}

var xxx_messageInfo_RevealTranche proto.InternalMessageInfo

func (m *RevealTranche) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RevealTranche) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RevealTranche) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RevealTranche) GetComponents() []string {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *RevealTranche) GetPreviewUri() string {
	if m != nil {
		return m.PreviewUri
	}
	return ""
}

func (m *RevealTranche) GetCodeUri() string {
	if m != nil {
		return m.CodeUri
	}
	return ""
}

func (m *RevealTranche) GetDocsUri() string {
	if m != nil {
		return m.DocsUri
	}
	return ""
}

func (m *RevealTranche) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *RevealTranche) GetStakeDeadline() int64 {
	if m != nil {
		return m.StakeDeadline
	}
	return 0
}

func (m *RevealTranche) GetRevealDeadline() int64 {
	if m != nil {
		return m.RevealDeadline
	}
	return 0
}

func (m *RevealTranche) GetVerificationDeadline() int64 {
	if m != nil {
		return m.VerificationDeadline
	}
	return 0
}

func (m *RevealTranche) GetStatus() TrancheStatus {
	if m != nil {
		return m.Status
	}
	return TrancheStatus_TRANCHE_STATUS_LOCKED
}

func (m *RevealTranche) GetBackedAt() int64 {
	if m != nil {
		return m.BackedAt
	}
	return 0
}

func (m *RevealTranche) GetRevealedAt() int64 {
	if m != nil {
		return m.RevealedAt
	}
	return 0
}

func (m *RevealTranche) GetVerifiedAt() int64 {
	if m != nil {
		return m.VerifiedAt
	}
	return 0
}

// RevealStake represents a community member's conviction stake toward a tranche.
type RevealStake struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Staker         string                `protobuf:"bytes,2,opt,name=staker,proto3" json:"staker,omitempty"`
	ContributionId uint64                `protobuf:"varint,3,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	TrancheId      uint32                `protobuf:"varint,4,opt,name=tranche_id,json=trancheId,proto3" json:"tranche_id,omitempty"`
	Amount         cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	StakedAt       int64                 `protobuf:"varint,6,opt,name=staked_at,json=stakedAt,proto3" json:"staked_at,omitempty"`
}

func (m *RevealStake) Reset()         { *m = RevealStake{} }
func (m *RevealStake) String() string { return proto.CompactTextString(m) }
func (*RevealStake) ProtoMessage()    {}
func (*RevealStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{2}
}
func (m *RevealStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevealStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevealStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevealStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevealStake.Merge(m, src)
}
func (m *RevealStake) XXX_Size() int {
	return m.Size()
}
func (m *RevealStake) XXX_DiscardUnknown() {
	xxx_messageInfo_RevealStake.DiscardUnknown(m)
}

var xxx_messageInfo_RevealStake proto.InternalMessageInfo

func (m *RevealStake) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RevealStake) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *RevealStake) GetContributionId() uint64 {
	if m != nil {
		return m.ContributionId
	}
	return 0
}

func (m *RevealStake) GetTrancheId() uint32 {
	if m != nil {
		return m.TrancheId
	}
	return 0
}

func (m *RevealStake) GetStakedAt() int64 {
	if m != nil {
		return m.StakedAt
	}
	return 0
}

// VerificationVote represents a staker's vote on revealed code quality.
type VerificationVote struct {
	Voter          string                `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	ContributionId uint64                `protobuf:"varint,2,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	TrancheId      uint32                `protobuf:"varint,3,opt,name=tranche_id,json=trancheId,proto3" json:"tranche_id,omitempty"`
	ValueConfirmed bool                  `protobuf:"varint,4,opt,name=value_confirmed,json=valueConfirmed,proto3" json:"value_confirmed,omitempty"`
	QualityRating  uint32                `protobuf:"varint,5,opt,name=quality_rating,json=qualityRating,proto3" json:"quality_rating,omitempty"`
	Comments       string                `protobuf:"bytes,6,opt,name=comments,proto3" json:"comments,omitempty"`
	StakeWeight    cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=stake_weight,json=stakeWeight,proto3,customtype=cosmossdk.io/math.Int" json:"stake_weight"`
	VotedAt        int64                 `protobuf:"varint,8,opt,name=voted_at,json=votedAt,proto3" json:"voted_at,omitempty"`
}

func (m *VerificationVote) Reset()         { *m = VerificationVote{} }
func (m *VerificationVote) String() string { return proto.CompactTextString(m) }
func (*VerificationVote) ProtoMessage()    {}
func (*VerificationVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{3}
}
func (m *VerificationVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationVote.Merge(m, src)
}
func (m *VerificationVote) XXX_Size() int {
	return m.Size()
}
func (m *VerificationVote) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationVote.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationVote proto.InternalMessageInfo

func (m *VerificationVote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *VerificationVote) GetContributionId() uint64 {
	if m != nil {
		return m.ContributionId
	}
	return 0
}

func (m *VerificationVote) GetTrancheId() uint32 {
	if m != nil {
		return m.TrancheId
	}
	return 0
}

func (m *VerificationVote) GetValueConfirmed() bool {
	if m != nil {
		return m.ValueConfirmed
	}
	return false
}

func (m *VerificationVote) GetQualityRating() uint32 {
	if m != nil {
		return m.QualityRating
	}
	return 0
}

func (m *VerificationVote) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *VerificationVote) GetVotedAt() int64 {
	if m != nil {
		return m.VotedAt
	}
	return 0
}

// TrancheDef is used in MsgPropose to define tranche structure.
type TrancheDef struct {
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Components  []string `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// DREAM that must be staked to back this tranche; also the mint amount on payout
	StakeThreshold cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=stake_threshold,json=stakeThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"stake_threshold"`
	PreviewUri     string                `protobuf:"bytes,5,opt,name=preview_uri,json=previewUri,proto3" json:"preview_uri,omitempty"`
}

func (m *TrancheDef) Reset()         { *m = TrancheDef{} }
func (m *TrancheDef) String() string { return proto.CompactTextString(m) }
func (*TrancheDef) ProtoMessage()    {}
func (*TrancheDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bcd39d84f749826, []int{4}
}
func (m *TrancheDef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrancheDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrancheDef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrancheDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrancheDef.Merge(m, src)
}
func (m *TrancheDef) XXX_Size() int {
	return m.Size()
}
func (m *TrancheDef) XXX_DiscardUnknown() {
	xxx_messageInfo_TrancheDef.DiscardUnknown(m)
}

var xxx_messageInfo_TrancheDef proto.InternalMessageInfo

func (m *TrancheDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrancheDef) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TrancheDef) GetComponents() []string {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *TrancheDef) GetPreviewUri() string {
	if m != nil {
		return m.PreviewUri
	}
	return ""
}

func init() {
	proto.RegisterEnum("sparkdream.reveal.v1.ContributionStatus", ContributionStatus_name, ContributionStatus_value)
	proto.RegisterEnum("sparkdream.reveal.v1.TrancheStatus", TrancheStatus_name, TrancheStatus_value)
	proto.RegisterEnum("sparkdream.reveal.v1.DisputeVerdict", DisputeVerdict_name, DisputeVerdict_value)
	proto.RegisterType((*Contribution)(nil), "sparkdream.reveal.v1.Contribution")
	proto.RegisterType((*RevealTranche)(nil), "sparkdream.reveal.v1.RevealTranche")
	proto.RegisterType((*RevealStake)(nil), "sparkdream.reveal.v1.RevealStake")
	proto.RegisterType((*VerificationVote)(nil), "sparkdream.reveal.v1.VerificationVote")
	proto.RegisterType((*TrancheDef)(nil), "sparkdream.reveal.v1.TrancheDef")
}

func init() { proto.RegisterFile("sparkdream/reveal/v1/types.proto", fileDescriptor_7bcd39d84f749826) }

var fileDescriptor_7bcd39d84f749826 = []byte{
	// 1332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4f, 0x6f, 0x1a, 0x47,
	0x14, 0xf7, 0x02, 0xb6, 0x61, 0x30, 0x98, 0x4e, 0xed, 0x66, 0xed, 0x24, 0x98, 0x38, 0xaa, 0x82,
	0x22, 0x15, 0xe7, 0x8f, 0x5a, 0xa9, 0xad, 0x54, 0x65, 0x0d, 0x9b, 0x64, 0x1b, 0x07, 0xd0, 0x82,
	0xa9, 0xd4, 0xcb, 0x6a, 0xbd, 0x3b, 0x36, 0x53, 0xc3, 0x0e, 0x9d, 0x1d, 0x48, 0xfd, 0x05, 0x7a,
	0xee, 0xb1, 0xd7, 0x7e, 0x87, 0x7e, 0x88, 0x48, 0xbd, 0x44, 0xed, 0x25, 0xea, 0x21, 0xaa, 0x92,
	0x63, 0x4f, 0xfd, 0x06, 0xd5, 0xbc, 0x99, 0xb5, 0x09, 0x21, 0x35, 0xea, 0x8d, 0xf9, 0xbd, 0xdf,
	0x6f, 0x66, 0xde, 0xcc, 0xfb, 0xbd, 0x61, 0x51, 0x25, 0x1e, 0xf9, 0xfc, 0x34, 0xe4, 0xc4, 0x1f,
	0xee, 0x71, 0x32, 0x21, 0xfe, 0x60, 0x6f, 0x72, 0x77, 0x4f, 0x9c, 0x8d, 0x48, 0x5c, 0x1b, 0x71,
	0x26, 0x18, 0xde, 0xb8, 0x60, 0xd4, 0x14, 0xa3, 0x36, 0xb9, 0xbb, 0xbd, 0x15, 0xb0, 0x78, 0xc8,
	0x62, 0x0f, 0x38, 0x7b, 0x6a, 0xa0, 0x04, 0xdb, 0x1b, 0x27, 0xec, 0x84, 0x29, 0x5c, 0xfe, 0x52,
	0xe8, 0xee, 0xcb, 0x55, 0xb4, 0x56, 0x67, 0x91, 0xe0, 0xf4, 0x68, 0x2c, 0x28, 0x8b, 0x70, 0x11,
	0xa5, 0x68, 0x68, 0x1a, 0x15, 0xa3, 0x9a, 0x71, 0x53, 0x34, 0xc4, 0x5f, 0xa0, 0x7c, 0x90, 0xc4,
	0x19, 0x37, 0x53, 0x15, 0xa3, 0x9a, 0xdb, 0x37, 0x7f, 0xff, 0xf5, 0x93, 0x0d, 0x3d, 0xbb, 0x15,
	0x86, 0x9c, 0xc4, 0x71, 0x47, 0x70, 0x1a, 0x9d, 0xb8, 0xd3, 0x64, 0x7c, 0x03, 0xad, 0x8d, 0x38,
	0xfb, 0x8e, 0x04, 0xc2, 0x8b, 0xfc, 0x21, 0x31, 0xd3, 0x52, 0xec, 0xe6, 0x35, 0xd6, 0xf4, 0x87,
	0x04, 0x57, 0x50, 0x3e, 0x24, 0x71, 0xc0, 0xe9, 0x48, 0xae, 0x6e, 0x66, 0x14, 0x63, 0x0a, 0xc2,
	0x36, 0xca, 0x0a, 0xee, 0x47, 0x41, 0x9f, 0xc4, 0xe6, 0x72, 0x25, 0x5d, 0xcd, 0xdf, 0xbb, 0x59,
	0x9b, 0x97, 0x7b, 0xcd, 0x85, 0x5f, 0x5d, 0xc5, 0xdd, 0xcf, 0x3c, 0x7f, 0xb5, 0xb3, 0xe4, 0x9e,
	0x4b, 0xf1, 0x2d, 0xb4, 0x1e, 0x8c, 0x39, 0x27, 0x91, 0xf0, 0x34, 0x66, 0xae, 0x54, 0x8c, 0x6a,
	0xc1, 0x2d, 0x6a, 0x58, 0x0b, 0xf1, 0x43, 0xb4, 0x2e, 0x98, 0xf0, 0x07, 0xde, 0xc4, 0x1f, 0x8c,
	0x7d, 0xd8, 0xd5, 0x2a, 0x24, 0x7d, 0x5d, 0xce, 0xf8, 0xe7, 0xab, 0x9d, 0x4d, 0x95, 0x78, 0x1c,
	0x9e, 0xd6, 0x28, 0xdb, 0x1b, 0xfa, 0xa2, 0x5f, 0x73, 0x22, 0xe1, 0x16, 0x41, 0xd5, 0x4b, 0x44,
	0xf8, 0x2b, 0x94, 0x3f, 0x62, 0x51, 0xe8, 0xf9, 0x43, 0x36, 0x8e, 0x84, 0x99, 0x5d, 0x64, 0x0e,
	0x24, 0x15, 0x16, 0x08, 0x70, 0x03, 0x15, 0x41, 0xcf, 0xc9, 0xd0, 0xa7, 0x11, 0x8d, 0x4e, 0xcc,
	0xdc, 0x22, 0x53, 0x14, 0xa4, 0xc8, 0x4d, 0x34, 0x32, 0x6d, 0x1a, 0x51, 0x41, 0xfd, 0x81, 0x37,
	0xa0, 0x01, 0x89, 0x62, 0x62, 0x22, 0x38, 0xe3, 0xa2, 0x86, 0x0f, 0x14, 0x8a, 0x6f, 0xa2, 0xc2,
	0x31, 0x8d, 0xa6, 0x68, 0x79, 0xa0, 0xad, 0x01, 0x98, 0x90, 0x3e, 0x43, 0x57, 0xe4, 0xe1, 0xc5,
	0x54, 0x66, 0x48, 0x42, 0x4f, 0x30, 0x4f, 0x5f, 0xa6, 0xb9, 0x56, 0x31, 0xaa, 0x59, 0x77, 0x73,
	0x3a, 0xdc, 0x65, 0x6d, 0x15, 0xc4, 0xd7, 0x11, 0x4a, 0x0a, 0x81, 0x86, 0x66, 0x01, 0x8a, 0x2b,
	0xa7, 0x11, 0x27, 0xc4, 0x0f, 0xd0, 0x4a, 0x2c, 0x7c, 0x31, 0x8e, 0xcd, 0x62, 0xc5, 0xa8, 0x16,
	0xef, 0x55, 0xe7, 0x5f, 0xf0, 0x74, 0x9d, 0x76, 0x80, 0xef, 0x6a, 0x9d, 0x5c, 0x20, 0x60, 0xe3,
	0x28, 0xa0, 0x03, 0xb9, 0xc0, 0xba, 0x5a, 0x40, 0x23, 0x4e, 0x88, 0x3f, 0x47, 0x79, 0x7f, 0x34,
	0xe2, 0x6c, 0x42, 0x42, 0xef, 0xe8, 0xcc, 0x2c, 0x5d, 0x52, 0xc4, 0x28, 0x21, 0xef, 0x9f, 0xe1,
	0x9d, 0x29, 0xa9, 0x2f, 0xcc, 0x0f, 0x2a, 0x46, 0x35, 0x7d, 0x41, 0xb0, 0x20, 0xb7, 0x80, 0x13,
	0x5f, 0xa8, 0x38, 0x86, 0x78, 0x4e, 0x23, 0x96, 0x90, 0xe5, 0xd4, 0x67, 0x83, 0xf0, 0xc8, 0x0f,
	0x4e, 0x93, 0x52, 0xf8, 0x70, 0xa1, 0x72, 0x4a, 0x54, 0xba, 0x1c, 0xee, 0xa0, 0x8d, 0x11, 0x67,
	0x23, 0x16, 0xfb, 0x03, 0x8f, 0x0c, 0xe8, 0x09, 0x3d, 0x1a, 0x10, 0xb9, 0xe0, 0x06, 0x2c, 0x88,
	0x93, 0x98, 0xad, 0x43, 0x96, 0xd8, 0xfd, 0x79, 0x19, 0x15, 0xde, 0xf2, 0xc4, 0x94, 0xb7, 0x0b,
	0xe0, 0x6d, 0x8c, 0x32, 0xe0, 0x4b, 0x30, 0xb5, 0x0b, 0xbf, 0x67, 0x0d, 0x99, 0x7e, 0xd7, 0x90,
	0x65, 0x79, 0xd6, 0xc3, 0x11, 0x8b, 0x48, 0x24, 0x62, 0x33, 0x53, 0x49, 0x57, 0x73, 0xee, 0x14,
	0x22, 0x33, 0x8e, 0x85, 0x7f, 0x4a, 0x3c, 0xd1, 0xe7, 0x24, 0x96, 0x69, 0x98, 0xcb, 0x0b, 0x65,
	0x0c, 0xaa, 0x6e, 0x22, 0xc2, 0x0f, 0xd0, 0x1a, 0x54, 0x80, 0x07, 0x78, 0x08, 0x76, 0xbd, 0x74,
	0x92, 0x3c, 0x48, 0x3a, 0xa0, 0x90, 0x77, 0x37, 0xe2, 0x64, 0x42, 0xc9, 0x33, 0x6f, 0xcc, 0xa9,
	0xb2, 0xb1, 0x8b, 0x34, 0x74, 0xc8, 0x29, 0xde, 0x42, 0xd9, 0x80, 0x85, 0x04, 0xa2, 0x60, 0x50,
	0x77, 0x55, 0x8e, 0x75, 0x28, 0x64, 0x41, 0x0c, 0xa1, 0x9c, 0x0a, 0xc9, 0xb1, 0x0c, 0xed, 0xc8,
	0x96, 0x38, 0x1c, 0x52, 0xe1, 0xf5, 0xfd, 0xb8, 0xaf, 0xfd, 0x84, 0x14, 0xf4, 0xd8, 0x8f, 0xfb,
	0xf8, 0x63, 0xa4, 0x72, 0xf1, 0x42, 0xe2, 0x87, 0x03, 0x1a, 0x29, 0x33, 0xa5, 0xdd, 0x02, 0xa0,
	0x0d, 0x0d, 0x4a, 0x6f, 0xaa, 0xe2, 0xbe, 0xe0, 0xad, 0x01, 0xaf, 0xa8, 0xe0, 0x73, 0xe2, 0x7d,
	0xb4, 0x39, 0x21, 0x9c, 0x1e, 0xd3, 0x00, 0x5a, 0xcb, 0x05, 0xbd, 0x00, 0xf4, 0x8d, 0xe9, 0xe0,
	0xb9, 0xe8, 0xcb, 0x19, 0x53, 0xbd, 0xa7, 0x6b, 0xea, 0xda, 0x98, 0xf1, 0xd3, 0x55, 0x94, 0x93,
	0xb5, 0xa7, 0x6a, 0x7a, 0x1d, 0x56, 0xc9, 0x2a, 0xc0, 0x12, 0x32, 0x7f, 0xa5, 0x57, 0xe1, 0x92,
	0xb2, 0x44, 0x02, 0x29, 0x82, 0xda, 0xd2, 0x5b, 0x9e, 0x49, 0x20, 0x4b, 0xec, 0xfe, 0x6d, 0xa0,
	0xbc, 0x2a, 0x4d, 0xb8, 0xa9, 0x77, 0x1e, 0x9d, 0x3b, 0xb0, 0xf7, 0x53, 0x72, 0xf9, 0x7b, 0xa3,
	0x79, 0xd0, 0xde, 0xa7, 0xda, 0x83, 0xec, 0x02, 0x69, 0x98, 0xae, 0x38, 0x0d, 0x3b, 0xa1, 0xb4,
	0xab, 0xee, 0xff, 0x92, 0x93, 0x01, 0x2f, 0xe4, 0x34, 0xe2, 0x84, 0xf8, 0x53, 0xb4, 0xa2, 0x5d,
	0xba, 0x50, 0xcd, 0x6a, 0xb2, 0x3c, 0x2f, 0x55, 0xa5, 0x32, 0xdf, 0x15, 0x75, 0x5e, 0x0a, 0xb0,
	0xc4, 0xee, 0x1f, 0x29, 0x54, 0xea, 0x4d, 0x5d, 0x51, 0x8f, 0x09, 0x82, 0x6b, 0x68, 0x79, 0xc2,
	0x04, 0xe1, 0x90, 0xf5, 0x7f, 0x65, 0xa8, 0x68, 0xf3, 0x12, 0x4c, 0x2d, 0x90, 0x60, 0x7a, 0x36,
	0xc1, 0x5b, 0x68, 0x5d, 0x3e, 0x6c, 0xc4, 0x0b, 0x58, 0x74, 0x4c, 0xf9, 0x90, 0xa8, 0x43, 0xc8,
	0xba, 0x45, 0x80, 0xeb, 0x09, 0x2a, 0x8b, 0xf8, 0xfb, 0xb1, 0x3f, 0xa0, 0xe2, 0xcc, 0xe3, 0xbe,
	0x90, 0xef, 0xcf, 0x32, 0xcc, 0x55, 0xd0, 0xa8, 0x0b, 0x20, 0xde, 0x96, 0x16, 0x1a, 0x0e, 0xa1,
	0x17, 0x80, 0x43, 0xdd, 0xf3, 0xb1, 0x74, 0xb0, 0xf2, 0xc1, 0x33, 0x42, 0x4f, 0xfa, 0x62, 0xb1,
	0x77, 0x34, 0x0f, 0x92, 0x6f, 0x40, 0x21, 0x5d, 0x28, 0xd3, 0x87, 0x63, 0xcd, 0xc2, 0xb1, 0xae,
	0xc2, 0xd8, 0x12, 0xbb, 0xbf, 0x19, 0x08, 0xe9, 0xe2, 0x6d, 0x90, 0xe3, 0xf3, 0x5e, 0x66, 0xbc,
	0xbf, 0x97, 0xa5, 0x2e, 0xeb, 0x65, 0xe9, 0x45, 0x7a, 0x59, 0xe6, 0xff, 0xf4, 0xb2, 0x99, 0x4e,
	0xb4, 0x3c, 0xdb, 0x89, 0x6e, 0xff, 0x62, 0x20, 0xfc, 0xee, 0xfb, 0x86, 0x2b, 0xe8, 0x5a, 0xbd,
	0xd5, 0xec, 0xba, 0xce, 0xfe, 0x61, 0xd7, 0x69, 0x35, 0xbd, 0x4e, 0xd7, 0xea, 0x1e, 0x76, 0xbc,
	0xb6, 0xdb, 0x6a, 0xb7, 0x3a, 0x76, 0xa3, 0xb4, 0x84, 0x6f, 0xa2, 0x9d, 0x79, 0x0c, 0xa7, 0x29,
	0x49, 0x8f, 0x5c, 0xbb, 0xd3, 0x29, 0x19, 0xf8, 0x06, 0xba, 0x3e, 0x8f, 0x54, 0x6f, 0x3d, 0x6d,
	0x1f, 0xd8, 0x5d, 0xbb, 0x51, 0x4a, 0xbd, 0x97, 0x62, 0x35, 0xeb, 0xf6, 0xc1, 0x81, 0xdd, 0x28,
	0xa5, 0x6f, 0xff, 0x63, 0xa0, 0xc2, 0x5b, 0xed, 0x02, 0x6f, 0xa1, 0xcd, 0xae, 0x6b, 0x35, 0xeb,
	0x8f, 0xed, 0x84, 0x7f, 0xd0, 0xaa, 0x3f, 0x81, 0x7d, 0x6d, 0xa3, 0x8f, 0x66, 0x42, 0x9d, 0xae,
	0xf5, 0xc4, 0x69, 0x3e, 0x2a, 0x19, 0x73, 0x64, 0xfb, 0x16, 0xc8, 0x52, 0xf8, 0x2a, 0xba, 0x32,
	0x13, 0x72, 0xed, 0x9e, 0x6d, 0xc1, 0x06, 0xe6, 0x04, 0x7b, 0xb6, 0xeb, 0x3c, 0x74, 0xec, 0x46,
	0x29, 0x33, 0x27, 0xd8, 0x70, 0x3a, 0xed, 0x43, 0x99, 0xdd, 0x32, 0xbe, 0x86, 0xcc, 0x99, 0xe0,
	0x45, 0x62, 0x2b, 0x73, 0xf6, 0xf3, 0xd0, 0x72, 0x64, 0x68, 0xf5, 0xf6, 0x8f, 0x06, 0x2a, 0x36,
	0x68, 0x3c, 0x1a, 0x0b, 0xd2, 0x23, 0x3c, 0xa4, 0x81, 0xec, 0x6e, 0x57, 0xf5, 0xcc, 0x72, 0xf9,
	0x86, 0x53, 0xef, 0x7a, 0x87, 0xcd, 0x4e, 0xdb, 0xae, 0xab, 0x9d, 0x40, 0xea, 0xb3, 0x04, 0xab,
	0x5e, 0xb7, 0xdb, 0xdd, 0x92, 0x21, 0x77, 0x39, 0x1b, 0x73, 0x9e, 0xb6, 0xdd, 0x56, 0xcf, 0x2e,
	0xa5, 0xe6, 0x09, 0x5d, 0xfb, 0x6b, 0xbb, 0xde, 0x2d, 0xa5, 0xf7, 0xef, 0x3f, 0x7f, 0x5d, 0x36,
	0x5e, 0xbc, 0x2e, 0x1b, 0x7f, 0xbd, 0x2e, 0x1b, 0x3f, 0xbd, 0x29, 0x2f, 0xbd, 0x78, 0x53, 0x5e,
	0x7a, 0xf9, 0xa6, 0xbc, 0xf4, 0xed, 0xd6, 0xd4, 0xb7, 0xc2, 0x0f, 0xc9, 0xd7, 0x02, 0x7c, 0x2a,
	0x1c, 0xad, 0xc0, 0x9f, 0xfc, 0xfb, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb0, 0xb3, 0x82,
	0x4f, 0x0c, 0x00, 0x00,
}

func (m *Contribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalEligibleAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProposalEligibleAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	{
		size := m.HoldbackAmount.Size()
		i -= size
		if _, err := m.HoldbackAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.ApprovedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ApprovedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.ApprovedBy) > 0 {
		i -= len(m.ApprovedBy)
		copy(dAtA[i:], m.ApprovedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ApprovedBy)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.CouncilId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CouncilId))
		i--
		dAtA[i] = 0x78
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x70
	}
	if m.ProjectId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x68
	}
	if m.TransitionedToProject {
		i--
		if m.TransitionedToProject {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.FinalLicense) > 0 {
		i -= len(m.FinalLicense)
		copy(dAtA[i:], m.FinalLicense)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FinalLicense)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.InitialLicense) > 0 {
		i -= len(m.InitialLicense)
		copy(dAtA[i:], m.InitialLicense)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.InitialLicense)))
		i--
		dAtA[i] = 0x52
	}
	{
		size := m.BondRemaining.Size()
		i -= size
		if _, err := m.BondRemaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.BondAmount.Size()
		i -= size
		if _, err := m.BondAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.TotalValuation.Size()
		i -= size
		if _, err := m.TotalValuation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.CurrentTranche != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CurrentTranche))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Tranches) > 0 {
		for iNdEx := len(m.Tranches) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tranches[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProjectName) > 0 {
		i -= len(m.ProjectName)
		copy(dAtA[i:], m.ProjectName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProjectName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Contributor) > 0 {
		i -= len(m.Contributor)
		copy(dAtA[i:], m.Contributor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Contributor)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RevealTranche) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevealTranche) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevealTranche) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifiedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VerifiedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.RevealedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RevealedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.BackedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BackedAt))
		i--
		dAtA[i] = 0x78
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x70
	}
	if m.VerificationDeadline != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VerificationDeadline))
		i--
		dAtA[i] = 0x68
	}
	if m.RevealDeadline != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RevealDeadline))
		i--
		dAtA[i] = 0x60
	}
	if m.StakeDeadline != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StakeDeadline))
		i--
		dAtA[i] = 0x58
	}
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.DocsUri) > 0 {
		i -= len(m.DocsUri)
		copy(dAtA[i:], m.DocsUri)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DocsUri)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.CodeUri) > 0 {
		i -= len(m.CodeUri)
		copy(dAtA[i:], m.CodeUri)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CodeUri)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PreviewUri) > 0 {
		i -= len(m.PreviewUri)
		copy(dAtA[i:], m.PreviewUri)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PreviewUri)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.DreamStaked.Size()
		i -= size
		if _, err := m.DreamStaked.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.StakeThreshold.Size()
		i -= size
		if _, err := m.StakeThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Components) > 0 {
		for iNdEx := len(m.Components) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Components[iNdEx])
			copy(dAtA[i:], m.Components[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Components[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RevealStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevealStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevealStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StakedAt))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.TrancheId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TrancheId))
		i--
		dAtA[i] = 0x20
	}
	if m.ContributionId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ContributionId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VerificationVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VotedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VotedAt))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.StakeWeight.Size()
		i -= size
		if _, err := m.StakeWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x32
	}
	if m.QualityRating != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QualityRating))
		i--
		dAtA[i] = 0x28
	}
	if m.ValueConfirmed {
		i--
		if m.ValueConfirmed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.TrancheId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TrancheId))
		i--
		dAtA[i] = 0x18
	}
	if m.ContributionId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ContributionId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrancheDef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrancheDef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrancheDef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreviewUri) > 0 {
		i -= len(m.PreviewUri)
		copy(dAtA[i:], m.PreviewUri)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PreviewUri)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.StakeThreshold.Size()
		i -= size
		if _, err := m.StakeThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Components) > 0 {
		for iNdEx := len(m.Components) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Components[iNdEx])
			copy(dAtA[i:], m.Components[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Components[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Contributor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ProjectName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Tranches) > 0 {
		for _, e := range m.Tranches {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.CurrentTranche != 0 {
		n += 1 + sovTypes(uint64(m.CurrentTranche))
	}
	l = m.TotalValuation.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.BondAmount.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.BondRemaining.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.InitialLicense)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.FinalLicense)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TransitionedToProject {
		n += 2
	}
	if m.ProjectId != 0 {
		n += 1 + sovTypes(uint64(m.ProjectId))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if m.CouncilId != 0 {
		n += 1 + sovTypes(uint64(m.CouncilId))
	}
	l = len(m.ApprovedBy)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.ApprovedAt != 0 {
		n += 2 + sovTypes(uint64(m.ApprovedAt))
	}
	if m.CreatedAt != 0 {
		n += 2 + sovTypes(uint64(m.CreatedAt))
	}
	l = m.HoldbackAmount.Size()
	n += 2 + l + sovTypes(uint64(l))
	if m.ProposalEligibleAt != 0 {
		n += 2 + sovTypes(uint64(m.ProposalEligibleAt))
	}
	return n
}

func (m *RevealTranche) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Components) > 0 {
		for _, s := range m.Components {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = m.StakeThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.DreamStaked.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.PreviewUri)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CodeUri)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DocsUri)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.StakeDeadline != 0 {
		n += 1 + sovTypes(uint64(m.StakeDeadline))
	}
	if m.RevealDeadline != 0 {
		n += 1 + sovTypes(uint64(m.RevealDeadline))
	}
	if m.VerificationDeadline != 0 {
		n += 1 + sovTypes(uint64(m.VerificationDeadline))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if m.BackedAt != 0 {
		n += 1 + sovTypes(uint64(m.BackedAt))
	}
	if m.RevealedAt != 0 {
		n += 2 + sovTypes(uint64(m.RevealedAt))
	}
	if m.VerifiedAt != 0 {
		n += 2 + sovTypes(uint64(m.VerifiedAt))
	}
	return n
}

func (m *RevealStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ContributionId != 0 {
		n += 1 + sovTypes(uint64(m.ContributionId))
	}
	if m.TrancheId != 0 {
		n += 1 + sovTypes(uint64(m.TrancheId))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.StakedAt != 0 {
		n += 1 + sovTypes(uint64(m.StakedAt))
	}
	return n
}

func (m *VerificationVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ContributionId != 0 {
		n += 1 + sovTypes(uint64(m.ContributionId))
	}
	if m.TrancheId != 0 {
		n += 1 + sovTypes(uint64(m.TrancheId))
	}
	if m.ValueConfirmed {
		n += 2
	}
	if m.QualityRating != 0 {
		n += 1 + sovTypes(uint64(m.QualityRating))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.StakeWeight.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.VotedAt != 0 {
		n += 1 + sovTypes(uint64(m.VotedAt))
	}
	return n
}

func (m *TrancheDef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Components) > 0 {
		for _, s := range m.Components {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = m.StakeThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.PreviewUri)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tranches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tranches = append(m.Tranches, RevealTranche{})
			if err := m.Tranches[len(m.Tranches)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentTranche", wireType)
			}
			m.CurrentTranche = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentTranche |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValuation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalValuation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondRemaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondRemaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialLicense", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialLicense = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalLicense", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalLicense = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransitionedToProject", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TransitionedToProject = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ContributionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CouncilId", wireType)
			}
			m.CouncilId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CouncilId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedAt", wireType)
			}
			m.ApprovedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApprovedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoldbackAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HoldbackAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalEligibleAt", wireType)
			}
			m.ProposalEligibleAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalEligibleAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RevealTranche) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevealTranche: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevealTranche: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Components", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Components = append(m.Components, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakeThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DreamStaked", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DreamStaked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviewUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviewUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocsUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocsUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeDeadline", wireType)
			}
			m.StakeDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealDeadline", wireType)
			}
			m.RevealDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationDeadline", wireType)
			}
			m.VerificationDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrancheStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackedAt", wireType)
			}
			m.BackedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BackedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealedAt", wireType)
			}
			m.RevealedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedAt", wireType)
			}
			m.VerifiedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifiedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RevealStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevealStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevealStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionId", wireType)
			}
			m.ContributionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrancheId", wireType)
			}
			m.TrancheId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrancheId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedAt", wireType)
			}
			m.StakedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionId", wireType)
			}
			m.ContributionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContributionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrancheId", wireType)
			}
			m.TrancheId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrancheId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueConfirmed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ValueConfirmed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QualityRating", wireType)
			}
			m.QualityRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QualityRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakeWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotedAt", wireType)
			}
			m.VotedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrancheDef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrancheDef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrancheDef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Components", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Components = append(m.Components, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakeThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviewUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviewUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
