// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/federation/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the federation module.
type Params struct {
	// Bridge operator requirements
	MinBridgeStake           types.Coin    `protobuf:"bytes,1,opt,name=min_bridge_stake,json=minBridgeStake,proto3" json:"min_bridge_stake"`
	MaxBridgesPerPeer        uint64        `protobuf:"varint,2,opt,name=max_bridges_per_peer,json=maxBridgesPerPeer,proto3" json:"max_bridges_per_peer,omitempty"`
	BridgeRevocationCooldown time.Duration `protobuf:"bytes,3,opt,name=bridge_revocation_cooldown,json=bridgeRevocationCooldown,proto3,stdduration" json:"bridge_revocation_cooldown"`
	BridgeUnbondingPeriod    time.Duration `protobuf:"bytes,4,opt,name=bridge_unbonding_period,json=bridgeUnbondingPeriod,proto3,stdduration" json:"bridge_unbonding_period"`
	// Content types
	KnownContentTypes []string `protobuf:"bytes,5,rep,name=known_content_types,json=knownContentTypes,proto3" json:"known_content_types,omitempty"`
	// Content federation
	MaxInboundPerBlock      uint64        `protobuf:"varint,6,opt,name=max_inbound_per_block,json=maxInboundPerBlock,proto3" json:"max_inbound_per_block,omitempty"`
	MaxContentBodySize      uint64        `protobuf:"varint,7,opt,name=max_content_body_size,json=maxContentBodySize,proto3" json:"max_content_body_size,omitempty"`
	MaxContentUriSize       uint64        `protobuf:"varint,8,opt,name=max_content_uri_size,json=maxContentUriSize,proto3" json:"max_content_uri_size,omitempty"`
	MaxProtocolMetadataSize uint64        `protobuf:"varint,9,opt,name=max_protocol_metadata_size,json=maxProtocolMetadataSize,proto3" json:"max_protocol_metadata_size,omitempty"`
	ContentTtl              time.Duration `protobuf:"bytes,10,opt,name=content_ttl,json=contentTtl,proto3,stdduration" json:"content_ttl"`
	// Reputation
	AttestationTtl       time.Duration               `protobuf:"bytes,11,opt,name=attestation_ttl,json=attestationTtl,proto3,stdduration" json:"attestation_ttl"`
	GlobalMaxTrustCredit uint32                      `protobuf:"varint,12,opt,name=global_max_trust_credit,json=globalMaxTrustCredit,proto3" json:"global_max_trust_credit,omitempty"`
	TrustDiscountRate    cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=trust_discount_rate,json=trustDiscountRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"trust_discount_rate"`
	// Identity
	MaxIdentityLinksPerUser uint32        `protobuf:"varint,14,opt,name=max_identity_links_per_user,json=maxIdentityLinksPerUser,proto3" json:"max_identity_links_per_user,omitempty"`
	UnverifiedLinkTtl       time.Duration `protobuf:"bytes,15,opt,name=unverified_link_ttl,json=unverifiedLinkTtl,proto3,stdduration" json:"unverified_link_ttl"`
	ChallengeTtl            time.Duration `protobuf:"bytes,16,opt,name=challenge_ttl,json=challengeTtl,proto3,stdduration" json:"challenge_ttl"`
	// Bridge monitoring
	BridgeInactivityThreshold uint64 `protobuf:"varint,17,opt,name=bridge_inactivity_threshold,json=bridgeInactivityThreshold,proto3" json:"bridge_inactivity_threshold,omitempty"`
	// IBC
	IbcPort           string        `protobuf:"bytes,18,opt,name=ibc_port,json=ibcPort,proto3" json:"ibc_port,omitempty"`
	IbcChannelVersion string        `protobuf:"bytes,19,opt,name=ibc_channel_version,json=ibcChannelVersion,proto3" json:"ibc_channel_version,omitempty"`
	IbcPacketTimeout  time.Duration `protobuf:"bytes,20,opt,name=ibc_packet_timeout,json=ibcPacketTimeout,proto3,stdduration" json:"ibc_packet_timeout"`
	// Pruning
	MaxPrunePerBlock uint64 `protobuf:"varint,21,opt,name=max_prune_per_block,json=maxPrunePerBlock,proto3" json:"max_prune_per_block,omitempty"`
	// Outbound rate limiting
	MaxOutboundPerBlock uint64 `protobuf:"varint,22,opt,name=max_outbound_per_block,json=maxOutboundPerBlock,proto3" json:"max_outbound_per_block,omitempty"`
	// Rate limiting
	RateLimitWindow time.Duration `protobuf:"bytes,23,opt,name=rate_limit_window,json=rateLimitWindow,proto3,stdduration" json:"rate_limit_window"`
	// Verification (sentinel-style)
	MinVerifierTrustLevel        uint32                      `protobuf:"varint,24,opt,name=min_verifier_trust_level,json=minVerifierTrustLevel,proto3" json:"min_verifier_trust_level,omitempty"`
	MinVerifierBond              cosmossdk_io_math.Int       `protobuf:"bytes,25,opt,name=min_verifier_bond,json=minVerifierBond,proto3,customtype=cosmossdk.io/math.Int" json:"min_verifier_bond"`
	VerifierRecoveryThreshold    cosmossdk_io_math.Int       `protobuf:"bytes,26,opt,name=verifier_recovery_threshold,json=verifierRecoveryThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"verifier_recovery_threshold"`
	VerifierSlashAmount          cosmossdk_io_math.Int       `protobuf:"bytes,27,opt,name=verifier_slash_amount,json=verifierSlashAmount,proto3,customtype=cosmossdk.io/math.Int" json:"verifier_slash_amount"`
	VerificationWindow           time.Duration               `protobuf:"bytes,28,opt,name=verification_window,json=verificationWindow,proto3,stdduration" json:"verification_window"`
	ChallengeWindow              time.Duration               `protobuf:"bytes,29,opt,name=challenge_window,json=challengeWindow,proto3,stdduration" json:"challenge_window"`
	ChallengeFee                 types.Coin                  `protobuf:"bytes,30,opt,name=challenge_fee,json=challengeFee,proto3" json:"challenge_fee"`
	ChallengeJuryDeadline        time.Duration               `protobuf:"bytes,31,opt,name=challenge_jury_deadline,json=challengeJuryDeadline,proto3,stdduration" json:"challenge_jury_deadline"`
	VerifierDemotionCooldown     time.Duration               `protobuf:"bytes,32,opt,name=verifier_demotion_cooldown,json=verifierDemotionCooldown,proto3,stdduration" json:"verifier_demotion_cooldown"`
	VerifierOverturnBaseCooldown time.Duration               `protobuf:"bytes,33,opt,name=verifier_overturn_base_cooldown,json=verifierOverturnBaseCooldown,proto3,stdduration" json:"verifier_overturn_base_cooldown"`
	UpheldToResetOverturns       uint32                      `protobuf:"varint,34,opt,name=upheld_to_reset_overturns,json=upheldToResetOverturns,proto3" json:"upheld_to_reset_overturns,omitempty"`
	MinEpochVerifications        uint32                      `protobuf:"varint,35,opt,name=min_epoch_verifications,json=minEpochVerifications,proto3" json:"min_epoch_verifications,omitempty"`
	MinVerifierAccuracy          cosmossdk_io_math.LegacyDec `protobuf:"bytes,36,opt,name=min_verifier_accuracy,json=minVerifierAccuracy,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_verifier_accuracy"`
	OperatorRewardShare          cosmossdk_io_math.LegacyDec `protobuf:"bytes,37,opt,name=operator_reward_share,json=operatorRewardShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"operator_reward_share"`
	VerifierDreamReward          cosmossdk_io_math.Int       `protobuf:"bytes,38,opt,name=verifier_dream_reward,json=verifierDreamReward,proto3,customtype=cosmossdk.io/math.Int" json:"verifier_dream_reward"`
	MaxVerifierDreamMintPerEpoch cosmossdk_io_math.Int       `protobuf:"bytes,39,opt,name=max_verifier_dream_mint_per_epoch,json=maxVerifierDreamMintPerEpoch,proto3,customtype=cosmossdk.io/math.Int" json:"max_verifier_dream_mint_per_epoch"`
	// Anonymous challenge resolution
	ArbiterQuorum           uint32        `protobuf:"varint,40,opt,name=arbiter_quorum,json=arbiterQuorum,proto3" json:"arbiter_quorum,omitempty"`
	ArbiterResolutionWindow time.Duration `protobuf:"bytes,41,opt,name=arbiter_resolution_window,json=arbiterResolutionWindow,proto3,stdduration" json:"arbiter_resolution_window"`
	ArbiterEscalationWindow time.Duration `protobuf:"bytes,42,opt,name=arbiter_escalation_window,json=arbiterEscalationWindow,proto3,stdduration" json:"arbiter_escalation_window"`
	EscalationFee           types.Coin    `protobuf:"bytes,43,opt,name=escalation_fee,json=escalationFee,proto3" json:"escalation_fee"`
	ChallengeCooldown       time.Duration `protobuf:"bytes,44,opt,name=challenge_cooldown,json=challengeCooldown,proto3,stdduration" json:"challenge_cooldown"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_16ee8151fad3071f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinBridgeStake() types.Coin {
	if m != nil {
		return m.MinBridgeStake
	}
	return types.Coin{}
}

func (m *Params) GetMaxBridgesPerPeer() uint64 {
	if m != nil {
		return m.MaxBridgesPerPeer
	}
	return 0
}

func (m *Params) GetBridgeRevocationCooldown() time.Duration {
	if m != nil {
		return m.BridgeRevocationCooldown
	}
	return 0
}

func (m *Params) GetBridgeUnbondingPeriod() time.Duration {
	if m != nil {
		return m.BridgeUnbondingPeriod
	}
	return 0
}

func (m *Params) GetKnownContentTypes() []string {
	if m != nil {
		return m.KnownContentTypes
	}
	return nil
}

func (m *Params) GetMaxInboundPerBlock() uint64 {
	if m != nil {
		return m.MaxInboundPerBlock
	}
	return 0
}

func (m *Params) GetMaxContentBodySize() uint64 {
	if m != nil {
		return m.MaxContentBodySize
	}
	return 0
}

func (m *Params) GetMaxContentUriSize() uint64 {
	if m != nil {
		return m.MaxContentUriSize
	}
	return 0
}

func (m *Params) GetMaxProtocolMetadataSize() uint64 {
	if m != nil {
		return m.MaxProtocolMetadataSize
	}
	return 0
}

func (m *Params) GetContentTtl() time.Duration {
	if m != nil {
		return m.ContentTtl
	}
	return 0
}

func (m *Params) GetAttestationTtl() time.Duration {
	if m != nil {
		return m.AttestationTtl
	}
	return 0
}

func (m *Params) GetGlobalMaxTrustCredit() uint32 {
	if m != nil {
		return m.GlobalMaxTrustCredit
	}
	return 0
}

func (m *Params) GetMaxIdentityLinksPerUser() uint32 {
	if m != nil {
		return m.MaxIdentityLinksPerUser
	}
	return 0
}

func (m *Params) GetUnverifiedLinkTtl() time.Duration {
	if m != nil {
		return m.UnverifiedLinkTtl
	}
	return 0
}

func (m *Params) GetChallengeTtl() time.Duration {
	if m != nil {
		return m.ChallengeTtl
	}
	return 0
}

func (m *Params) GetBridgeInactivityThreshold() uint64 {
	if m != nil {
		return m.BridgeInactivityThreshold
	}
	return 0
}

func (m *Params) GetIbcPort() string {
	if m != nil {
		return m.IbcPort
	}
	return ""
}

func (m *Params) GetIbcChannelVersion() string {
	if m != nil {
		return m.IbcChannelVersion
	}
	return ""
}

func (m *Params) GetIbcPacketTimeout() time.Duration {
	if m != nil {
		return m.IbcPacketTimeout
	}
	return 0
}

func (m *Params) GetMaxPrunePerBlock() uint64 {
	if m != nil {
		return m.MaxPrunePerBlock
	}
	return 0
}

func (m *Params) GetMaxOutboundPerBlock() uint64 {
	if m != nil {
		return m.MaxOutboundPerBlock
	}
	return 0
}

func (m *Params) GetRateLimitWindow() time.Duration {
	if m != nil {
		return m.RateLimitWindow
	}
	return 0
}

func (m *Params) GetMinVerifierTrustLevel() uint32 {
	if m != nil {
		return m.MinVerifierTrustLevel
	}
	return 0
}

func (m *Params) GetVerificationWindow() time.Duration {
	if m != nil {
		return m.VerificationWindow
	}
	return 0
}

func (m *Params) GetChallengeWindow() time.Duration {
	if m != nil {
		return m.ChallengeWindow
	}
	return 0
}

func (m *Params) GetChallengeFee() types.Coin {
	if m != nil {
		return m.ChallengeFee
	}
	return types.Coin{}
}

func (m *Params) GetChallengeJuryDeadline() time.Duration {
	if m != nil {
		return m.ChallengeJuryDeadline
	}
	return 0
}

func (m *Params) GetVerifierDemotionCooldown() time.Duration {
	if m != nil {
		return m.VerifierDemotionCooldown
	}
	return 0
}

func (m *Params) GetVerifierOverturnBaseCooldown() time.Duration {
	if m != nil {
		return m.VerifierOverturnBaseCooldown
	}
	return 0
}

func (m *Params) GetUpheldToResetOverturns() uint32 {
	if m != nil {
		return m.UpheldToResetOverturns
	}
	return 0
}

func (m *Params) GetMinEpochVerifications() uint32 {
	if m != nil {
		return m.MinEpochVerifications
	}
	return 0
}

func (m *Params) GetArbiterQuorum() uint32 {
	if m != nil {
		return m.ArbiterQuorum
	}
	return 0
}

func (m *Params) GetArbiterResolutionWindow() time.Duration {
	if m != nil {
		return m.ArbiterResolutionWindow
	}
	return 0
}

func (m *Params) GetArbiterEscalationWindow() time.Duration {
	if m != nil {
		return m.ArbiterEscalationWindow
	}
	return 0
}

func (m *Params) GetEscalationFee() types.Coin {
	if m != nil {
		return m.EscalationFee
	}
	return types.Coin{}
}

func (m *Params) GetChallengeCooldown() time.Duration {
	if m != nil {
		return m.ChallengeCooldown
	}
	return 0
}

// FederationOperationalParams is the subset of Params updateable by Operations Committee.
type FederationOperationalParams struct {
	MaxInboundPerBlock        uint64                      `protobuf:"varint,1,opt,name=max_inbound_per_block,json=maxInboundPerBlock,proto3" json:"max_inbound_per_block,omitempty"`
	MaxOutboundPerBlock       uint64                      `protobuf:"varint,2,opt,name=max_outbound_per_block,json=maxOutboundPerBlock,proto3" json:"max_outbound_per_block,omitempty"`
	MaxContentBodySize        uint64                      `protobuf:"varint,3,opt,name=max_content_body_size,json=maxContentBodySize,proto3" json:"max_content_body_size,omitempty"`
	MaxContentUriSize         uint64                      `protobuf:"varint,4,opt,name=max_content_uri_size,json=maxContentUriSize,proto3" json:"max_content_uri_size,omitempty"`
	MaxProtocolMetadataSize   uint64                      `protobuf:"varint,5,opt,name=max_protocol_metadata_size,json=maxProtocolMetadataSize,proto3" json:"max_protocol_metadata_size,omitempty"`
	ContentTtl                time.Duration               `protobuf:"bytes,6,opt,name=content_ttl,json=contentTtl,proto3,stdduration" json:"content_ttl"`
	AttestationTtl            time.Duration               `protobuf:"bytes,7,opt,name=attestation_ttl,json=attestationTtl,proto3,stdduration" json:"attestation_ttl"`
	GlobalMaxTrustCredit      uint32                      `protobuf:"varint,8,opt,name=global_max_trust_credit,json=globalMaxTrustCredit,proto3" json:"global_max_trust_credit,omitempty"`
	TrustDiscountRate         cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=trust_discount_rate,json=trustDiscountRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"trust_discount_rate"`
	BridgeInactivityThreshold uint64                      `protobuf:"varint,10,opt,name=bridge_inactivity_threshold,json=bridgeInactivityThreshold,proto3" json:"bridge_inactivity_threshold,omitempty"`
	MaxPrunePerBlock          uint64                      `protobuf:"varint,11,opt,name=max_prune_per_block,json=maxPrunePerBlock,proto3" json:"max_prune_per_block,omitempty"`
}

func (m *FederationOperationalParams) Reset()         { *m = FederationOperationalParams{} }
func (m *FederationOperationalParams) String() string { return proto.CompactTextString(m) }
func (*FederationOperationalParams) ProtoMessage()    {}
func (*FederationOperationalParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_16ee8151fad3071f, []int{1}
}
func (m *FederationOperationalParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FederationOperationalParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FederationOperationalParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FederationOperationalParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederationOperationalParams.Merge(m, src)
}
func (m *FederationOperationalParams) XXX_Size() int {
	return m.Size()
}
func (m *FederationOperationalParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FederationOperationalParams.DiscardUnknown(m)
}

var xxx_messageInfo_FederationOperationalParams proto.InternalMessageInfo

func (m *FederationOperationalParams) GetMaxInboundPerBlock() uint64 {
	if m != nil {
		return m.MaxInboundPerBlock
	}
	return 0
}

func (m *FederationOperationalParams) GetMaxOutboundPerBlock() uint64 {
	if m != nil {
		return m.MaxOutboundPerBlock
	}
	return 0
}

func (m *FederationOperationalParams) GetMaxContentBodySize() uint64 {
	if m != nil {
		return m.MaxContentBodySize
	}
	return 0
}

func (m *FederationOperationalParams) GetMaxContentUriSize() uint64 {
	if m != nil {
		return m.MaxContentUriSize
	}
	return 0
}

func (m *FederationOperationalParams) GetMaxProtocolMetadataSize() uint64 {
	if m != nil {
		return m.MaxProtocolMetadataSize
	}
	return 0
}

func (m *FederationOperationalParams) GetContentTtl() time.Duration {
	if m != nil {
		return m.ContentTtl
	}
	return 0
}

func (m *FederationOperationalParams) GetAttestationTtl() time.Duration {
	if m != nil {
		return m.AttestationTtl
	}
	return 0
}

func (m *FederationOperationalParams) GetGlobalMaxTrustCredit() uint32 {
	if m != nil {
		return m.GlobalMaxTrustCredit
	}
	return 0
}

func (m *FederationOperationalParams) GetBridgeInactivityThreshold() uint64 {
	if m != nil {
		return m.BridgeInactivityThreshold
	}
	return 0
}

func (m *FederationOperationalParams) GetMaxPrunePerBlock() uint64 {
	if m != nil {
		return m.MaxPrunePerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "sparkdream.federation.v1.Params")
	proto.RegisterType((*FederationOperationalParams)(nil), "sparkdream.federation.v1.FederationOperationalParams")
}

func init() {
	proto.RegisterFile("sparkdream/federation/v1/params.proto", fileDescriptor_16ee8151fad3071f)
}

var fileDescriptor_16ee8151fad3071f = []byte{
	// 1472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x72, 0x13, 0xc7,
	0x13, 0xb6, 0xc0, 0x18, 0x7b, 0x8c, 0xff, 0x68, 0x6d, 0xe3, 0x91, 0x0d, 0xb2, 0x81, 0x1f, 0x3f,
	0x1c, 0x08, 0x52, 0x39, 0x54, 0x42, 0xe5, 0x4f, 0xa5, 0x0a, 0x59, 0x50, 0x71, 0xca, 0xc4, 0x62,
	0x6d, 0x4c, 0x55, 0x72, 0xd8, 0x9a, 0xdd, 0x6d, 0x4b, 0x83, 0x76, 0x67, 0x94, 0xd9, 0x59, 0xd9,
	0xe2, 0x11, 0x72, 0xca, 0x31, 0xc7, 0x3c, 0x42, 0x0e, 0xc9, 0x3b, 0x70, 0xa4, 0x72, 0x4a, 0xe5,
	0x40, 0x52, 0x70, 0x48, 0x9e, 0x21, 0xa7, 0xd4, 0xcc, 0xce, 0xae, 0xd6, 0x24, 0x2a, 0xa4, 0x90,
	0x5c, 0x5c, 0xd6, 0x74, 0x7f, 0x5f, 0xcf, 0xf4, 0xf4, 0x37, 0xdd, 0x8b, 0xae, 0x46, 0x1d, 0x22,
	0xda, 0xbe, 0x00, 0x12, 0x56, 0x0f, 0xc1, 0x07, 0x41, 0x24, 0xe5, 0xac, 0xda, 0xdd, 0xac, 0x76,
	0x88, 0x20, 0x61, 0x54, 0xe9, 0x08, 0x2e, 0xb9, 0x85, 0xfb, 0x6e, 0x95, 0xbe, 0x5b, 0xa5, 0xbb,
	0xb9, 0x52, 0x24, 0x21, 0x65, 0xbc, 0xaa, 0xff, 0x26, 0xce, 0x2b, 0x65, 0x8f, 0x47, 0x21, 0x8f,
	0xaa, 0x2e, 0x89, 0xa0, 0xda, 0xdd, 0x74, 0x41, 0x92, 0xcd, 0xaa, 0xc7, 0x29, 0x33, 0xf6, 0x52,
	0x62, 0x77, 0xf4, 0xaf, 0x6a, 0xf2, 0xc3, 0x98, 0x16, 0x9b, 0xbc, 0xc9, 0x93, 0x75, 0xf5, 0x5f,
	0x4a, 0xd8, 0xe4, 0xbc, 0x19, 0x40, 0x55, 0xff, 0x72, 0xe3, 0xc3, 0xaa, 0x1f, 0x9b, 0x0d, 0xe8,
	0x95, 0xcb, 0x7f, 0x94, 0xd0, 0x44, 0x43, 0x6f, 0xd7, 0xda, 0x46, 0xf3, 0x21, 0x65, 0x8e, 0x2b,
	0xa8, 0xdf, 0x04, 0x27, 0x92, 0xa4, 0x0d, 0xb8, 0xb0, 0x5e, 0xd8, 0x98, 0x7e, 0xa7, 0x54, 0x31,
	0x91, 0xd4, 0xb6, 0x2a, 0x66, 0x5b, 0x95, 0x2d, 0x4e, 0x59, 0x6d, 0xfc, 0xe9, 0xf3, 0xb5, 0x31,
	0x7b, 0x36, 0xa4, 0xac, 0xa6, 0x71, 0x7b, 0x0a, 0x66, 0x55, 0xd1, 0x62, 0x48, 0x8e, 0x0d, 0x55,
	0xe4, 0x74, 0x40, 0x38, 0x1d, 0x00, 0x81, 0x4f, 0xad, 0x17, 0x36, 0xc6, 0xed, 0x62, 0x48, 0x8e,
	0x13, 0xef, 0xa8, 0x01, 0xa2, 0x01, 0x20, 0x2c, 0x82, 0x56, 0x4c, 0x5c, 0x01, 0x5d, 0xee, 0xe9,
	0x1d, 0x3a, 0x1e, 0xe7, 0x81, 0xcf, 0x8f, 0x18, 0x3e, 0x6d, 0x76, 0x91, 0x9c, 0xa5, 0x92, 0x9e,
	0xa5, 0x52, 0x37, 0x67, 0xa9, 0x4d, 0xaa, 0x5d, 0x7c, 0xf3, 0xcb, 0x5a, 0xc1, 0xc6, 0x09, 0x8d,
	0x9d, 0xb1, 0x6c, 0x19, 0x12, 0xeb, 0x0b, 0xb4, 0x6c, 0x42, 0xc4, 0xcc, 0xe5, 0xcc, 0xa7, 0xac,
	0xa9, 0x36, 0x46, 0xb9, 0x8f, 0xc7, 0x87, 0xe7, 0x5f, 0x4a, 0x38, 0x1e, 0xa6, 0x14, 0x0d, 0xcd,
	0x60, 0x55, 0xd0, 0x42, 0x9b, 0xf1, 0x23, 0xb5, 0x67, 0x26, 0x81, 0x49, 0x47, 0xf6, 0x3a, 0x10,
	0xe1, 0x33, 0xeb, 0xa7, 0x37, 0xa6, 0xec, 0xa2, 0x36, 0x6d, 0x25, 0x96, 0x7d, 0x65, 0xb0, 0x36,
	0xd1, 0x92, 0x4a, 0x10, 0x65, 0x2e, 0x8f, 0x99, 0xaf, 0x13, 0xe4, 0x06, 0xdc, 0x6b, 0xe3, 0x09,
	0x9d, 0x21, 0x2b, 0x24, 0xc7, 0xdb, 0x89, 0xad, 0x01, 0xa2, 0xa6, 0x2c, 0x29, 0x24, 0x0d, 0xe0,
	0x72, 0xbf, 0xe7, 0x44, 0xf4, 0x09, 0xe0, 0xb3, 0x19, 0xc4, 0x84, 0xa8, 0x71, 0xbf, 0xb7, 0x47,
	0x9f, 0x64, 0xd7, 0x90, 0x42, 0x62, 0x41, 0x13, 0xc4, 0x64, 0x76, 0x0d, 0x06, 0xf1, 0x50, 0x50,
	0x0d, 0xf8, 0x10, 0xad, 0x28, 0x80, 0x4e, 0x80, 0xc7, 0x03, 0x27, 0x04, 0x49, 0x7c, 0x22, 0x49,
	0x02, 0x9b, 0xd2, 0xb0, 0xe5, 0x90, 0x1c, 0x37, 0x8c, 0xc3, 0x7d, 0x63, 0xd7, 0xe0, 0x3a, 0x9a,
	0xce, 0x4e, 0x2f, 0x03, 0x8c, 0x86, 0x4f, 0x2a, 0x32, 0xb8, 0x7d, 0x19, 0x58, 0x3b, 0x68, 0x8e,
	0x48, 0x09, 0x91, 0x4c, 0x6a, 0x40, 0x31, 0x4d, 0x0f, 0xcf, 0x34, 0x9b, 0xc3, 0x2a, 0xb6, 0x77,
	0xd1, 0x72, 0x33, 0xe0, 0x2e, 0x09, 0x1c, 0x75, 0x2e, 0x29, 0xe2, 0x48, 0x3a, 0x9e, 0x00, 0x9f,
	0x4a, 0x7c, 0x6e, 0xbd, 0xb0, 0x31, 0x63, 0x2f, 0x26, 0xe6, 0xfb, 0xe4, 0x78, 0x5f, 0x19, 0xb7,
	0xb4, 0xcd, 0xda, 0x43, 0x0b, 0x89, 0xaf, 0x4f, 0x23, 0x8f, 0xc7, 0x4c, 0x3a, 0x82, 0x48, 0xc0,
	0x33, 0xeb, 0x85, 0x8d, 0xa9, 0xda, 0x15, 0x15, 0xed, 0xe7, 0xe7, 0x6b, 0xab, 0x89, 0x28, 0x22,
	0xbf, 0x5d, 0xa1, 0xbc, 0x1a, 0x12, 0xd9, 0xaa, 0xec, 0x40, 0x93, 0x78, 0xbd, 0x3a, 0x78, 0x76,
	0x51, 0xe3, 0xeb, 0x06, 0x6e, 0x13, 0x09, 0xd6, 0x47, 0x68, 0x55, 0xdf, 0xb9, 0x0f, 0x4c, 0x52,
	0xd9, 0x73, 0x02, 0xca, 0xda, 0x89, 0x36, 0xe2, 0x08, 0x04, 0x9e, 0xd5, 0xfb, 0x51, 0xd9, 0xdd,
	0x36, 0x1e, 0x3b, 0xca, 0xa1, 0x01, 0xe2, 0x61, 0x04, 0x42, 0x6d, 0x29, 0x66, 0x5d, 0x10, 0xf4,
	0x90, 0x82, 0xaf, 0xb1, 0x3a, 0x37, 0x73, 0xc3, 0xe7, 0xa6, 0xd8, 0xc7, 0x2b, 0x66, 0x95, 0x9e,
	0x4f, 0xd0, 0x8c, 0xd7, 0x22, 0x41, 0x00, 0xac, 0x09, 0x9a, 0x6e, 0x7e, 0x78, 0xba, 0x73, 0x19,
	0x52, 0x31, 0x7d, 0x8c, 0x56, 0x8d, 0xba, 0x28, 0x23, 0x9e, 0xa4, 0x5d, 0x75, 0x42, 0xd9, 0x12,
	0x10, 0xb5, 0x78, 0xe0, 0xe3, 0xa2, 0x2e, 0x9d, 0x52, 0xe2, 0xb2, 0x9d, 0x79, 0xec, 0xa7, 0x0e,
	0x56, 0x09, 0x4d, 0x52, 0xd7, 0x73, 0x3a, 0x5c, 0x48, 0x6c, 0xa9, 0x34, 0xdb, 0x67, 0xa9, 0xeb,
	0x35, 0xb8, 0x90, 0x4a, 0x5b, 0xca, 0xe4, 0xb5, 0x08, 0x63, 0x10, 0x38, 0x5d, 0x10, 0x11, 0xe5,
	0x0c, 0x2f, 0x68, 0xaf, 0x22, 0x75, 0xbd, 0xad, 0xc4, 0x72, 0x90, 0x18, 0xac, 0x07, 0xc8, 0xd2,
	0x54, 0xc4, 0x6b, 0x83, 0x74, 0x24, 0x0d, 0x81, 0xc7, 0x12, 0x2f, 0x0e, 0x7f, 0xb2, 0x79, 0x15,
	0x59, 0xa3, 0xf7, 0x13, 0xb0, 0x75, 0x13, 0x2d, 0x24, 0xba, 0x88, 0x19, 0xe4, 0xc4, 0xba, 0xa4,
	0x4f, 0x35, 0xaf, 0x05, 0x11, 0x33, 0xc8, 0xa4, 0x7a, 0x0b, 0x9d, 0x57, 0xee, 0x3c, 0x96, 0xaf,
	0xca, 0xfb, 0xbc, 0x46, 0x28, 0xb2, 0x5d, 0x63, 0xcc, 0x40, 0xbb, 0xa8, 0xa8, 0x8a, 0xcc, 0x09,
	0x68, 0x48, 0xa5, 0x73, 0x44, 0x99, 0xcf, 0x8f, 0xf0, 0xf2, 0xf0, 0xbb, 0x9e, 0x53, 0xe8, 0x1d,
	0x05, 0x7e, 0xa4, 0xb1, 0xd6, 0x6d, 0x84, 0xd5, 0x7b, 0x6e, 0xee, 0x5c, 0x98, 0xea, 0x0f, 0xa0,
	0x0b, 0x01, 0xc6, 0xba, 0xd8, 0x96, 0x42, 0xca, 0x0e, 0x8c, 0x59, 0x97, 0xff, 0x8e, 0x32, 0x5a,
	0x8f, 0x50, 0xf1, 0x04, 0x50, 0x3d, 0x75, 0xb8, 0xa4, 0x6b, 0xff, 0x86, 0xa9, 0xfd, 0xa5, 0xbf,
	0xd6, 0xfe, 0x36, 0x93, 0x3f, 0x7e, 0x7f, 0x13, 0x99, 0x4e, 0xb1, 0xcd, 0xa4, 0x3d, 0x97, 0xa3,
	0xaf, 0x71, 0xe6, 0x5b, 0x6d, 0xb4, 0x9a, 0x91, 0x0a, 0xf0, 0x78, 0x17, 0x44, 0xbe, 0x48, 0x56,
	0x46, 0x0f, 0x51, 0x4a, 0xf9, 0x6c, 0x43, 0xd7, 0xaf, 0x28, 0x07, 0x2d, 0x65, 0xc1, 0xa2, 0x80,
	0x44, 0x2d, 0x87, 0x84, 0x4a, 0x8b, 0x78, 0x75, 0xf4, 0x30, 0x0b, 0x29, 0xd3, 0x9e, 0x22, 0xba,
	0xa3, 0x79, 0xac, 0x7d, 0x64, 0x96, 0x4d, 0xbb, 0x32, 0x57, 0x76, 0x61, 0xf8, 0x2b, 0xb3, 0xf2,
	0x78, 0x73, 0x6b, 0x9f, 0xa1, 0xf9, 0xbe, 0x24, 0x0d, 0xe5, 0xc5, 0x11, 0xaa, 0x20, 0x03, 0x1b,
	0xbe, 0x7a, 0x5e, 0xe2, 0x87, 0x00, 0xb8, 0x3c, 0x5c, 0x4b, 0xef, 0xcb, 0xfb, 0x1e, 0x80, 0x6a,
	0x9e, 0x7d, 0x96, 0xc7, 0xb1, 0xe8, 0x39, 0x3e, 0x10, 0x3f, 0xa0, 0x0c, 0xf0, 0xda, 0x08, 0xcd,
	0x33, 0xe3, 0xf8, 0x34, 0x16, 0xbd, 0xba, 0x61, 0x50, 0xcd, 0x3f, 0xbb, 0x29, 0x1f, 0x42, 0x7e,
	0xb2, 0xf9, 0xaf, 0x8f, 0xd0, 0xfc, 0x53, 0x9a, 0xba, 0x61, 0xc9, 0x9a, 0xff, 0x63, 0xb4, 0x96,
	0x85, 0x50, 0x75, 0x22, 0x63, 0xc1, 0x1c, 0x75, 0xf4, 0x7e, 0x9c, 0x4b, 0xc3, 0xc7, 0xb9, 0x90,
	0x72, 0xed, 0x1a, 0xaa, 0x1a, 0x89, 0x20, 0x8b, 0xf5, 0x3e, 0x2a, 0xc5, 0x9d, 0x16, 0x04, 0xbe,
	0x23, 0xb9, 0x23, 0x20, 0x02, 0x99, 0x85, 0x8c, 0xf0, 0x65, 0x2d, 0xbc, 0xf3, 0x89, 0xc3, 0x3e,
	0xb7, 0x95, 0x39, 0x65, 0x89, 0xac, 0xf7, 0xd0, 0xb2, 0x52, 0x1e, 0x74, 0xb8, 0xd7, 0x72, 0xf2,
	0xc5, 0x11, 0xe1, 0x2b, 0x99, 0x62, 0xef, 0x2a, 0xeb, 0x41, 0xde, 0x68, 0x3d, 0x42, 0x4b, 0x27,
	0x14, 0x4b, 0x3c, 0x2f, 0x16, 0xc4, 0xeb, 0xe1, 0xff, 0x0d, 0xdf, 0xb1, 0x16, 0x72, 0x6a, 0xbd,
	0x63, 0xf0, 0x8a, 0x98, 0x77, 0xd4, 0xc8, 0xca, 0x95, 0x62, 0x8f, 0x88, 0xf0, 0x9d, 0xa8, 0x45,
	0x04, 0xe0, 0xab, 0x23, 0x10, 0xa7, 0x0c, 0xb6, 0x26, 0xd8, 0x53, 0xf8, 0x13, 0xea, 0xd4, 0xb3,
	0xb1, 0xa1, 0xc7, 0xff, 0x7f, 0x03, 0x75, 0xd6, 0x15, 0x51, 0x12, 0xc5, 0x92, 0xe8, 0x92, 0x7a,
	0x83, 0x5f, 0x09, 0x12, 0x52, 0x26, 0xf5, 0x73, 0xac, 0x53, 0x8c, 0xaf, 0x8d, 0x1e, 0xec, 0x42,
	0x48, 0x8e, 0x0f, 0xf2, 0xf1, 0xee, 0x53, 0x26, 0x1b, 0x20, 0xf4, 0xad, 0x58, 0x57, 0xd1, 0x2c,
	0x11, 0x2e, 0x95, 0x20, 0x9c, 0x2f, 0x63, 0x2e, 0xe2, 0x10, 0x6f, 0xe8, 0x7b, 0x9b, 0x31, 0xab,
	0x0f, 0xf4, 0xa2, 0xe5, 0xa0, 0x52, 0xea, 0x26, 0x20, 0xe2, 0x41, 0x9c, 0x7f, 0x40, 0xde, 0x1a,
	0xbe, 0x10, 0x97, 0x0d, 0x8b, 0x9d, 0x91, 0x18, 0xd5, 0xe7, 0x02, 0x40, 0xe4, 0x91, 0xe0, 0xc4,
	0x0b, 0x75, 0x7d, 0xf4, 0x00, 0x77, 0x33, 0x12, 0x13, 0xe0, 0x1e, 0x9a, 0xcd, 0x11, 0xab, 0x77,
	0xe5, 0xc6, 0x70, 0xef, 0xca, 0x4c, 0x1f, 0xa6, 0x1e, 0x16, 0x1b, 0x59, 0xfd, 0x87, 0x25, 0xd3,
	0xe2, 0xdb, 0x23, 0x4c, 0x35, 0x19, 0x3c, 0x15, 0xe0, 0x07, 0xd7, 0x7e, 0xff, 0x76, 0xad, 0xf0,
	0xd5, 0x6f, 0xdf, 0x5d, 0x2f, 0xe7, 0xbe, 0xd0, 0x8e, 0xf3, 0xdf, 0x68, 0xc9, 0x17, 0xcf, 0xe5,
	0x1f, 0xce, 0xa0, 0xd5, 0x7b, 0xd9, 0xea, 0x6e, 0xc7, 0xfc, 0x43, 0x02, 0xf3, 0x45, 0x34, 0x70,
	0x4a, 0x2f, 0x0c, 0x9c, 0xd2, 0x07, 0xb7, 0xfe, 0x53, 0x83, 0x5b, 0xff, 0xc0, 0xd1, 0xfe, 0xf4,
	0xc8, 0xa3, 0xfd, 0xf8, 0x3f, 0x1b, 0xed, 0xcf, 0x8c, 0x34, 0xda, 0x4f, 0xfc, 0x6b, 0xa3, 0xfd,
	0xd9, 0xff, 0x64, 0xb4, 0x9f, 0x1c, 0x7d, 0xb4, 0x9f, 0x7a, 0xa3, 0xd1, 0xfe, 0x35, 0xd3, 0x2f,
	0x7a, 0xdd, 0xf4, 0x3b, 0x60, 0xbe, 0x9c, 0xfe, 0xfb, 0xf9, 0xb2, 0x76, 0xfb, 0xe9, 0x8b, 0x72,
	0xe1, 0xd9, 0x8b, 0x72, 0xe1, 0xd7, 0x17, 0xe5, 0xc2, 0xd7, 0x2f, 0xcb, 0x63, 0xcf, 0x5e, 0x96,
	0xc7, 0x7e, 0x7a, 0x59, 0x1e, 0xfb, 0xfc, 0xe2, 0xa0, 0x8a, 0xd7, 0xdf, 0xa3, 0xee, 0x84, 0x4e,
	0xf0, 0xad, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xef, 0x3c, 0x18, 0x51, 0xbb, 0x10, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinBridgeStake.Equal(&that1.MinBridgeStake) {
		return false
	}
	if this.MaxBridgesPerPeer != that1.MaxBridgesPerPeer {
		return false
	}
	if this.BridgeRevocationCooldown != that1.BridgeRevocationCooldown {
		return false
	}
	if this.BridgeUnbondingPeriod != that1.BridgeUnbondingPeriod {
		return false
	}
	if len(this.KnownContentTypes) != len(that1.KnownContentTypes) {
		return false
	}
	for i := range this.KnownContentTypes {
		if this.KnownContentTypes[i] != that1.KnownContentTypes[i] {
			return false
		}
	}
	if this.MaxInboundPerBlock != that1.MaxInboundPerBlock {
		return false
	}
	if this.MaxContentBodySize != that1.MaxContentBodySize {
		return false
	}
	if this.MaxContentUriSize != that1.MaxContentUriSize {
		return false
	}
	if this.MaxProtocolMetadataSize != that1.MaxProtocolMetadataSize {
		return false
	}
	if this.ContentTtl != that1.ContentTtl {
		return false
	}
	if this.AttestationTtl != that1.AttestationTtl {
		return false
	}
	if this.GlobalMaxTrustCredit != that1.GlobalMaxTrustCredit {
		return false
	}
	if !this.TrustDiscountRate.Equal(that1.TrustDiscountRate) {
		return false
	}
	if this.MaxIdentityLinksPerUser != that1.MaxIdentityLinksPerUser {
		return false
	}
	if this.UnverifiedLinkTtl != that1.UnverifiedLinkTtl {
		return false
	}
	if this.ChallengeTtl != that1.ChallengeTtl {
		return false
	}
	if this.BridgeInactivityThreshold != that1.BridgeInactivityThreshold {
		return false
	}
	if this.IbcPort != that1.IbcPort {
		return false
	}
	if this.IbcChannelVersion != that1.IbcChannelVersion {
		return false
	}
	if this.IbcPacketTimeout != that1.IbcPacketTimeout {
		return false
	}
	if this.MaxPrunePerBlock != that1.MaxPrunePerBlock {
		return false
	}
	if this.MaxOutboundPerBlock != that1.MaxOutboundPerBlock {
		return false
	}
	if this.RateLimitWindow != that1.RateLimitWindow {
		return false
	}
	if this.MinVerifierTrustLevel != that1.MinVerifierTrustLevel {
		return false
	}
	if !this.MinVerifierBond.Equal(that1.MinVerifierBond) {
		return false
	}
	if !this.VerifierRecoveryThreshold.Equal(that1.VerifierRecoveryThreshold) {
		return false
	}
	if !this.VerifierSlashAmount.Equal(that1.VerifierSlashAmount) {
		return false
	}
	if this.VerificationWindow != that1.VerificationWindow {
		return false
	}
	if this.ChallengeWindow != that1.ChallengeWindow {
		return false
	}
	if !this.ChallengeFee.Equal(&that1.ChallengeFee) {
		return false
	}
	if this.ChallengeJuryDeadline != that1.ChallengeJuryDeadline {
		return false
	}
	if this.VerifierDemotionCooldown != that1.VerifierDemotionCooldown {
		return false
	}
	if this.VerifierOverturnBaseCooldown != that1.VerifierOverturnBaseCooldown {
		return false
	}
	if this.UpheldToResetOverturns != that1.UpheldToResetOverturns {
		return false
	}
	if this.MinEpochVerifications != that1.MinEpochVerifications {
		return false
	}
	if !this.MinVerifierAccuracy.Equal(that1.MinVerifierAccuracy) {
		return false
	}
	if !this.OperatorRewardShare.Equal(that1.OperatorRewardShare) {
		return false
	}
	if !this.VerifierDreamReward.Equal(that1.VerifierDreamReward) {
		return false
	}
	if !this.MaxVerifierDreamMintPerEpoch.Equal(that1.MaxVerifierDreamMintPerEpoch) {
		return false
	}
	if this.ArbiterQuorum != that1.ArbiterQuorum {
		return false
	}
	if this.ArbiterResolutionWindow != that1.ArbiterResolutionWindow {
		return false
	}
	if this.ArbiterEscalationWindow != that1.ArbiterEscalationWindow {
		return false
	}
	if !this.EscalationFee.Equal(&that1.EscalationFee) {
		return false
	}
	if this.ChallengeCooldown != that1.ChallengeCooldown {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChallengeCooldown, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeCooldown):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xe2
	{
		size, err := m.EscalationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xda
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ArbiterEscalationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ArbiterEscalationWindow):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xd2
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ArbiterResolutionWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ArbiterResolutionWindow):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintParams(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xca
	if m.ArbiterQuorum != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ArbiterQuorum))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc0
	}
	{
		size := m.MaxVerifierDreamMintPerEpoch.Size()
		i -= size
		if _, err := m.MaxVerifierDreamMintPerEpoch.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xba
	{
		size := m.VerifierDreamReward.Size()
		i -= size
		if _, err := m.VerifierDreamReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xb2
	{
		size := m.OperatorRewardShare.Size()
		i -= size
		if _, err := m.OperatorRewardShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xaa
	{
		size := m.MinVerifierAccuracy.Size()
		i -= size
		if _, err := m.MinVerifierAccuracy.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0xa2
	if m.MinEpochVerifications != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinEpochVerifications))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.UpheldToResetOverturns != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpheldToResetOverturns))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x90
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.VerifierOverturnBaseCooldown, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerifierOverturnBaseCooldown):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintParams(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x8a
	n6, err6 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.VerifierDemotionCooldown, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerifierDemotionCooldown):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintParams(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x82
	n7, err7 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChallengeJuryDeadline, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeJuryDeadline):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintParams(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xfa
	{
		size, err := m.ChallengeFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xf2
	n9, err9 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChallengeWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeWindow):])
	if err9 != nil {
		return 0, err9
	}
	i -= n9
	i = encodeVarintParams(dAtA, i, uint64(n9))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xea
	n10, err10 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.VerificationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerificationWindow):])
	if err10 != nil {
		return 0, err10
	}
	i -= n10
	i = encodeVarintParams(dAtA, i, uint64(n10))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xe2
	{
		size := m.VerifierSlashAmount.Size()
		i -= size
		if _, err := m.VerifierSlashAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xda
	{
		size := m.VerifierRecoveryThreshold.Size()
		i -= size
		if _, err := m.VerifierRecoveryThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xd2
	{
		size := m.MinVerifierBond.Size()
		i -= size
		if _, err := m.MinVerifierBond.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xca
	if m.MinVerifierTrustLevel != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinVerifierTrustLevel))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	n11, err11 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.RateLimitWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.RateLimitWindow):])
	if err11 != nil {
		return 0, err11
	}
	i -= n11
	i = encodeVarintParams(dAtA, i, uint64(n11))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xba
	if m.MaxOutboundPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOutboundPerBlock))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.MaxPrunePerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPrunePerBlock))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	n12, err12 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.IbcPacketTimeout, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.IbcPacketTimeout):])
	if err12 != nil {
		return 0, err12
	}
	i -= n12
	i = encodeVarintParams(dAtA, i, uint64(n12))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xa2
	if len(m.IbcChannelVersion) > 0 {
		i -= len(m.IbcChannelVersion)
		copy(dAtA[i:], m.IbcChannelVersion)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IbcChannelVersion)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.IbcPort) > 0 {
		i -= len(m.IbcPort)
		copy(dAtA[i:], m.IbcPort)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IbcPort)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.BridgeInactivityThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BridgeInactivityThreshold))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	n13, err13 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChallengeTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeTtl):])
	if err13 != nil {
		return 0, err13
	}
	i -= n13
	i = encodeVarintParams(dAtA, i, uint64(n13))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	n14, err14 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.UnverifiedLinkTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnverifiedLinkTtl):])
	if err14 != nil {
		return 0, err14
	}
	i -= n14
	i = encodeVarintParams(dAtA, i, uint64(n14))
	i--
	dAtA[i] = 0x7a
	if m.MaxIdentityLinksPerUser != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxIdentityLinksPerUser))
		i--
		dAtA[i] = 0x70
	}
	{
		size := m.TrustDiscountRate.Size()
		i -= size
		if _, err := m.TrustDiscountRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if m.GlobalMaxTrustCredit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.GlobalMaxTrustCredit))
		i--
		dAtA[i] = 0x60
	}
	n15, err15 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.AttestationTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AttestationTtl):])
	if err15 != nil {
		return 0, err15
	}
	i -= n15
	i = encodeVarintParams(dAtA, i, uint64(n15))
	i--
	dAtA[i] = 0x5a
	n16, err16 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ContentTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ContentTtl):])
	if err16 != nil {
		return 0, err16
	}
	i -= n16
	i = encodeVarintParams(dAtA, i, uint64(n16))
	i--
	dAtA[i] = 0x52
	if m.MaxProtocolMetadataSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxProtocolMetadataSize))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxContentUriSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContentUriSize))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxContentBodySize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContentBodySize))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxInboundPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxInboundPerBlock))
		i--
		dAtA[i] = 0x30
	}
	if len(m.KnownContentTypes) > 0 {
		for iNdEx := len(m.KnownContentTypes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.KnownContentTypes[iNdEx])
			copy(dAtA[i:], m.KnownContentTypes[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.KnownContentTypes[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	n17, err17 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.BridgeUnbondingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BridgeUnbondingPeriod):])
	if err17 != nil {
		return 0, err17
	}
	i -= n17
	i = encodeVarintParams(dAtA, i, uint64(n17))
	i--
	dAtA[i] = 0x22
	n18, err18 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.BridgeRevocationCooldown, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BridgeRevocationCooldown):])
	if err18 != nil {
		return 0, err18
	}
	i -= n18
	i = encodeVarintParams(dAtA, i, uint64(n18))
	i--
	dAtA[i] = 0x1a
	if m.MaxBridgesPerPeer != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBridgesPerPeer))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.MinBridgeStake.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FederationOperationalParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FederationOperationalParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FederationOperationalParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxPrunePerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPrunePerBlock))
		i--
		dAtA[i] = 0x58
	}
	if m.BridgeInactivityThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BridgeInactivityThreshold))
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.TrustDiscountRate.Size()
		i -= size
		if _, err := m.TrustDiscountRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.GlobalMaxTrustCredit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.GlobalMaxTrustCredit))
		i--
		dAtA[i] = 0x40
	}
	n20, err20 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.AttestationTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AttestationTtl):])
	if err20 != nil {
		return 0, err20
	}
	i -= n20
	i = encodeVarintParams(dAtA, i, uint64(n20))
	i--
	dAtA[i] = 0x3a
	n21, err21 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ContentTtl, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ContentTtl):])
	if err21 != nil {
		return 0, err21
	}
	i -= n21
	i = encodeVarintParams(dAtA, i, uint64(n21))
	i--
	dAtA[i] = 0x32
	if m.MaxProtocolMetadataSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxProtocolMetadataSize))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxContentUriSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContentUriSize))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxContentBodySize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContentBodySize))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxOutboundPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOutboundPerBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxInboundPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxInboundPerBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinBridgeStake.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxBridgesPerPeer != 0 {
		n += 1 + sovParams(uint64(m.MaxBridgesPerPeer))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BridgeRevocationCooldown)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BridgeUnbondingPeriod)
	n += 1 + l + sovParams(uint64(l))
	if len(m.KnownContentTypes) > 0 {
		for _, s := range m.KnownContentTypes {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MaxInboundPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxInboundPerBlock))
	}
	if m.MaxContentBodySize != 0 {
		n += 1 + sovParams(uint64(m.MaxContentBodySize))
	}
	if m.MaxContentUriSize != 0 {
		n += 1 + sovParams(uint64(m.MaxContentUriSize))
	}
	if m.MaxProtocolMetadataSize != 0 {
		n += 1 + sovParams(uint64(m.MaxProtocolMetadataSize))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ContentTtl)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AttestationTtl)
	n += 1 + l + sovParams(uint64(l))
	if m.GlobalMaxTrustCredit != 0 {
		n += 1 + sovParams(uint64(m.GlobalMaxTrustCredit))
	}
	l = m.TrustDiscountRate.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxIdentityLinksPerUser != 0 {
		n += 1 + sovParams(uint64(m.MaxIdentityLinksPerUser))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnverifiedLinkTtl)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeTtl)
	n += 2 + l + sovParams(uint64(l))
	if m.BridgeInactivityThreshold != 0 {
		n += 2 + sovParams(uint64(m.BridgeInactivityThreshold))
	}
	l = len(m.IbcPort)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	l = len(m.IbcChannelVersion)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.IbcPacketTimeout)
	n += 2 + l + sovParams(uint64(l))
	if m.MaxPrunePerBlock != 0 {
		n += 2 + sovParams(uint64(m.MaxPrunePerBlock))
	}
	if m.MaxOutboundPerBlock != 0 {
		n += 2 + sovParams(uint64(m.MaxOutboundPerBlock))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.RateLimitWindow)
	n += 2 + l + sovParams(uint64(l))
	if m.MinVerifierTrustLevel != 0 {
		n += 2 + sovParams(uint64(m.MinVerifierTrustLevel))
	}
	l = m.MinVerifierBond.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.VerifierRecoveryThreshold.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.VerifierSlashAmount.Size()
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerificationWindow)
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeWindow)
	n += 2 + l + sovParams(uint64(l))
	l = m.ChallengeFee.Size()
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeJuryDeadline)
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerifierDemotionCooldown)
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VerifierOverturnBaseCooldown)
	n += 2 + l + sovParams(uint64(l))
	if m.UpheldToResetOverturns != 0 {
		n += 2 + sovParams(uint64(m.UpheldToResetOverturns))
	}
	if m.MinEpochVerifications != 0 {
		n += 2 + sovParams(uint64(m.MinEpochVerifications))
	}
	l = m.MinVerifierAccuracy.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.OperatorRewardShare.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.VerifierDreamReward.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.MaxVerifierDreamMintPerEpoch.Size()
	n += 2 + l + sovParams(uint64(l))
	if m.ArbiterQuorum != 0 {
		n += 2 + sovParams(uint64(m.ArbiterQuorum))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ArbiterResolutionWindow)
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ArbiterEscalationWindow)
	n += 2 + l + sovParams(uint64(l))
	l = m.EscalationFee.Size()
	n += 2 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengeCooldown)
	n += 2 + l + sovParams(uint64(l))
	return n
}

func (m *FederationOperationalParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxInboundPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxInboundPerBlock))
	}
	if m.MaxOutboundPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxOutboundPerBlock))
	}
	if m.MaxContentBodySize != 0 {
		n += 1 + sovParams(uint64(m.MaxContentBodySize))
	}
	if m.MaxContentUriSize != 0 {
		n += 1 + sovParams(uint64(m.MaxContentUriSize))
	}
	if m.MaxProtocolMetadataSize != 0 {
		n += 1 + sovParams(uint64(m.MaxProtocolMetadataSize))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ContentTtl)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AttestationTtl)
	n += 1 + l + sovParams(uint64(l))
	if m.GlobalMaxTrustCredit != 0 {
		n += 1 + sovParams(uint64(m.GlobalMaxTrustCredit))
	}
	l = m.TrustDiscountRate.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.BridgeInactivityThreshold != 0 {
		n += 1 + sovParams(uint64(m.BridgeInactivityThreshold))
	}
	if m.MaxPrunePerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxPrunePerBlock))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBridgeStake", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBridgeStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBridgesPerPeer", wireType)
			}
			m.MaxBridgesPerPeer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBridgesPerPeer |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeRevocationCooldown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.BridgeRevocationCooldown, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeUnbondingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.BridgeUnbondingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KnownContentTypes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KnownContentTypes = append(m.KnownContentTypes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxInboundPerBlock", wireType)
			}
			m.MaxInboundPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxInboundPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContentBodySize", wireType)
			}
			m.MaxContentBodySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContentBodySize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContentUriSize", wireType)
			}
			m.MaxContentUriSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContentUriSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProtocolMetadataSize", wireType)
			}
			m.MaxProtocolMetadataSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProtocolMetadataSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ContentTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.AttestationTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMaxTrustCredit", wireType)
			}
			m.GlobalMaxTrustCredit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GlobalMaxTrustCredit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustDiscountRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TrustDiscountRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIdentityLinksPerUser", wireType)
			}
			m.MaxIdentityLinksPerUser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxIdentityLinksPerUser |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnverifiedLinkTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.UnverifiedLinkTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChallengeTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeInactivityThreshold", wireType)
			}
			m.BridgeInactivityThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeInactivityThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcPort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcPort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcChannelVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcChannelVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcPacketTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.IbcPacketTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrunePerBlock", wireType)
			}
			m.MaxPrunePerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPrunePerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOutboundPerBlock", wireType)
			}
			m.MaxOutboundPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOutboundPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimitWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.RateLimitWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVerifierTrustLevel", wireType)
			}
			m.MinVerifierTrustLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinVerifierTrustLevel |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVerifierBond", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinVerifierBond.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierRecoveryThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifierRecoveryThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierSlashAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifierSlashAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.VerificationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChallengeWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ChallengeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeJuryDeadline", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChallengeJuryDeadline, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierDemotionCooldown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.VerifierDemotionCooldown, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierOverturnBaseCooldown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.VerifierOverturnBaseCooldown, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpheldToResetOverturns", wireType)
			}
			m.UpheldToResetOverturns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpheldToResetOverturns |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinEpochVerifications", wireType)
			}
			m.MinEpochVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinEpochVerifications |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVerifierAccuracy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinVerifierAccuracy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 37:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorRewardShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OperatorRewardShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 38:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierDreamReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifierDreamReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 39:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVerifierDreamMintPerEpoch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxVerifierDreamMintPerEpoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbiterQuorum", wireType)
			}
			m.ArbiterQuorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArbiterQuorum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbiterResolutionWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ArbiterResolutionWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 42:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbiterEscalationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ArbiterEscalationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 43:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscalationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EscalationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 44:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeCooldown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChallengeCooldown, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FederationOperationalParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FederationOperationalParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FederationOperationalParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxInboundPerBlock", wireType)
			}
			m.MaxInboundPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxInboundPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOutboundPerBlock", wireType)
			}
			m.MaxOutboundPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOutboundPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContentBodySize", wireType)
			}
			m.MaxContentBodySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContentBodySize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContentUriSize", wireType)
			}
			m.MaxContentUriSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContentUriSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProtocolMetadataSize", wireType)
			}
			m.MaxProtocolMetadataSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProtocolMetadataSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ContentTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationTtl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.AttestationTtl, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMaxTrustCredit", wireType)
			}
			m.GlobalMaxTrustCredit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GlobalMaxTrustCredit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustDiscountRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TrustDiscountRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeInactivityThreshold", wireType)
			}
			m.BridgeInactivityThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeInactivityThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrunePerBlock", wireType)
			}
			m.MaxPrunePerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPrunePerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
