// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sparkdream/federation/v1/verifier_activity.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VerifierActivity holds federation-specific per-verifier counters. The
// generic bond/status/activity record lives in x/rep as BondedRole
// (ROLE_TYPE_FEDERATION_VERIFIER) — this proto only tracks what's
// federation-specific: verification counts and dispute outcomes.
type VerifierActivity struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Lifetime metrics
	TotalVerifications        uint64 `protobuf:"varint,2,opt,name=total_verifications,json=totalVerifications,proto3" json:"total_verifications,omitempty"`
	UpheldVerifications       uint64 `protobuf:"varint,3,opt,name=upheld_verifications,json=upheldVerifications,proto3" json:"upheld_verifications,omitempty"`
	OverturnedVerifications   uint64 `protobuf:"varint,4,opt,name=overturned_verifications,json=overturnedVerifications,proto3" json:"overturned_verifications,omitempty"`
	UnchallengedVerifications uint64 `protobuf:"varint,5,opt,name=unchallenged_verifications,json=unchallengedVerifications,proto3" json:"unchallenged_verifications,omitempty"`
	// Epoch metrics
	EpochVerifications      uint64 `protobuf:"varint,6,opt,name=epoch_verifications,json=epochVerifications,proto3" json:"epoch_verifications,omitempty"`
	EpochChallengesResolved uint64 `protobuf:"varint,7,opt,name=epoch_challenges_resolved,json=epochChallengesResolved,proto3" json:"epoch_challenges_resolved,omitempty"`
	// Consecutive-outcome tracking for demotion triggers. Slash streak beyond
	// UpheldToResetOverturns consecutive-overturn is the demotion signal.
	ConsecutiveOverturns uint64 `protobuf:"varint,8,opt,name=consecutive_overturns,json=consecutiveOverturns,proto3" json:"consecutive_overturns,omitempty"`
	ConsecutiveUpheld    uint64 `protobuf:"varint,9,opt,name=consecutive_upheld,json=consecutiveUpheld,proto3" json:"consecutive_upheld,omitempty"`
	// overturn_cooldown_until is the unix timestamp during which the verifier
	// cannot submit new verifications after an overturn. Managed by the
	// federation challenge-resolution flow.
	OverturnCooldownUntil int64 `protobuf:"varint,10,opt,name=overturn_cooldown_until,json=overturnCooldownUntil,proto3" json:"overturn_cooldown_until,omitempty"`
	// slash_count is the lifetime number of times this verifier has been
	// slashed (overturn verdicts).
	SlashCount uint64 `protobuf:"varint,11,opt,name=slash_count,json=slashCount,proto3" json:"slash_count,omitempty"`
}

func (m *VerifierActivity) Reset()         { *m = VerifierActivity{} }
func (m *VerifierActivity) String() string { return proto.CompactTextString(m) }
func (*VerifierActivity) ProtoMessage()    {}
func (*VerifierActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff99916355787d20, []int{0}
}
func (m *VerifierActivity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifierActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifierActivity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifierActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierActivity.Merge(m, src)
}
func (m *VerifierActivity) XXX_Size() int {
	return m.Size()
}
func (m *VerifierActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierActivity.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierActivity proto.InternalMessageInfo

func (m *VerifierActivity) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *VerifierActivity) GetTotalVerifications() uint64 {
	if m != nil {
		return m.TotalVerifications
	}
	return 0
}

func (m *VerifierActivity) GetUpheldVerifications() uint64 {
	if m != nil {
		return m.UpheldVerifications
	}
	return 0
}

func (m *VerifierActivity) GetOverturnedVerifications() uint64 {
	if m != nil {
		return m.OverturnedVerifications
	}
	return 0
}

func (m *VerifierActivity) GetUnchallengedVerifications() uint64 {
	if m != nil {
		return m.UnchallengedVerifications
	}
	return 0
}

func (m *VerifierActivity) GetEpochVerifications() uint64 {
	if m != nil {
		return m.EpochVerifications
	}
	return 0
}

func (m *VerifierActivity) GetEpochChallengesResolved() uint64 {
	if m != nil {
		return m.EpochChallengesResolved
	}
	return 0
}

func (m *VerifierActivity) GetConsecutiveOverturns() uint64 {
	if m != nil {
		return m.ConsecutiveOverturns
	}
	return 0
}

func (m *VerifierActivity) GetConsecutiveUpheld() uint64 {
	if m != nil {
		return m.ConsecutiveUpheld
	}
	return 0
}

func (m *VerifierActivity) GetOverturnCooldownUntil() int64 {
	if m != nil {
		return m.OverturnCooldownUntil
	}
	return 0
}

func (m *VerifierActivity) GetSlashCount() uint64 {
	if m != nil {
		return m.SlashCount
	}
	return 0
}

func init() {
	proto.RegisterType((*VerifierActivity)(nil), "sparkdream.federation.v1.VerifierActivity")
}

func init() {
	proto.RegisterFile("sparkdream/federation/v1/verifier_activity.proto", fileDescriptor_ff99916355787d20)
}

var fileDescriptor_ff99916355787d20 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x1b, 0x56, 0x36, 0xe6, 0x5d, 0xc0, 0xed, 0x84, 0x3b, 0x89, 0x50, 0x71, 0xea, 0x65,
	0x0d, 0x65, 0x12, 0x08, 0x24, 0x0e, 0x5b, 0x1f, 0x00, 0x29, 0x68, 0x3b, 0x70, 0xb1, 0x8c, 0xf3,
	0x6d, 0xb1, 0xf0, 0xec, 0xc8, 0x76, 0x02, 0x7d, 0x0b, 0x1e, 0x86, 0x87, 0xe0, 0x84, 0x2a, 0x4e,
	0x1c, 0x51, 0xfb, 0x22, 0xa8, 0x76, 0xd2, 0x26, 0xe5, 0x18, 0xff, 0xfe, 0xbf, 0x7f, 0xec, 0x4f,
	0x1f, 0x7a, 0x69, 0x0b, 0x66, 0xbe, 0x64, 0x06, 0xd8, 0x7d, 0x72, 0x0b, 0x19, 0x18, 0xe6, 0x84,
	0x56, 0x49, 0x35, 0x4b, 0x2a, 0x30, 0xe2, 0x56, 0x80, 0xa1, 0x8c, 0x3b, 0x51, 0x09, 0xb7, 0x98,
	0x16, 0x46, 0x3b, 0x8d, 0xc9, 0xce, 0x98, 0xee, 0x8c, 0x69, 0x35, 0x3b, 0x1b, 0x71, 0x6d, 0xef,
	0xb5, 0xa5, 0x3e, 0x97, 0x84, 0x8f, 0x20, 0xbd, 0xf8, 0xd5, 0x47, 0x8f, 0x6f, 0xea, 0xc2, 0xcb,
	0xba, 0x0f, 0xbf, 0x42, 0x47, 0x2c, 0xcb, 0x0c, 0x58, 0x4b, 0xa2, 0x71, 0x34, 0x39, 0xbe, 0x22,
	0xbf, 0x7f, 0x9c, 0x0f, 0x6b, 0xef, 0x32, 0x90, 0x8f, 0xce, 0x08, 0x75, 0x97, 0x36, 0x41, 0x9c,
	0xa0, 0x81, 0xd3, 0x8e, 0x49, 0x1a, 0xae, 0xc7, 0xfd, 0xcf, 0x2d, 0x79, 0x30, 0x8e, 0x26, 0xfd,
	0x14, 0x7b, 0x74, 0xd3, 0x26, 0x78, 0x86, 0x86, 0x65, 0x91, 0x83, 0xcc, 0xf6, 0x8c, 0x03, 0x6f,
	0x0c, 0x02, 0xeb, 0x2a, 0x6f, 0x11, 0xd1, 0x15, 0x18, 0x57, 0x1a, 0x05, 0xfb, 0x5a, 0xdf, 0x6b,
	0x4f, 0x77, 0xbc, 0xab, 0xbe, 0x47, 0x67, 0xa5, 0xe2, 0x39, 0x93, 0x12, 0xd4, 0xdd, 0x7f, 0xf2,
	0x43, 0x2f, 0x8f, 0xda, 0x89, 0xae, 0x9e, 0xa0, 0x01, 0x14, 0x9a, 0xe7, 0x7b, 0xde, 0x61, 0x78,
	0x9d, 0x47, 0x5d, 0xe1, 0x1d, 0x1a, 0x05, 0x61, 0xdb, 0x68, 0xa9, 0x01, 0xab, 0x65, 0x05, 0x19,
	0x39, 0x0a, 0x77, 0xf5, 0x81, 0xf9, 0x96, 0xa7, 0x35, 0xc6, 0x17, 0xe8, 0x94, 0x6b, 0x65, 0x81,
	0x97, 0x4e, 0x54, 0x40, 0x9b, 0x27, 0x59, 0xf2, 0xc8, 0x7b, 0xc3, 0x16, 0xfc, 0xd0, 0x30, 0x7c,
	0x8e, 0x70, 0x5b, 0x0a, 0xe3, 0x23, 0xc7, 0xde, 0x78, 0xd2, 0x22, 0xd7, 0x1e, 0xe0, 0xd7, 0x68,
	0x3b, 0x2a, 0xca, 0xb5, 0x96, 0x99, 0xfe, 0xaa, 0x68, 0xa9, 0x9c, 0x90, 0x04, 0x8d, 0xa3, 0xc9,
	0x41, 0x7a, 0xda, 0xe0, 0x79, 0x4d, 0xaf, 0x37, 0x10, 0x3f, 0x47, 0x27, 0x56, 0x32, 0x9b, 0x53,
	0xae, 0x4b, 0xe5, 0xc8, 0x89, 0xef, 0x47, 0xfe, 0x68, 0xbe, 0x39, 0xb9, 0x7a, 0xf3, 0x73, 0x15,
	0x47, 0xcb, 0x55, 0x1c, 0xfd, 0x5d, 0xc5, 0xd1, 0xf7, 0x75, 0xdc, 0x5b, 0xae, 0xe3, 0xde, 0x9f,
	0x75, 0xdc, 0xfb, 0xf4, 0xac, 0xb5, 0xd1, 0xdf, 0xda, 0x3b, 0xed, 0x16, 0x05, 0xd8, 0xcf, 0x87,
	0x7e, 0x21, 0x2f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xa3, 0x17, 0x56, 0xf9, 0x02, 0x00,
	0x00,
}

func (m *VerifierActivity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifierActivity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifierActivity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlashCount != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.SlashCount))
		i--
		dAtA[i] = 0x58
	}
	if m.OverturnCooldownUntil != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.OverturnCooldownUntil))
		i--
		dAtA[i] = 0x50
	}
	if m.ConsecutiveUpheld != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.ConsecutiveUpheld))
		i--
		dAtA[i] = 0x48
	}
	if m.ConsecutiveOverturns != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.ConsecutiveOverturns))
		i--
		dAtA[i] = 0x40
	}
	if m.EpochChallengesResolved != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.EpochChallengesResolved))
		i--
		dAtA[i] = 0x38
	}
	if m.EpochVerifications != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.EpochVerifications))
		i--
		dAtA[i] = 0x30
	}
	if m.UnchallengedVerifications != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.UnchallengedVerifications))
		i--
		dAtA[i] = 0x28
	}
	if m.OverturnedVerifications != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.OverturnedVerifications))
		i--
		dAtA[i] = 0x20
	}
	if m.UpheldVerifications != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.UpheldVerifications))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalVerifications != 0 {
		i = encodeVarintVerifierActivity(dAtA, i, uint64(m.TotalVerifications))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintVerifierActivity(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerifierActivity(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerifierActivity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VerifierActivity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovVerifierActivity(uint64(l))
	}
	if m.TotalVerifications != 0 {
		n += 1 + sovVerifierActivity(uint64(m.TotalVerifications))
	}
	if m.UpheldVerifications != 0 {
		n += 1 + sovVerifierActivity(uint64(m.UpheldVerifications))
	}
	if m.OverturnedVerifications != 0 {
		n += 1 + sovVerifierActivity(uint64(m.OverturnedVerifications))
	}
	if m.UnchallengedVerifications != 0 {
		n += 1 + sovVerifierActivity(uint64(m.UnchallengedVerifications))
	}
	if m.EpochVerifications != 0 {
		n += 1 + sovVerifierActivity(uint64(m.EpochVerifications))
	}
	if m.EpochChallengesResolved != 0 {
		n += 1 + sovVerifierActivity(uint64(m.EpochChallengesResolved))
	}
	if m.ConsecutiveOverturns != 0 {
		n += 1 + sovVerifierActivity(uint64(m.ConsecutiveOverturns))
	}
	if m.ConsecutiveUpheld != 0 {
		n += 1 + sovVerifierActivity(uint64(m.ConsecutiveUpheld))
	}
	if m.OverturnCooldownUntil != 0 {
		n += 1 + sovVerifierActivity(uint64(m.OverturnCooldownUntil))
	}
	if m.SlashCount != 0 {
		n += 1 + sovVerifierActivity(uint64(m.SlashCount))
	}
	return n
}

func sovVerifierActivity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerifierActivity(x uint64) (n int) {
	return sovVerifierActivity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VerifierActivity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifierActivity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifierActivity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifierActivity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifierActivity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierActivity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVerifications", wireType)
			}
			m.TotalVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVerifications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpheldVerifications", wireType)
			}
			m.UpheldVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpheldVerifications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverturnedVerifications", wireType)
			}
			m.OverturnedVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OverturnedVerifications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnchallengedVerifications", wireType)
			}
			m.UnchallengedVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnchallengedVerifications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochVerifications", wireType)
			}
			m.EpochVerifications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochVerifications |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochChallengesResolved", wireType)
			}
			m.EpochChallengesResolved = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochChallengesResolved |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveOverturns", wireType)
			}
			m.ConsecutiveOverturns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveOverturns |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveUpheld", wireType)
			}
			m.ConsecutiveUpheld = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveUpheld |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverturnCooldownUntil", wireType)
			}
			m.OverturnCooldownUntil = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OverturnCooldownUntil |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashCount", wireType)
			}
			m.SlashCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVerifierActivity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerifierActivity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerifierActivity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerifierActivity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierActivity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerifierActivity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerifierActivity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerifierActivity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerifierActivity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerifierActivity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerifierActivity = fmt.Errorf("proto: unexpected end of group")
)
